package main

import (
	"github.com/arulkarim/ngodingyuk-server/internal/domain"
	"gorm.io/gorm"
)

func seedSQLQuizzesExp(db *gorm.DB) {
	quizzes := []domain.LessonQuiz{
		// COURSE 4 LESSON 1
		{ID: quizUUID(4, 1, 1), LessonID: lessonUUID(4, 1), OrderIndex: 1,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 1?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 1, 2), LessonID: lessonUUID(4, 1), OrderIndex: 2,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 2?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 1, 3), LessonID: lessonUUID(4, 1), OrderIndex: 3,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 3?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 1, 4), LessonID: lessonUUID(4, 1), OrderIndex: 4,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 4?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 1, 5), LessonID: lessonUUID(4, 1), OrderIndex: 5,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 5?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 1, 6), LessonID: lessonUUID(4, 1), OrderIndex: 6,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 6?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 1, 7), LessonID: lessonUUID(4, 1), OrderIndex: 7,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 7?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 1, 8), LessonID: lessonUUID(4, 1), OrderIndex: 8,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 8?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 1, 9), LessonID: lessonUUID(4, 1), OrderIndex: 9,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 9?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 1, 10), LessonID: lessonUUID(4, 1), OrderIndex: 10,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 10?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		// COURSE 4 LESSON 2
		{ID: quizUUID(4, 2, 1), LessonID: lessonUUID(4, 2), OrderIndex: 1,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 1?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 2, 2), LessonID: lessonUUID(4, 2), OrderIndex: 2,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 2?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 2, 3), LessonID: lessonUUID(4, 2), OrderIndex: 3,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 3?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 2, 4), LessonID: lessonUUID(4, 2), OrderIndex: 4,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 4?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 2, 5), LessonID: lessonUUID(4, 2), OrderIndex: 5,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 5?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 2, 6), LessonID: lessonUUID(4, 2), OrderIndex: 6,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 6?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 2, 7), LessonID: lessonUUID(4, 2), OrderIndex: 7,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 7?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 2, 8), LessonID: lessonUUID(4, 2), OrderIndex: 8,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 8?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 2, 9), LessonID: lessonUUID(4, 2), OrderIndex: 9,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 9?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 2, 10), LessonID: lessonUUID(4, 2), OrderIndex: 10,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 10?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		// COURSE 4 LESSON 3
		{ID: quizUUID(4, 3, 1), LessonID: lessonUUID(4, 3), OrderIndex: 1,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 1?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 3, 2), LessonID: lessonUUID(4, 3), OrderIndex: 2,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 2?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 3, 3), LessonID: lessonUUID(4, 3), OrderIndex: 3,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 3?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 3, 4), LessonID: lessonUUID(4, 3), OrderIndex: 4,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 4?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 3, 5), LessonID: lessonUUID(4, 3), OrderIndex: 5,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 5?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 3, 6), LessonID: lessonUUID(4, 3), OrderIndex: 6,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 6?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 3, 7), LessonID: lessonUUID(4, 3), OrderIndex: 7,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 7?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 3, 8), LessonID: lessonUUID(4, 3), OrderIndex: 8,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 8?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 3, 9), LessonID: lessonUUID(4, 3), OrderIndex: 9,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 9?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 3, 10), LessonID: lessonUUID(4, 3), OrderIndex: 10,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 10?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		// COURSE 4 LESSON 4
		{ID: quizUUID(4, 4, 1), LessonID: lessonUUID(4, 4), OrderIndex: 1,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 1?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 4, 2), LessonID: lessonUUID(4, 4), OrderIndex: 2,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 2?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 4, 3), LessonID: lessonUUID(4, 4), OrderIndex: 3,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 3?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 4, 4), LessonID: lessonUUID(4, 4), OrderIndex: 4,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 4?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 4, 5), LessonID: lessonUUID(4, 4), OrderIndex: 5,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 5?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 4, 6), LessonID: lessonUUID(4, 4), OrderIndex: 6,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 6?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 4, 7), LessonID: lessonUUID(4, 4), OrderIndex: 7,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 7?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 4, 8), LessonID: lessonUUID(4, 4), OrderIndex: 8,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 8?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 4, 9), LessonID: lessonUUID(4, 4), OrderIndex: 9,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 9?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 4, 10), LessonID: lessonUUID(4, 4), OrderIndex: 10,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 10?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		// COURSE 4 LESSON 5
		{ID: quizUUID(4, 5, 1), LessonID: lessonUUID(4, 5), OrderIndex: 1,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 1?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 5, 2), LessonID: lessonUUID(4, 5), OrderIndex: 2,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 2?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 5, 3), LessonID: lessonUUID(4, 5), OrderIndex: 3,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 3?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 5, 4), LessonID: lessonUUID(4, 5), OrderIndex: 4,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 4?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 5, 5), LessonID: lessonUUID(4, 5), OrderIndex: 5,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 5?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 5, 6), LessonID: lessonUUID(4, 5), OrderIndex: 6,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 6?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 5, 7), LessonID: lessonUUID(4, 5), OrderIndex: 7,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 7?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 5, 8), LessonID: lessonUUID(4, 5), OrderIndex: 8,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 8?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 5, 9), LessonID: lessonUUID(4, 5), OrderIndex: 9,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 9?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(4, 5, 10), LessonID: lessonUUID(4, 5), OrderIndex: 10,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 10?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		// COURSE 5 LESSON 1
		{ID: quizUUID(5, 1, 1), LessonID: lessonUUID(5, 1), OrderIndex: 1,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 1?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 1, 2), LessonID: lessonUUID(5, 1), OrderIndex: 2,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 2?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 1, 3), LessonID: lessonUUID(5, 1), OrderIndex: 3,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 3?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 1, 4), LessonID: lessonUUID(5, 1), OrderIndex: 4,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 4?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 1, 5), LessonID: lessonUUID(5, 1), OrderIndex: 5,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 5?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 1, 6), LessonID: lessonUUID(5, 1), OrderIndex: 6,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 6?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 1, 7), LessonID: lessonUUID(5, 1), OrderIndex: 7,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 7?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 1, 8), LessonID: lessonUUID(5, 1), OrderIndex: 8,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 8?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 1, 9), LessonID: lessonUUID(5, 1), OrderIndex: 9,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 9?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 1, 10), LessonID: lessonUUID(5, 1), OrderIndex: 10,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 10?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		// COURSE 5 LESSON 2
		{ID: quizUUID(5, 2, 1), LessonID: lessonUUID(5, 2), OrderIndex: 1,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 1?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 2, 2), LessonID: lessonUUID(5, 2), OrderIndex: 2,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 2?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 2, 3), LessonID: lessonUUID(5, 2), OrderIndex: 3,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 3?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 2, 4), LessonID: lessonUUID(5, 2), OrderIndex: 4,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 4?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 2, 5), LessonID: lessonUUID(5, 2), OrderIndex: 5,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 5?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 2, 6), LessonID: lessonUUID(5, 2), OrderIndex: 6,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 6?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 2, 7), LessonID: lessonUUID(5, 2), OrderIndex: 7,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 7?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 2, 8), LessonID: lessonUUID(5, 2), OrderIndex: 8,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 8?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 2, 9), LessonID: lessonUUID(5, 2), OrderIndex: 9,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 9?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 2, 10), LessonID: lessonUUID(5, 2), OrderIndex: 10,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 10?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		// COURSE 5 LESSON 3
		{ID: quizUUID(5, 3, 1), LessonID: lessonUUID(5, 3), OrderIndex: 1,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 1?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 3, 2), LessonID: lessonUUID(5, 3), OrderIndex: 2,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 2?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 3, 3), LessonID: lessonUUID(5, 3), OrderIndex: 3,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 3?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 3, 4), LessonID: lessonUUID(5, 3), OrderIndex: 4,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 4?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 3, 5), LessonID: lessonUUID(5, 3), OrderIndex: 5,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 5?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 3, 6), LessonID: lessonUUID(5, 3), OrderIndex: 6,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 6?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 3, 7), LessonID: lessonUUID(5, 3), OrderIndex: 7,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 7?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 3, 8), LessonID: lessonUUID(5, 3), OrderIndex: 8,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 8?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 3, 9), LessonID: lessonUUID(5, 3), OrderIndex: 9,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 9?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 3, 10), LessonID: lessonUUID(5, 3), OrderIndex: 10,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 10?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		// COURSE 5 LESSON 4
		{ID: quizUUID(5, 4, 1), LessonID: lessonUUID(5, 4), OrderIndex: 1,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 1?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 4, 2), LessonID: lessonUUID(5, 4), OrderIndex: 2,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 2?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 4, 3), LessonID: lessonUUID(5, 4), OrderIndex: 3,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 3?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 4, 4), LessonID: lessonUUID(5, 4), OrderIndex: 4,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 4?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 4, 5), LessonID: lessonUUID(5, 4), OrderIndex: 5,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 5?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 4, 6), LessonID: lessonUUID(5, 4), OrderIndex: 6,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 6?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 4, 7), LessonID: lessonUUID(5, 4), OrderIndex: 7,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 7?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 4, 8), LessonID: lessonUUID(5, 4), OrderIndex: 8,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 8?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 4, 9), LessonID: lessonUUID(5, 4), OrderIndex: 9,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 9?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 4, 10), LessonID: lessonUUID(5, 4), OrderIndex: 10,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 10?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		// COURSE 5 LESSON 5
		{ID: quizUUID(5, 5, 1), LessonID: lessonUUID(5, 5), OrderIndex: 1,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 1?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 5, 2), LessonID: lessonUUID(5, 5), OrderIndex: 2,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 2?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 5, 3), LessonID: lessonUUID(5, 5), OrderIndex: 3,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 3?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 5, 4), LessonID: lessonUUID(5, 5), OrderIndex: 4,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 4?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 5, 5), LessonID: lessonUUID(5, 5), OrderIndex: 5,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 5?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 5, 6), LessonID: lessonUUID(5, 5), OrderIndex: 6,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 6?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 5, 7), LessonID: lessonUUID(5, 5), OrderIndex: 7,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 7?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 5, 8), LessonID: lessonUUID(5, 5), OrderIndex: 8,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 8?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 5, 9), LessonID: lessonUUID(5, 5), OrderIndex: 9,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 9?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(5, 5, 10), LessonID: lessonUUID(5, 5), OrderIndex: 10,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 10?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		// COURSE 6 LESSON 1
		{ID: quizUUID(6, 1, 1), LessonID: lessonUUID(6, 1), OrderIndex: 1,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 1?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 1, 2), LessonID: lessonUUID(6, 1), OrderIndex: 2,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 2?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 1, 3), LessonID: lessonUUID(6, 1), OrderIndex: 3,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 3?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 1, 4), LessonID: lessonUUID(6, 1), OrderIndex: 4,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 4?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 1, 5), LessonID: lessonUUID(6, 1), OrderIndex: 5,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 5?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 1, 6), LessonID: lessonUUID(6, 1), OrderIndex: 6,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 6?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 1, 7), LessonID: lessonUUID(6, 1), OrderIndex: 7,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 7?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 1, 8), LessonID: lessonUUID(6, 1), OrderIndex: 8,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 8?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 1, 9), LessonID: lessonUUID(6, 1), OrderIndex: 9,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 9?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 1, 10), LessonID: lessonUUID(6, 1), OrderIndex: 10,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 10?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		// COURSE 6 LESSON 2
		{ID: quizUUID(6, 2, 1), LessonID: lessonUUID(6, 2), OrderIndex: 1,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 1?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 2, 2), LessonID: lessonUUID(6, 2), OrderIndex: 2,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 2?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 2, 3), LessonID: lessonUUID(6, 2), OrderIndex: 3,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 3?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 2, 4), LessonID: lessonUUID(6, 2), OrderIndex: 4,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 4?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 2, 5), LessonID: lessonUUID(6, 2), OrderIndex: 5,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 5?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 2, 6), LessonID: lessonUUID(6, 2), OrderIndex: 6,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 6?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 2, 7), LessonID: lessonUUID(6, 2), OrderIndex: 7,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 7?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 2, 8), LessonID: lessonUUID(6, 2), OrderIndex: 8,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 8?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 2, 9), LessonID: lessonUUID(6, 2), OrderIndex: 9,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 9?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 2, 10), LessonID: lessonUUID(6, 2), OrderIndex: 10,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 10?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		// COURSE 6 LESSON 3
		{ID: quizUUID(6, 3, 1), LessonID: lessonUUID(6, 3), OrderIndex: 1,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 1?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 3, 2), LessonID: lessonUUID(6, 3), OrderIndex: 2,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 2?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 3, 3), LessonID: lessonUUID(6, 3), OrderIndex: 3,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 3?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 3, 4), LessonID: lessonUUID(6, 3), OrderIndex: 4,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 4?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 3, 5), LessonID: lessonUUID(6, 3), OrderIndex: 5,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 5?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 3, 6), LessonID: lessonUUID(6, 3), OrderIndex: 6,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 6?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 3, 7), LessonID: lessonUUID(6, 3), OrderIndex: 7,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 7?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 3, 8), LessonID: lessonUUID(6, 3), OrderIndex: 8,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 8?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 3, 9), LessonID: lessonUUID(6, 3), OrderIndex: 9,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 9?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 3, 10), LessonID: lessonUUID(6, 3), OrderIndex: 10,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 10?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		// COURSE 6 LESSON 4
		{ID: quizUUID(6, 4, 1), LessonID: lessonUUID(6, 4), OrderIndex: 1,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 1?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 4, 2), LessonID: lessonUUID(6, 4), OrderIndex: 2,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 2?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 4, 3), LessonID: lessonUUID(6, 4), OrderIndex: 3,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 3?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 4, 4), LessonID: lessonUUID(6, 4), OrderIndex: 4,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 4?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 4, 5), LessonID: lessonUUID(6, 4), OrderIndex: 5,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 5?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 4, 6), LessonID: lessonUUID(6, 4), OrderIndex: 6,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 6?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 4, 7), LessonID: lessonUUID(6, 4), OrderIndex: 7,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 7?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 4, 8), LessonID: lessonUUID(6, 4), OrderIndex: 8,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 8?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 4, 9), LessonID: lessonUUID(6, 4), OrderIndex: 9,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 9?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 4, 10), LessonID: lessonUUID(6, 4), OrderIndex: 10,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 10?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		// COURSE 6 LESSON 5
		{ID: quizUUID(6, 5, 1), LessonID: lessonUUID(6, 5), OrderIndex: 1,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 1?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 5, 2), LessonID: lessonUUID(6, 5), OrderIndex: 2,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 2?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 5, 3), LessonID: lessonUUID(6, 5), OrderIndex: 3,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 3?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 5, 4), LessonID: lessonUUID(6, 5), OrderIndex: 4,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 4?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 5, 5), LessonID: lessonUUID(6, 5), OrderIndex: 5,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 5?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 5, 6), LessonID: lessonUUID(6, 5), OrderIndex: 6,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 6?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 5, 7), LessonID: lessonUUID(6, 5), OrderIndex: 7,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario JOIN nomor 7?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 2, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 5, 8), LessonID: lessonUUID(6, 5), OrderIndex: 8,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario GROUP BY nomor 8?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 3, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 5, 9), LessonID: lessonUUID(6, 5), OrderIndex: 9,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario SELECT nomor 9?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 0, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
		{ID: quizUUID(6, 5, 10), LessonID: lessonUUID(6, 5), OrderIndex: 10,
			QuestionID: "Berdasarkan standar relasional, kueri manakah yang sering digunakan pada skenario WHERE nomor 10?",
			OptionsID: j(`["SELECT", "WHERE", "JOIN", "GROUP BY"]`), CorrectIndex: 1, ExplanationID: sp("Skenario SQL ini umum digunakan dalam DML dan DDL modern.")},
	}
	for i := range quizzes {
		upsertQuiz(db, &quizzes[i])
	}
}
