package main

import (
	"github.com/arulkarim/ngodingyuk-server/internal/domain"
	"gorm.io/gorm"
)

func seedGoQuizzesExp(db *gorm.DB) {
	quizzes := []domain.LessonQuiz{
		// COURSE 1 LESSON 1
		{ID: quizUUID(1, 1, 1), LessonID: lessonUUID(1, 1), OrderIndex: 1,
			QuestionID: "Pertanyaan seputar Variabel nomor urut 1 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Variabel", "B: Tipe Data", "C: Fungsi", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Variabel di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 1, 2), LessonID: lessonUUID(1, 1), OrderIndex: 2,
			QuestionID: "Pertanyaan seputar Tipe Data nomor urut 2 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Tipe Data", "B: Fungsi", "C: Looping", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Tipe Data di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 1, 3), LessonID: lessonUUID(1, 1), OrderIndex: 3,
			QuestionID: "Pertanyaan seputar Fungsi nomor urut 3 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Fungsi", "B: Looping", "C: Kondisional", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Fungsi di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 1, 4), LessonID: lessonUUID(1, 1), OrderIndex: 4,
			QuestionID: "Pertanyaan seputar Looping nomor urut 4 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Looping", "B: Kondisional", "C: Struct", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Looping di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 1, 5), LessonID: lessonUUID(1, 1), OrderIndex: 5,
			QuestionID: "Pertanyaan seputar Kondisional nomor urut 5 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Kondisional", "B: Struct", "C: Pointer", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Kondisional di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 1, 6), LessonID: lessonUUID(1, 1), OrderIndex: 6,
			QuestionID: "Pertanyaan seputar Struct nomor urut 6 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Struct", "B: Pointer", "C: Map", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Struct di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 1, 7), LessonID: lessonUUID(1, 1), OrderIndex: 7,
			QuestionID: "Pertanyaan seputar Pointer nomor urut 7 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Pointer", "B: Map", "C: Slice", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Pointer di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 1, 8), LessonID: lessonUUID(1, 1), OrderIndex: 8,
			QuestionID: "Pertanyaan seputar Map nomor urut 8 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Map", "B: Slice", "C: Interface", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Map di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 1, 9), LessonID: lessonUUID(1, 1), OrderIndex: 9,
			QuestionID: "Pertanyaan seputar Slice nomor urut 9 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Slice", "B: Interface", "C: Variabel", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Slice di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 1, 10), LessonID: lessonUUID(1, 1), OrderIndex: 10,
			QuestionID: "Pertanyaan seputar Interface nomor urut 10 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Interface", "B: Variabel", "C: Tipe Data", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Interface di bahasa Go bertipe statis.")},
		// COURSE 1 LESSON 2
		{ID: quizUUID(1, 2, 1), LessonID: lessonUUID(1, 2), OrderIndex: 1,
			QuestionID: "Pertanyaan seputar Variabel nomor urut 1 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Variabel", "B: Tipe Data", "C: Fungsi", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Variabel di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 2, 2), LessonID: lessonUUID(1, 2), OrderIndex: 2,
			QuestionID: "Pertanyaan seputar Tipe Data nomor urut 2 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Tipe Data", "B: Fungsi", "C: Looping", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Tipe Data di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 2, 3), LessonID: lessonUUID(1, 2), OrderIndex: 3,
			QuestionID: "Pertanyaan seputar Fungsi nomor urut 3 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Fungsi", "B: Looping", "C: Kondisional", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Fungsi di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 2, 4), LessonID: lessonUUID(1, 2), OrderIndex: 4,
			QuestionID: "Pertanyaan seputar Looping nomor urut 4 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Looping", "B: Kondisional", "C: Struct", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Looping di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 2, 5), LessonID: lessonUUID(1, 2), OrderIndex: 5,
			QuestionID: "Pertanyaan seputar Kondisional nomor urut 5 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Kondisional", "B: Struct", "C: Pointer", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Kondisional di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 2, 6), LessonID: lessonUUID(1, 2), OrderIndex: 6,
			QuestionID: "Pertanyaan seputar Struct nomor urut 6 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Struct", "B: Pointer", "C: Map", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Struct di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 2, 7), LessonID: lessonUUID(1, 2), OrderIndex: 7,
			QuestionID: "Pertanyaan seputar Pointer nomor urut 7 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Pointer", "B: Map", "C: Slice", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Pointer di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 2, 8), LessonID: lessonUUID(1, 2), OrderIndex: 8,
			QuestionID: "Pertanyaan seputar Map nomor urut 8 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Map", "B: Slice", "C: Interface", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Map di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 2, 9), LessonID: lessonUUID(1, 2), OrderIndex: 9,
			QuestionID: "Pertanyaan seputar Slice nomor urut 9 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Slice", "B: Interface", "C: Variabel", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Slice di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 2, 10), LessonID: lessonUUID(1, 2), OrderIndex: 10,
			QuestionID: "Pertanyaan seputar Interface nomor urut 10 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Interface", "B: Variabel", "C: Tipe Data", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Interface di bahasa Go bertipe statis.")},
		// COURSE 1 LESSON 3
		{ID: quizUUID(1, 3, 1), LessonID: lessonUUID(1, 3), OrderIndex: 1,
			QuestionID: "Pertanyaan seputar Variabel nomor urut 1 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Variabel", "B: Tipe Data", "C: Fungsi", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Variabel di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 3, 2), LessonID: lessonUUID(1, 3), OrderIndex: 2,
			QuestionID: "Pertanyaan seputar Tipe Data nomor urut 2 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Tipe Data", "B: Fungsi", "C: Looping", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Tipe Data di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 3, 3), LessonID: lessonUUID(1, 3), OrderIndex: 3,
			QuestionID: "Pertanyaan seputar Fungsi nomor urut 3 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Fungsi", "B: Looping", "C: Kondisional", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Fungsi di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 3, 4), LessonID: lessonUUID(1, 3), OrderIndex: 4,
			QuestionID: "Pertanyaan seputar Looping nomor urut 4 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Looping", "B: Kondisional", "C: Struct", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Looping di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 3, 5), LessonID: lessonUUID(1, 3), OrderIndex: 5,
			QuestionID: "Pertanyaan seputar Kondisional nomor urut 5 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Kondisional", "B: Struct", "C: Pointer", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Kondisional di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 3, 6), LessonID: lessonUUID(1, 3), OrderIndex: 6,
			QuestionID: "Pertanyaan seputar Struct nomor urut 6 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Struct", "B: Pointer", "C: Map", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Struct di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 3, 7), LessonID: lessonUUID(1, 3), OrderIndex: 7,
			QuestionID: "Pertanyaan seputar Pointer nomor urut 7 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Pointer", "B: Map", "C: Slice", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Pointer di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 3, 8), LessonID: lessonUUID(1, 3), OrderIndex: 8,
			QuestionID: "Pertanyaan seputar Map nomor urut 8 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Map", "B: Slice", "C: Interface", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Map di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 3, 9), LessonID: lessonUUID(1, 3), OrderIndex: 9,
			QuestionID: "Pertanyaan seputar Slice nomor urut 9 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Slice", "B: Interface", "C: Variabel", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Slice di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 3, 10), LessonID: lessonUUID(1, 3), OrderIndex: 10,
			QuestionID: "Pertanyaan seputar Interface nomor urut 10 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Interface", "B: Variabel", "C: Tipe Data", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Interface di bahasa Go bertipe statis.")},
		// COURSE 1 LESSON 4
		{ID: quizUUID(1, 4, 1), LessonID: lessonUUID(1, 4), OrderIndex: 1,
			QuestionID: "Pertanyaan seputar Variabel nomor urut 1 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Variabel", "B: Tipe Data", "C: Fungsi", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Variabel di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 4, 2), LessonID: lessonUUID(1, 4), OrderIndex: 2,
			QuestionID: "Pertanyaan seputar Tipe Data nomor urut 2 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Tipe Data", "B: Fungsi", "C: Looping", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Tipe Data di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 4, 3), LessonID: lessonUUID(1, 4), OrderIndex: 3,
			QuestionID: "Pertanyaan seputar Fungsi nomor urut 3 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Fungsi", "B: Looping", "C: Kondisional", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Fungsi di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 4, 4), LessonID: lessonUUID(1, 4), OrderIndex: 4,
			QuestionID: "Pertanyaan seputar Looping nomor urut 4 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Looping", "B: Kondisional", "C: Struct", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Looping di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 4, 5), LessonID: lessonUUID(1, 4), OrderIndex: 5,
			QuestionID: "Pertanyaan seputar Kondisional nomor urut 5 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Kondisional", "B: Struct", "C: Pointer", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Kondisional di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 4, 6), LessonID: lessonUUID(1, 4), OrderIndex: 6,
			QuestionID: "Pertanyaan seputar Struct nomor urut 6 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Struct", "B: Pointer", "C: Map", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Struct di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 4, 7), LessonID: lessonUUID(1, 4), OrderIndex: 7,
			QuestionID: "Pertanyaan seputar Pointer nomor urut 7 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Pointer", "B: Map", "C: Slice", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Pointer di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 4, 8), LessonID: lessonUUID(1, 4), OrderIndex: 8,
			QuestionID: "Pertanyaan seputar Map nomor urut 8 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Map", "B: Slice", "C: Interface", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Map di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 4, 9), LessonID: lessonUUID(1, 4), OrderIndex: 9,
			QuestionID: "Pertanyaan seputar Slice nomor urut 9 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Slice", "B: Interface", "C: Variabel", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Slice di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 4, 10), LessonID: lessonUUID(1, 4), OrderIndex: 10,
			QuestionID: "Pertanyaan seputar Interface nomor urut 10 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Interface", "B: Variabel", "C: Tipe Data", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Interface di bahasa Go bertipe statis.")},
		// COURSE 1 LESSON 5
		{ID: quizUUID(1, 5, 1), LessonID: lessonUUID(1, 5), OrderIndex: 1,
			QuestionID: "Pertanyaan seputar Variabel nomor urut 1 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Variabel", "B: Tipe Data", "C: Fungsi", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Variabel di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 5, 2), LessonID: lessonUUID(1, 5), OrderIndex: 2,
			QuestionID: "Pertanyaan seputar Tipe Data nomor urut 2 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Tipe Data", "B: Fungsi", "C: Looping", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Tipe Data di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 5, 3), LessonID: lessonUUID(1, 5), OrderIndex: 3,
			QuestionID: "Pertanyaan seputar Fungsi nomor urut 3 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Fungsi", "B: Looping", "C: Kondisional", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Fungsi di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 5, 4), LessonID: lessonUUID(1, 5), OrderIndex: 4,
			QuestionID: "Pertanyaan seputar Looping nomor urut 4 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Looping", "B: Kondisional", "C: Struct", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Looping di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 5, 5), LessonID: lessonUUID(1, 5), OrderIndex: 5,
			QuestionID: "Pertanyaan seputar Kondisional nomor urut 5 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Kondisional", "B: Struct", "C: Pointer", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Kondisional di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 5, 6), LessonID: lessonUUID(1, 5), OrderIndex: 6,
			QuestionID: "Pertanyaan seputar Struct nomor urut 6 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Struct", "B: Pointer", "C: Map", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Struct di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 5, 7), LessonID: lessonUUID(1, 5), OrderIndex: 7,
			QuestionID: "Pertanyaan seputar Pointer nomor urut 7 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Pointer", "B: Map", "C: Slice", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Pointer di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 5, 8), LessonID: lessonUUID(1, 5), OrderIndex: 8,
			QuestionID: "Pertanyaan seputar Map nomor urut 8 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Map", "B: Slice", "C: Interface", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Map di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 5, 9), LessonID: lessonUUID(1, 5), OrderIndex: 9,
			QuestionID: "Pertanyaan seputar Slice nomor urut 9 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Slice", "B: Interface", "C: Variabel", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Slice di bahasa Go bertipe statis.")},
		{ID: quizUUID(1, 5, 10), LessonID: lessonUUID(1, 5), OrderIndex: 10,
			QuestionID: "Pertanyaan seputar Interface nomor urut 10 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Interface", "B: Variabel", "C: Tipe Data", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Interface di bahasa Go bertipe statis.")},
		// COURSE 2 LESSON 1
		{ID: quizUUID(2, 1, 1), LessonID: lessonUUID(2, 1), OrderIndex: 1,
			QuestionID: "Pertanyaan seputar Variabel nomor urut 1 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Variabel", "B: Tipe Data", "C: Fungsi", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Variabel di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 1, 2), LessonID: lessonUUID(2, 1), OrderIndex: 2,
			QuestionID: "Pertanyaan seputar Tipe Data nomor urut 2 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Tipe Data", "B: Fungsi", "C: Looping", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Tipe Data di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 1, 3), LessonID: lessonUUID(2, 1), OrderIndex: 3,
			QuestionID: "Pertanyaan seputar Fungsi nomor urut 3 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Fungsi", "B: Looping", "C: Kondisional", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Fungsi di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 1, 4), LessonID: lessonUUID(2, 1), OrderIndex: 4,
			QuestionID: "Pertanyaan seputar Looping nomor urut 4 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Looping", "B: Kondisional", "C: Struct", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Looping di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 1, 5), LessonID: lessonUUID(2, 1), OrderIndex: 5,
			QuestionID: "Pertanyaan seputar Kondisional nomor urut 5 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Kondisional", "B: Struct", "C: Pointer", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Kondisional di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 1, 6), LessonID: lessonUUID(2, 1), OrderIndex: 6,
			QuestionID: "Pertanyaan seputar Struct nomor urut 6 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Struct", "B: Pointer", "C: Map", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Struct di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 1, 7), LessonID: lessonUUID(2, 1), OrderIndex: 7,
			QuestionID: "Pertanyaan seputar Pointer nomor urut 7 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Pointer", "B: Map", "C: Slice", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Pointer di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 1, 8), LessonID: lessonUUID(2, 1), OrderIndex: 8,
			QuestionID: "Pertanyaan seputar Map nomor urut 8 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Map", "B: Slice", "C: Interface", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Map di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 1, 9), LessonID: lessonUUID(2, 1), OrderIndex: 9,
			QuestionID: "Pertanyaan seputar Slice nomor urut 9 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Slice", "B: Interface", "C: Variabel", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Slice di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 1, 10), LessonID: lessonUUID(2, 1), OrderIndex: 10,
			QuestionID: "Pertanyaan seputar Interface nomor urut 10 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Interface", "B: Variabel", "C: Tipe Data", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Interface di bahasa Go bertipe statis.")},
		// COURSE 2 LESSON 2
		{ID: quizUUID(2, 2, 1), LessonID: lessonUUID(2, 2), OrderIndex: 1,
			QuestionID: "Pertanyaan seputar Variabel nomor urut 1 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Variabel", "B: Tipe Data", "C: Fungsi", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Variabel di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 2, 2), LessonID: lessonUUID(2, 2), OrderIndex: 2,
			QuestionID: "Pertanyaan seputar Tipe Data nomor urut 2 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Tipe Data", "B: Fungsi", "C: Looping", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Tipe Data di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 2, 3), LessonID: lessonUUID(2, 2), OrderIndex: 3,
			QuestionID: "Pertanyaan seputar Fungsi nomor urut 3 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Fungsi", "B: Looping", "C: Kondisional", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Fungsi di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 2, 4), LessonID: lessonUUID(2, 2), OrderIndex: 4,
			QuestionID: "Pertanyaan seputar Looping nomor urut 4 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Looping", "B: Kondisional", "C: Struct", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Looping di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 2, 5), LessonID: lessonUUID(2, 2), OrderIndex: 5,
			QuestionID: "Pertanyaan seputar Kondisional nomor urut 5 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Kondisional", "B: Struct", "C: Pointer", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Kondisional di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 2, 6), LessonID: lessonUUID(2, 2), OrderIndex: 6,
			QuestionID: "Pertanyaan seputar Struct nomor urut 6 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Struct", "B: Pointer", "C: Map", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Struct di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 2, 7), LessonID: lessonUUID(2, 2), OrderIndex: 7,
			QuestionID: "Pertanyaan seputar Pointer nomor urut 7 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Pointer", "B: Map", "C: Slice", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Pointer di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 2, 8), LessonID: lessonUUID(2, 2), OrderIndex: 8,
			QuestionID: "Pertanyaan seputar Map nomor urut 8 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Map", "B: Slice", "C: Interface", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Map di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 2, 9), LessonID: lessonUUID(2, 2), OrderIndex: 9,
			QuestionID: "Pertanyaan seputar Slice nomor urut 9 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Slice", "B: Interface", "C: Variabel", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Slice di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 2, 10), LessonID: lessonUUID(2, 2), OrderIndex: 10,
			QuestionID: "Pertanyaan seputar Interface nomor urut 10 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Interface", "B: Variabel", "C: Tipe Data", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Interface di bahasa Go bertipe statis.")},
		// COURSE 2 LESSON 3
		{ID: quizUUID(2, 3, 1), LessonID: lessonUUID(2, 3), OrderIndex: 1,
			QuestionID: "Pertanyaan seputar Variabel nomor urut 1 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Variabel", "B: Tipe Data", "C: Fungsi", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Variabel di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 3, 2), LessonID: lessonUUID(2, 3), OrderIndex: 2,
			QuestionID: "Pertanyaan seputar Tipe Data nomor urut 2 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Tipe Data", "B: Fungsi", "C: Looping", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Tipe Data di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 3, 3), LessonID: lessonUUID(2, 3), OrderIndex: 3,
			QuestionID: "Pertanyaan seputar Fungsi nomor urut 3 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Fungsi", "B: Looping", "C: Kondisional", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Fungsi di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 3, 4), LessonID: lessonUUID(2, 3), OrderIndex: 4,
			QuestionID: "Pertanyaan seputar Looping nomor urut 4 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Looping", "B: Kondisional", "C: Struct", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Looping di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 3, 5), LessonID: lessonUUID(2, 3), OrderIndex: 5,
			QuestionID: "Pertanyaan seputar Kondisional nomor urut 5 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Kondisional", "B: Struct", "C: Pointer", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Kondisional di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 3, 6), LessonID: lessonUUID(2, 3), OrderIndex: 6,
			QuestionID: "Pertanyaan seputar Struct nomor urut 6 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Struct", "B: Pointer", "C: Map", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Struct di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 3, 7), LessonID: lessonUUID(2, 3), OrderIndex: 7,
			QuestionID: "Pertanyaan seputar Pointer nomor urut 7 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Pointer", "B: Map", "C: Slice", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Pointer di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 3, 8), LessonID: lessonUUID(2, 3), OrderIndex: 8,
			QuestionID: "Pertanyaan seputar Map nomor urut 8 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Map", "B: Slice", "C: Interface", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Map di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 3, 9), LessonID: lessonUUID(2, 3), OrderIndex: 9,
			QuestionID: "Pertanyaan seputar Slice nomor urut 9 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Slice", "B: Interface", "C: Variabel", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Slice di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 3, 10), LessonID: lessonUUID(2, 3), OrderIndex: 10,
			QuestionID: "Pertanyaan seputar Interface nomor urut 10 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Interface", "B: Variabel", "C: Tipe Data", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Interface di bahasa Go bertipe statis.")},
		// COURSE 2 LESSON 4
		{ID: quizUUID(2, 4, 1), LessonID: lessonUUID(2, 4), OrderIndex: 1,
			QuestionID: "Pertanyaan seputar Variabel nomor urut 1 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Variabel", "B: Tipe Data", "C: Fungsi", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Variabel di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 4, 2), LessonID: lessonUUID(2, 4), OrderIndex: 2,
			QuestionID: "Pertanyaan seputar Tipe Data nomor urut 2 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Tipe Data", "B: Fungsi", "C: Looping", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Tipe Data di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 4, 3), LessonID: lessonUUID(2, 4), OrderIndex: 3,
			QuestionID: "Pertanyaan seputar Fungsi nomor urut 3 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Fungsi", "B: Looping", "C: Kondisional", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Fungsi di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 4, 4), LessonID: lessonUUID(2, 4), OrderIndex: 4,
			QuestionID: "Pertanyaan seputar Looping nomor urut 4 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Looping", "B: Kondisional", "C: Struct", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Looping di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 4, 5), LessonID: lessonUUID(2, 4), OrderIndex: 5,
			QuestionID: "Pertanyaan seputar Kondisional nomor urut 5 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Kondisional", "B: Struct", "C: Pointer", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Kondisional di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 4, 6), LessonID: lessonUUID(2, 4), OrderIndex: 6,
			QuestionID: "Pertanyaan seputar Struct nomor urut 6 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Struct", "B: Pointer", "C: Map", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Struct di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 4, 7), LessonID: lessonUUID(2, 4), OrderIndex: 7,
			QuestionID: "Pertanyaan seputar Pointer nomor urut 7 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Pointer", "B: Map", "C: Slice", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Pointer di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 4, 8), LessonID: lessonUUID(2, 4), OrderIndex: 8,
			QuestionID: "Pertanyaan seputar Map nomor urut 8 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Map", "B: Slice", "C: Interface", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Map di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 4, 9), LessonID: lessonUUID(2, 4), OrderIndex: 9,
			QuestionID: "Pertanyaan seputar Slice nomor urut 9 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Slice", "B: Interface", "C: Variabel", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Slice di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 4, 10), LessonID: lessonUUID(2, 4), OrderIndex: 10,
			QuestionID: "Pertanyaan seputar Interface nomor urut 10 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Interface", "B: Variabel", "C: Tipe Data", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Interface di bahasa Go bertipe statis.")},
		// COURSE 2 LESSON 5
		{ID: quizUUID(2, 5, 1), LessonID: lessonUUID(2, 5), OrderIndex: 1,
			QuestionID: "Pertanyaan seputar Variabel nomor urut 1 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Variabel", "B: Tipe Data", "C: Fungsi", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Variabel di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 5, 2), LessonID: lessonUUID(2, 5), OrderIndex: 2,
			QuestionID: "Pertanyaan seputar Tipe Data nomor urut 2 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Tipe Data", "B: Fungsi", "C: Looping", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Tipe Data di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 5, 3), LessonID: lessonUUID(2, 5), OrderIndex: 3,
			QuestionID: "Pertanyaan seputar Fungsi nomor urut 3 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Fungsi", "B: Looping", "C: Kondisional", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Fungsi di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 5, 4), LessonID: lessonUUID(2, 5), OrderIndex: 4,
			QuestionID: "Pertanyaan seputar Looping nomor urut 4 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Looping", "B: Kondisional", "C: Struct", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Looping di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 5, 5), LessonID: lessonUUID(2, 5), OrderIndex: 5,
			QuestionID: "Pertanyaan seputar Kondisional nomor urut 5 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Kondisional", "B: Struct", "C: Pointer", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Kondisional di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 5, 6), LessonID: lessonUUID(2, 5), OrderIndex: 6,
			QuestionID: "Pertanyaan seputar Struct nomor urut 6 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Struct", "B: Pointer", "C: Map", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Struct di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 5, 7), LessonID: lessonUUID(2, 5), OrderIndex: 7,
			QuestionID: "Pertanyaan seputar Pointer nomor urut 7 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Pointer", "B: Map", "C: Slice", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Pointer di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 5, 8), LessonID: lessonUUID(2, 5), OrderIndex: 8,
			QuestionID: "Pertanyaan seputar Map nomor urut 8 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Map", "B: Slice", "C: Interface", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Map di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 5, 9), LessonID: lessonUUID(2, 5), OrderIndex: 9,
			QuestionID: "Pertanyaan seputar Slice nomor urut 9 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Slice", "B: Interface", "C: Variabel", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Slice di bahasa Go bertipe statis.")},
		{ID: quizUUID(2, 5, 10), LessonID: lessonUUID(2, 5), OrderIndex: 10,
			QuestionID: "Pertanyaan seputar Interface nomor urut 10 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Interface", "B: Variabel", "C: Tipe Data", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Interface di bahasa Go bertipe statis.")},
		// COURSE 3 LESSON 1
		{ID: quizUUID(3, 1, 1), LessonID: lessonUUID(3, 1), OrderIndex: 1,
			QuestionID: "Pertanyaan seputar Variabel nomor urut 1 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Variabel", "B: Tipe Data", "C: Fungsi", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Variabel di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 1, 2), LessonID: lessonUUID(3, 1), OrderIndex: 2,
			QuestionID: "Pertanyaan seputar Tipe Data nomor urut 2 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Tipe Data", "B: Fungsi", "C: Looping", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Tipe Data di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 1, 3), LessonID: lessonUUID(3, 1), OrderIndex: 3,
			QuestionID: "Pertanyaan seputar Fungsi nomor urut 3 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Fungsi", "B: Looping", "C: Kondisional", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Fungsi di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 1, 4), LessonID: lessonUUID(3, 1), OrderIndex: 4,
			QuestionID: "Pertanyaan seputar Looping nomor urut 4 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Looping", "B: Kondisional", "C: Struct", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Looping di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 1, 5), LessonID: lessonUUID(3, 1), OrderIndex: 5,
			QuestionID: "Pertanyaan seputar Kondisional nomor urut 5 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Kondisional", "B: Struct", "C: Pointer", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Kondisional di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 1, 6), LessonID: lessonUUID(3, 1), OrderIndex: 6,
			QuestionID: "Pertanyaan seputar Struct nomor urut 6 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Struct", "B: Pointer", "C: Map", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Struct di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 1, 7), LessonID: lessonUUID(3, 1), OrderIndex: 7,
			QuestionID: "Pertanyaan seputar Pointer nomor urut 7 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Pointer", "B: Map", "C: Slice", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Pointer di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 1, 8), LessonID: lessonUUID(3, 1), OrderIndex: 8,
			QuestionID: "Pertanyaan seputar Map nomor urut 8 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Map", "B: Slice", "C: Interface", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Map di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 1, 9), LessonID: lessonUUID(3, 1), OrderIndex: 9,
			QuestionID: "Pertanyaan seputar Slice nomor urut 9 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Slice", "B: Interface", "C: Variabel", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Slice di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 1, 10), LessonID: lessonUUID(3, 1), OrderIndex: 10,
			QuestionID: "Pertanyaan seputar Interface nomor urut 10 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Interface", "B: Variabel", "C: Tipe Data", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Interface di bahasa Go bertipe statis.")},
		// COURSE 3 LESSON 2
		{ID: quizUUID(3, 2, 1), LessonID: lessonUUID(3, 2), OrderIndex: 1,
			QuestionID: "Pertanyaan seputar Variabel nomor urut 1 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Variabel", "B: Tipe Data", "C: Fungsi", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Variabel di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 2, 2), LessonID: lessonUUID(3, 2), OrderIndex: 2,
			QuestionID: "Pertanyaan seputar Tipe Data nomor urut 2 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Tipe Data", "B: Fungsi", "C: Looping", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Tipe Data di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 2, 3), LessonID: lessonUUID(3, 2), OrderIndex: 3,
			QuestionID: "Pertanyaan seputar Fungsi nomor urut 3 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Fungsi", "B: Looping", "C: Kondisional", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Fungsi di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 2, 4), LessonID: lessonUUID(3, 2), OrderIndex: 4,
			QuestionID: "Pertanyaan seputar Looping nomor urut 4 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Looping", "B: Kondisional", "C: Struct", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Looping di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 2, 5), LessonID: lessonUUID(3, 2), OrderIndex: 5,
			QuestionID: "Pertanyaan seputar Kondisional nomor urut 5 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Kondisional", "B: Struct", "C: Pointer", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Kondisional di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 2, 6), LessonID: lessonUUID(3, 2), OrderIndex: 6,
			QuestionID: "Pertanyaan seputar Struct nomor urut 6 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Struct", "B: Pointer", "C: Map", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Struct di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 2, 7), LessonID: lessonUUID(3, 2), OrderIndex: 7,
			QuestionID: "Pertanyaan seputar Pointer nomor urut 7 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Pointer", "B: Map", "C: Slice", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Pointer di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 2, 8), LessonID: lessonUUID(3, 2), OrderIndex: 8,
			QuestionID: "Pertanyaan seputar Map nomor urut 8 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Map", "B: Slice", "C: Interface", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Map di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 2, 9), LessonID: lessonUUID(3, 2), OrderIndex: 9,
			QuestionID: "Pertanyaan seputar Slice nomor urut 9 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Slice", "B: Interface", "C: Variabel", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Slice di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 2, 10), LessonID: lessonUUID(3, 2), OrderIndex: 10,
			QuestionID: "Pertanyaan seputar Interface nomor urut 10 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Interface", "B: Variabel", "C: Tipe Data", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Interface di bahasa Go bertipe statis.")},
		// COURSE 3 LESSON 3
		{ID: quizUUID(3, 3, 1), LessonID: lessonUUID(3, 3), OrderIndex: 1,
			QuestionID: "Pertanyaan seputar Variabel nomor urut 1 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Variabel", "B: Tipe Data", "C: Fungsi", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Variabel di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 3, 2), LessonID: lessonUUID(3, 3), OrderIndex: 2,
			QuestionID: "Pertanyaan seputar Tipe Data nomor urut 2 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Tipe Data", "B: Fungsi", "C: Looping", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Tipe Data di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 3, 3), LessonID: lessonUUID(3, 3), OrderIndex: 3,
			QuestionID: "Pertanyaan seputar Fungsi nomor urut 3 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Fungsi", "B: Looping", "C: Kondisional", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Fungsi di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 3, 4), LessonID: lessonUUID(3, 3), OrderIndex: 4,
			QuestionID: "Pertanyaan seputar Looping nomor urut 4 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Looping", "B: Kondisional", "C: Struct", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Looping di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 3, 5), LessonID: lessonUUID(3, 3), OrderIndex: 5,
			QuestionID: "Pertanyaan seputar Kondisional nomor urut 5 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Kondisional", "B: Struct", "C: Pointer", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Kondisional di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 3, 6), LessonID: lessonUUID(3, 3), OrderIndex: 6,
			QuestionID: "Pertanyaan seputar Struct nomor urut 6 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Struct", "B: Pointer", "C: Map", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Struct di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 3, 7), LessonID: lessonUUID(3, 3), OrderIndex: 7,
			QuestionID: "Pertanyaan seputar Pointer nomor urut 7 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Pointer", "B: Map", "C: Slice", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Pointer di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 3, 8), LessonID: lessonUUID(3, 3), OrderIndex: 8,
			QuestionID: "Pertanyaan seputar Map nomor urut 8 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Map", "B: Slice", "C: Interface", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Map di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 3, 9), LessonID: lessonUUID(3, 3), OrderIndex: 9,
			QuestionID: "Pertanyaan seputar Slice nomor urut 9 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Slice", "B: Interface", "C: Variabel", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Slice di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 3, 10), LessonID: lessonUUID(3, 3), OrderIndex: 10,
			QuestionID: "Pertanyaan seputar Interface nomor urut 10 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Interface", "B: Variabel", "C: Tipe Data", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Interface di bahasa Go bertipe statis.")},
		// COURSE 3 LESSON 4
		{ID: quizUUID(3, 4, 1), LessonID: lessonUUID(3, 4), OrderIndex: 1,
			QuestionID: "Pertanyaan seputar Variabel nomor urut 1 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Variabel", "B: Tipe Data", "C: Fungsi", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Variabel di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 4, 2), LessonID: lessonUUID(3, 4), OrderIndex: 2,
			QuestionID: "Pertanyaan seputar Tipe Data nomor urut 2 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Tipe Data", "B: Fungsi", "C: Looping", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Tipe Data di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 4, 3), LessonID: lessonUUID(3, 4), OrderIndex: 3,
			QuestionID: "Pertanyaan seputar Fungsi nomor urut 3 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Fungsi", "B: Looping", "C: Kondisional", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Fungsi di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 4, 4), LessonID: lessonUUID(3, 4), OrderIndex: 4,
			QuestionID: "Pertanyaan seputar Looping nomor urut 4 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Looping", "B: Kondisional", "C: Struct", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Looping di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 4, 5), LessonID: lessonUUID(3, 4), OrderIndex: 5,
			QuestionID: "Pertanyaan seputar Kondisional nomor urut 5 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Kondisional", "B: Struct", "C: Pointer", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Kondisional di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 4, 6), LessonID: lessonUUID(3, 4), OrderIndex: 6,
			QuestionID: "Pertanyaan seputar Struct nomor urut 6 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Struct", "B: Pointer", "C: Map", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Struct di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 4, 7), LessonID: lessonUUID(3, 4), OrderIndex: 7,
			QuestionID: "Pertanyaan seputar Pointer nomor urut 7 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Pointer", "B: Map", "C: Slice", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Pointer di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 4, 8), LessonID: lessonUUID(3, 4), OrderIndex: 8,
			QuestionID: "Pertanyaan seputar Map nomor urut 8 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Map", "B: Slice", "C: Interface", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Map di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 4, 9), LessonID: lessonUUID(3, 4), OrderIndex: 9,
			QuestionID: "Pertanyaan seputar Slice nomor urut 9 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Slice", "B: Interface", "C: Variabel", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Slice di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 4, 10), LessonID: lessonUUID(3, 4), OrderIndex: 10,
			QuestionID: "Pertanyaan seputar Interface nomor urut 10 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Interface", "B: Variabel", "C: Tipe Data", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Interface di bahasa Go bertipe statis.")},
		// COURSE 3 LESSON 5
		{ID: quizUUID(3, 5, 1), LessonID: lessonUUID(3, 5), OrderIndex: 1,
			QuestionID: "Pertanyaan seputar Variabel nomor urut 1 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Variabel", "B: Tipe Data", "C: Fungsi", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Variabel di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 5, 2), LessonID: lessonUUID(3, 5), OrderIndex: 2,
			QuestionID: "Pertanyaan seputar Tipe Data nomor urut 2 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Tipe Data", "B: Fungsi", "C: Looping", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Tipe Data di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 5, 3), LessonID: lessonUUID(3, 5), OrderIndex: 3,
			QuestionID: "Pertanyaan seputar Fungsi nomor urut 3 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Fungsi", "B: Looping", "C: Kondisional", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Fungsi di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 5, 4), LessonID: lessonUUID(3, 5), OrderIndex: 4,
			QuestionID: "Pertanyaan seputar Looping nomor urut 4 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Looping", "B: Kondisional", "C: Struct", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Looping di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 5, 5), LessonID: lessonUUID(3, 5), OrderIndex: 5,
			QuestionID: "Pertanyaan seputar Kondisional nomor urut 5 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Kondisional", "B: Struct", "C: Pointer", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Kondisional di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 5, 6), LessonID: lessonUUID(3, 5), OrderIndex: 6,
			QuestionID: "Pertanyaan seputar Struct nomor urut 6 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Struct", "B: Pointer", "C: Map", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Struct di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 5, 7), LessonID: lessonUUID(3, 5), OrderIndex: 7,
			QuestionID: "Pertanyaan seputar Pointer nomor urut 7 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Pointer", "B: Map", "C: Slice", "D: Salah Semua"]`), CorrectIndex: 2, ExplanationID: sp("Penjelasan: Opsi array index 2 adalah konsep fundamental dari Pointer di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 5, 8), LessonID: lessonUUID(3, 5), OrderIndex: 8,
			QuestionID: "Pertanyaan seputar Map nomor urut 8 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Map", "B: Slice", "C: Interface", "D: Salah Semua"]`), CorrectIndex: 3, ExplanationID: sp("Penjelasan: Opsi array index 3 adalah konsep fundamental dari Map di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 5, 9), LessonID: lessonUUID(3, 5), OrderIndex: 9,
			QuestionID: "Pertanyaan seputar Slice nomor urut 9 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Slice", "B: Interface", "C: Variabel", "D: Salah Semua"]`), CorrectIndex: 0, ExplanationID: sp("Penjelasan: Opsi array index 0 adalah konsep fundamental dari Slice di bahasa Go bertipe statis.")},
		{ID: quizUUID(3, 5, 10), LessonID: lessonUUID(3, 5), OrderIndex: 10,
			QuestionID: "Pertanyaan seputar Interface nomor urut 10 pada kelas lanjutan. Manakah yang benar?",
			OptionsID: j(`["A: Interface", "B: Variabel", "C: Tipe Data", "D: Salah Semua"]`), CorrectIndex: 1, ExplanationID: sp("Penjelasan: Opsi array index 1 adalah konsep fundamental dari Interface di bahasa Go bertipe statis.")},
	}
	for i := range quizzes {
		upsertQuiz(db, &quizzes[i])
	}
}
