package main

import (
	"github.com/arulkarim/ngodingyuk-server/internal/domain"
	"gorm.io/gorm"
)

func seedGoChallenges(db *gorm.DB) {
	challenges := []domain.Challenge{
		// GO EASY (5)
		{ID: challengeUUID(14), Slug: "fizzbuzz-pabrik-mie", Language: "golang", Difficulty: "easy", XPReward: 10, OrderIndex: 1,
			TitleID: "FizzBuzz di Pabrik Mie Pak Slamet", TitleEN: sp("FizzBuzz at Pak Slamet's Noodle Factory"),
			StoryID: "Kamu baru magang di pabrik mie milik Pak Slamet.\n\nSetiap mie ke-3 diberi label **'Fizz'**, ke-5 **'Buzz'**, ke-15 **'FizzBuzz'**.\n\n\"Tolong buatkan program untuk cetak label dari 1 sampai 20!\"",
			StoryEN: sp("You just started an internship at Pak Slamet's noodle factory.\n\nEvery 3rd noodle gets **'Fizz'**, 5th **'Buzz'**, 15th **'FizzBuzz'**.\n\n\"Please make a program to print labels from 1 to 20!\""),
			TaskID:  "Cetak label FizzBuzz dari 1 sampai 20.", TaskEN: sp("Print FizzBuzz labels from 1 to 20."),
			HintID: sp("Cek kelipatan 15 dulu sebelum 3 dan 5."), HintEN: sp("Check multiple of 15 first before 3 and 5."),
			StarterCode:    sp("package main\n\nimport \"fmt\"\n\nfunc main() {\n    // TODO: cetak FizzBuzz dari 1 sampai 20\n}"),
			SolutionCode:   sp("package main\n\nimport \"fmt\"\n\nfunc main() {\n    for i := 1; i <= 20; i++ {\n        switch {\n        case i%15 == 0:\n            fmt.Println(\"FizzBuzz\")\n        case i%3 == 0:\n            fmt.Println(\"Fizz\")\n        case i%5 == 0:\n            fmt.Println(\"Buzz\")\n        default:\n            fmt.Println(i)\n        }\n    }\n}"),
			TestCases:      j([]map[string]interface{}{{"input": "", "expected_output": "1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz\n16\n17\nFizz\n19\nBuzz\n"}}),
			ExpectedOutput: j("1\n2\nFizz\n4\nBuzz\nFizz\n7\n8\nFizz\nBuzz\n11\nFizz\n13\n14\nFizzBuzz\n16\n17\nFizz\n19\nBuzz\n"),
		},
		{ID: challengeUUID(15), Slug: "hitung-kembalian-warung", Language: "golang", Difficulty: "easy", XPReward: 10, OrderIndex: 2,
			TitleID: "Kasir Warung Bu Tini", TitleEN: sp("Bu Tini's Warung Cashier"),
			StoryID: "Bu Tini punya warung kelontong kecil.\n\n\"Tolong buatkan program untuk menghitung kembalian agar tidak salah hitung!\"",
			StoryEN: sp("Bu Tini runs a small store.\n\n\"Please make a program to calculate change so I don't make mistakes!\""),
			TaskID:  "Buat fungsi `hitungKembalian(harga, bayar int) int`. Jika bayar < harga, return -1. Cetak untuk harga=15000, bayar=20000.", TaskEN: sp("Create `hitungKembalian(harga, bayar int) int`. If bayar < harga, return -1. Print for 15000, 20000."),
			HintID: sp("Cek bayar >= harga. Kembalian = bayar - harga."), HintEN: sp("Check bayar >= harga. Change = bayar - harga."),
			StarterCode:    sp("package main\n\nimport \"fmt\"\n\n// TODO: buat fungsi hitungKembalian\n\nfunc main() {\n    hasil := hitungKembalian(15000, 20000)\n    fmt.Println(hasil)\n}"),
			SolutionCode:   sp("package main\n\nimport \"fmt\"\n\nfunc hitungKembalian(harga, bayar int) int {\n    if bayar < harga { return -1 }\n    return bayar - harga\n}\n\nfunc main() {\n    hasil := hitungKembalian(15000, 20000)\n    fmt.Println(hasil)\n}"),
			TestCases:      j([]map[string]interface{}{{"input": "", "expected_output": "5000\n"}}),
			ExpectedOutput: j("5000\n"),
		},
		{ID: challengeUUID(16), Slug: "palindrom-kata-sandi", Language: "golang", Difficulty: "easy", XPReward: 10, OrderIndex: 3,
			TitleID: "Palindrom Kata Sandi Pak RT", TitleEN: sp("Pak RT's Password Palindrome"),
			StoryID: "Pak RT mau bikin kata sandi palindrom.\n\n\"Tolong cek apakah kata yang saya ketik itu palindrom atau bukan.\"",
			StoryEN: sp("The neighborhood chief wants a palindrome password.\n\n\"Please check whether a word is a palindrome or not.\""),
			TaskID:  "Buat `isPalindrom(s string) bool`. Cetak true untuk \"katak\" dan false untuk \"golang\".", TaskEN: sp("Create `isPalindrom(s string) bool`. Print true for \"katak\" and false for \"golang\"."),
			HintID: sp("Bandingkan karakter dari depan dan belakang."), HintEN: sp("Compare characters from front and back."),
			StarterCode:    sp("package main\n\nimport \"fmt\"\n\n// TODO: buat fungsi isPalindrom\n\nfunc main() {\n    fmt.Println(isPalindrom(\"katak\"))\n    fmt.Println(isPalindrom(\"golang\"))\n}"),
			SolutionCode:   sp("package main\n\nimport \"fmt\"\n\nfunc isPalindrom(s string) bool {\n    r := []rune(s)\n    for i, j := 0, len(r)-1; i < j; i, j = i+1, j-1 {\n        if r[i] != r[j] { return false }\n    }\n    return true\n}\n\nfunc main() {\n    fmt.Println(isPalindrom(\"katak\"))\n    fmt.Println(isPalindrom(\"golang\"))\n}"),
			TestCases:      j([]map[string]interface{}{{"input": "", "expected_output": "true\nfalse\n"}}),
			ExpectedOutput: j("true\nfalse\n"),
		},
		{ID: challengeUUID(17), Slug: "fibonacci-kurir", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 4,
			TitleID: "Deret Fibonacci Pak Pos", TitleEN: sp("Pak Pos's Fibonacci Sequence"),
			StoryID: "Pak Pos menentukan rute sesuai deret Fibonacci!\n\n\"Tolong cetak 10 angka pertama deret Fibonacci.\"",
			StoryEN: sp("Pak Pos determines routes by Fibonacci sequence!\n\n\"Please print the first 10 Fibonacci numbers.\""),
			TaskID:  "Cetak 10 angka pertama deret Fibonacci (mulai dari 0).", TaskEN: sp("Print the first 10 Fibonacci numbers (starting from 0)."),
			HintID: sp("a, b := 0, 1 lalu swap: a, b = b, a+b"), HintEN: sp("a, b := 0, 1 then swap: a, b = b, a+b"),
			StarterCode:    sp("package main\n\nimport \"fmt\"\n\nfunc main() {\n    // TODO: cetak 10 angka Fibonacci pertama\n}"),
			SolutionCode:   sp("package main\n\nimport \"fmt\"\n\nfunc main() {\n    a, b := 0, 1\n    for i := 0; i < 10; i++ {\n        fmt.Println(a)\n        a, b = b, a+b\n    }\n}"),
			TestCases:      j([]map[string]interface{}{{"input": "", "expected_output": "0\n1\n1\n2\n3\n5\n8\n13\n21\n34\n"}}),
			ExpectedOutput: j("0\n1\n1\n2\n3\n5\n8\n13\n21\n34\n"),
		},
		{ID: challengeUUID(18), Slug: "balik-kata-nama", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 5,
			TitleID: "Balik Nama untuk Kode Rahasia", TitleEN: sp("Reverse Name for Secret Code"),
			StoryID: "Geng anak-anak punya tradisi: buat kode nama rahasia dengan membalik setiap kata.\n\nContoh: \"Budi Santoso\" → \"iduB osotnaSˮ",
			StoryEN: sp("The kids have a tradition: create secret name codes by reversing each word.\n\nExample: \"Budi Santoso\" → \"iduB osotnaSˮ"),
			TaskID:  "Buat `balikKata(s string) string` yang membalik setiap kata. Cetak untuk \"Budi Santoso Rahardjo\".", TaskEN: sp("Create `balikKata(s string) string` that reverses each word. Print for \"Budi Santoso Rahardjo\"."),
			HintID: sp("Split string, reverse tiap kata, join kembali."), HintEN: sp("Split string, reverse each word, join back."),
			StarterCode:    sp("package main\n\nimport (\n    \"fmt\"\n    \"strings\"\n)\n\n// TODO: buat fungsi balikKata\n\nfunc main() {\n    fmt.Println(balikKata(\"Budi Santoso Rahardjo\"))\n}"),
			SolutionCode:   sp("package main\n\nimport (\n    \"fmt\"\n    \"strings\"\n)\n\nfunc balikKata(s string) string {\n    words := strings.Fields(s)\n    for i, w := range words {\n        r := []rune(w)\n        for l, r2 := 0, len(r)-1; l < r2; l, r2 = l+1, r2-1 {\n            r[l], r[r2] = r[r2], r[l]\n        }\n        words[i] = string(r)\n    }\n    return strings.Join(words, \" \")\n}\n\nfunc main() {\n    fmt.Println(balikKata(\"Budi Santoso Rahardjo\"))\n}"),
			TestCases:      j([]map[string]interface{}{{"input": "", "expected_output": "iduB osotnaSˮ ojdrahaR\n"}}),
			ExpectedOutput: j("iduB osotnaSˮ ojdrahaR\n"),
		},

		// GO MEDIUM (4)
		{ID: challengeUUID(19), Slug: "sistem-antrian-puskesmas", Language: "golang", Difficulty: "medium", XPReward: 30, OrderIndex: 6,
			TitleID: "Sistem Antrian Puskesmas", TitleEN: sp("Clinic Queue System"),
			StoryID: "Bantu Puskesmas buat sistem antrian: Enqueue, Dequeue, Peek, IsEmpty.",
			StoryEN: sp("Help the clinic build a queue: Enqueue, Dequeue, Peek, IsEmpty."),
			TaskID:  "Implementasi Queue struct. Tambah Budi, Ani, Caca, panggil 1, lihat berikutnya.", TaskEN: sp("Implement Queue struct. Add Budi, Ani, Caca, dequeue 1, peek next."),
			HintID: sp("Gunakan slice []string sebagai storage."), HintEN: sp("Use []string slice as storage."),
			StarterCode:    sp("package main\n\nimport \"fmt\"\n\ntype Queue struct {\n    // TODO\n}\n\n// TODO: Enqueue, Dequeue, Peek, IsEmpty\n\nfunc main() {\n    q := Queue{}\n    q.Enqueue(\"Budi\")\n    q.Enqueue(\"Ani\")\n    q.Enqueue(\"Caca\")\n    fmt.Println(\"Dipanggil:\", q.Dequeue())\n    fmt.Println(\"Berikutnya:\", q.Peek())\n}"),
			SolutionCode:   sp("package main\n\nimport \"fmt\"\n\ntype Queue struct { items []string }\nfunc (q *Queue) Enqueue(n string) { q.items = append(q.items, n) }\nfunc (q *Queue) Dequeue() string { if q.IsEmpty() { return \"\" }; i := q.items[0]; q.items = q.items[1:]; return i }\nfunc (q *Queue) Peek() string { if q.IsEmpty() { return \"\" }; return q.items[0] }\nfunc (q *Queue) IsEmpty() bool { return len(q.items) == 0 }\n\nfunc main() {\n    q := Queue{}\n    q.Enqueue(\"Budi\")\n    q.Enqueue(\"Ani\")\n    q.Enqueue(\"Caca\")\n    fmt.Println(\"Dipanggil:\", q.Dequeue())\n    fmt.Println(\"Berikutnya:\", q.Peek())\n}"),
			TestCases:      j([]map[string]interface{}{{"input": "", "expected_output": "Dipanggil: Budi\nBerikutnya: Ani\n"}}),
			ExpectedOutput: j("Dipanggil: Budi\nBerikutnya: Ani\n"),
		},
		{ID: challengeUUID(20), Slug: "enkripsi-caesar-cipher", Language: "golang", Difficulty: "medium", XPReward: 30, OrderIndex: 7,
			TitleID: "Pesan Rahasia Caesar Cipher", TitleEN: sp("Secret Message with Caesar Cipher"),
			StoryID: "Enkripsi pesan dengan Caesar Cipher — geser setiap huruf sebanyak N posisi.",
			StoryEN: sp("Encrypt messages with Caesar Cipher — shift each letter by N positions."),
			TaskID:  "Buat `caesarCipher(text string, shift int) string`. Enkripsi \"Halo Dunia\" shift 3, lalu dekripsi.", TaskEN: sp("Create `caesarCipher(text string, shift int) string`. Encrypt \"Halo Dunia\" shift 3, then decrypt."),
			HintID: sp("Gunakan modulo 26 untuk wrap around."), HintEN: sp("Use modulo 26 for wrapping around."),
			StarterCode:    sp("package main\n\nimport \"fmt\"\n\n// TODO: buat caesarCipher\n\nfunc main() {\n    enc := caesarCipher(\"Halo Dunia\", 3)\n    fmt.Println(enc)\n    fmt.Println(caesarCipher(enc, -3))\n}"),
			SolutionCode:   sp("package main\n\nimport \"fmt\"\n\nfunc caesarCipher(text string, shift int) string {\n    r := []rune(text)\n    for i, ch := range r {\n        switch {\n        case ch >= 'A' && ch <= 'Z': r[i] = rune('A' + (int(ch-'A')+shift+26)%26)\n        case ch >= 'a' && ch <= 'z': r[i] = rune('a' + (int(ch-'a')+shift+26)%26)\n        }\n    }\n    return string(r)\n}\n\nfunc main() {\n    enc := caesarCipher(\"Halo Dunia\", 3)\n    fmt.Println(enc)\n    fmt.Println(caesarCipher(enc, -3))\n}"),
			TestCases:      j([]map[string]interface{}{{"input": "", "expected_output": "Kdor Gxqld\nHalo Dunia\n"}}),
			ExpectedOutput: j("Kdor Gxqld\nHalo Dunia\n"),
		},
		{ID: challengeUUID(21), Slug: "word-frequency-counter", Language: "golang", Difficulty: "medium", XPReward: 25, OrderIndex: 8,
			TitleID: "Hitung Frekuensi Kata", TitleEN: sp("Word Frequency Counter"),
			StoryID: "Guru Bahasa Indonesia ingin tahu kata yang paling sering muncul dalam teks.",
			StoryEN: sp("A teacher wants to know which words appear most often in a text."),
			TaskID:  "Buat `hitungKata(text string) map[string]int`. Cetak frekuensi (sorted) untuk kalimat yang diberikan.", TaskEN: sp("Create `hitungKata(text string) map[string]int`. Print sorted frequency."),
			HintID: sp("Gunakan strings.FieldsFunc + map."), HintEN: sp("Use strings.FieldsFunc + map."),
			StarterCode:    sp("package main\n\nimport (\n    \"fmt\"\n    \"sort\"\n    \"strings\"\n    \"unicode\"\n)\n\n// TODO: hitungKata\n\nfunc main() {\n    freq := hitungKata(\"Budi pergi ke pasar. Budi beli sayur di pasar.\")\n    keys := make([]string, 0, len(freq))\n    for k := range freq { keys = append(keys, k) }\n    sort.Strings(keys)\n    for _, k := range keys { fmt.Printf(\"%s: %d\\n\", k, freq[k]) }\n}"),
			SolutionCode:   sp("package main\n\nimport (\n    \"fmt\"\n    \"sort\"\n    \"strings\"\n    \"unicode\"\n)\n\nfunc hitungKata(text string) map[string]int {\n    freq := make(map[string]int)\n    words := strings.FieldsFunc(strings.ToLower(text), func(r rune) bool { return !unicode.IsLetter(r) })\n    for _, w := range words { if w != \"\" { freq[w]++ } }\n    return freq\n}\n\nfunc main() {\n    freq := hitungKata(\"Budi pergi ke pasar. Budi beli sayur di pasar.\")\n    keys := make([]string, 0, len(freq))\n    for k := range freq { keys = append(keys, k) }\n    sort.Strings(keys)\n    for _, k := range keys { fmt.Printf(\"%s: %d\\n\", k, freq[k]) }\n}"),
			TestCases:      j([]map[string]interface{}{{"input": "", "expected_output": "beli: 1\nbudi: 2\ndi: 1\nke: 1\npasar: 2\npergi: 1\nsayur: 1\n"}}),
			ExpectedOutput: j("beli: 1\nbudi: 2\ndi: 1\nke: 1\npasar: 2\npergi: 1\nsayur: 1\n"),
		},

		// GO HARD (2)
		{ID: challengeUUID(23), Slug: "lru-cache", Language: "golang", Difficulty: "hard", XPReward: 60, OrderIndex: 10,
			TitleID: "Implementasi LRU Cache", TitleEN: sp("Implement LRU Cache"),
			StoryID: "Tim backend butuh LRU Cache — cache yang membuang data paling lama tidak dipakai saat penuh.\n\n\"Implement LRU Cache kapasitas 3. Support Get dan Put, O(1).\"",
			StoryEN: sp("The backend team needs an LRU Cache — evicts least recently used when full.\n\n\"Implement LRU Cache with capacity 3. Support Get and Put, O(1).\""),
			TaskID:  "Implementasi LRUCache: Get(key) int, Put(key, val int). Get return -1 jika tidak ada.", TaskEN: sp("Implement LRUCache: Get(key) int, Put(key, val int). Get returns -1 if not found."),
			HintID: sp("Gunakan doubly linked list + map."), HintEN: sp("Use doubly linked list + map."),
			StarterCode:    sp("package main\n\nimport \"fmt\"\n\n// TODO: LRUCache struct dan method\n\nfunc main() {\n    cache := NewLRUCache(3)\n    cache.Put(1, 1)\n    cache.Put(2, 2)\n    cache.Put(3, 3)\n    fmt.Println(cache.Get(1))\n    cache.Put(4, 4)\n    fmt.Println(cache.Get(2))\n}"),
			SolutionCode:   sp("package main\n\nimport \"fmt\"\n\ntype Node struct { key, val int; prev, next *Node }\ntype LRUCache struct { cap int; cache map[int]*Node; head, tail *Node }\nfunc NewLRUCache(c int) *LRUCache { h, t := &Node{}, &Node{}; h.next = t; t.prev = h; return &LRUCache{cap: c, cache: make(map[int]*Node), head: h, tail: t} }\nfunc (c *LRUCache) remove(n *Node) { n.prev.next, n.next.prev = n.next, n.prev }\nfunc (c *LRUCache) insertFront(n *Node) { n.next = c.head.next; n.prev = c.head; c.head.next.prev = n; c.head.next = n }\nfunc (c *LRUCache) Get(key int) int { if n, ok := c.cache[key]; ok { c.remove(n); c.insertFront(n); return n.val }; return -1 }\nfunc (c *LRUCache) Put(key, val int) { if n, ok := c.cache[key]; ok { c.remove(n); n.val = val; c.insertFront(n); return }; if len(c.cache) == c.cap { lru := c.tail.prev; c.remove(lru); delete(c.cache, lru.key) }; n := &Node{key: key, val: val}; c.insertFront(n); c.cache[key] = n }\nfunc main() { cache := NewLRUCache(3); cache.Put(1,1); cache.Put(2,2); cache.Put(3,3); fmt.Println(cache.Get(1)); cache.Put(4,4); fmt.Println(cache.Get(2)) }"),
			TestCases:      j([]map[string]interface{}{{"input": "", "expected_output": "1\n-1\n"}}),
			ExpectedOutput: j("1\n-1\n"),
		},
		{ID: challengeUUID(25), Slug: "mini-json-parser", Language: "golang", Difficulty: "hard", XPReward: 70, OrderIndex: 12,
			TitleID: "Mini JSON Parser dengan Reflection", TitleEN: sp("Mini JSON Parser with Reflection"),
			StoryID: "Tim platform butuh library untuk serialize struct Go ke JSON menggunakan reflection — tanpa encoding/json.",
			StoryEN: sp("The platform team needs a library to serialize Go structs to JSON using reflection — without encoding/json."),
			TaskID:  "Buat `Marshal(v interface{}) string` yang konversi struct ke JSON string via reflect.", TaskEN: sp("Create `Marshal(v interface{}) string` that converts struct to JSON string via reflect."),
			HintID: sp("Gunakan reflect.ValueOf, reflect.TypeOf, iterate NumField."), HintEN: sp("Use reflect.ValueOf, reflect.TypeOf, iterate NumField."),
			StarterCode:    sp("package main\n\nimport (\n    \"fmt\"\n    \"reflect\"\n    \"strconv\"\n    \"strings\"\n)\n\n// TODO: Marshal function\n\ntype Produk struct {\n    Nama  string `json:\"nama\"`\n    Harga int    `json:\"harga\"`\n}\n\nfunc main() {\n    p := Produk{Nama: \"Batik\", Harga: 150000}\n    fmt.Println(Marshal(p))\n}"),
			SolutionCode:   sp("package main\n\nimport (\n    \"fmt\"\n    \"reflect\"\n    \"strconv\"\n    \"strings\"\n)\n\nfunc Marshal(v interface{}) string {\n    val := reflect.ValueOf(v)\n    if val.Kind() == reflect.Ptr { val = val.Elem() }\n    if val.Kind() != reflect.Struct { return \"null\" }\n    t := val.Type()\n    parts := []string{}\n    for i := 0; i < val.NumField(); i++ {\n        f := t.Field(i)\n        name := f.Tag.Get(\"json\")\n        if name == \"\" { name = strings.ToLower(f.Name) }\n        fv := val.Field(i)\n        var jv string\n        switch fv.Kind() {\n        case reflect.String: jv = `\"` + fv.String() + `\"`\n        case reflect.Int, reflect.Int64: jv = strconv.FormatInt(fv.Int(), 10)\n        }\n        parts = append(parts, `\"`+name+`\":`+jv)\n    }\n    return \"{\" + strings.Join(parts, \",\") + \"}\"\n}\n\ntype Produk struct {\n    Nama  string `json:\"nama\"`\n    Harga int    `json:\"harga\"`\n}\n\nfunc main() {\n    p := Produk{Nama: \"Batik\", Harga: 150000}\n    fmt.Println(Marshal(p))\n}"),
			TestCases:      j([]map[string]interface{}{{"input": "", "expected_output": "{\"nama\":\"Batik\",\"harga\":150000}\n"}}),
			ExpectedOutput: j("{\"nama\":\"Batik\",\"harga\":150000}\n"),
		},
	}

	for i := range challenges {
		upsert(db, &challenges[i], challenges[i].Slug)
	}
}
