package main

import (
	"github.com/arulkarim/ngodingyuk-server/internal/domain"
	"gorm.io/gorm"
)

func seedSQLChallengesExp(db *gorm.DB) {
	challenges := []domain.Challenge{
		{ID: challengeUUID(201), Slug: "toko-select-201", Language: "sql", Difficulty: "medium", XPReward: 30, OrderIndex: 201,
			TitleID: "Toko Kelontong Makmur: Data Master", TitleEN: sp("Toko Kelontong Makmur: Data Master"),
			StoryID: "Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nTampilkan seluruh data pada tabel master `users`. Tolong jangan filter apapun dulu.", StoryEN: sp("Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nTampilkan seluruh data pada tabel master `users`. Tolong jangan filter apapun dulu."),
			TaskID: "SELECT seluruh kolom dari tabel `users`.", TaskEN: sp("SELECT seluruh kolom dari tabel `users`."),
			ExpectedOutput: j(`[{"id":1,"name":"Budi"},{"id":2,"name":"Siti"}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "name", "type": "text"}], "rows": [{"id": 1, "name": "Budi"}, {"id": 2, "name": "Siti"}]}]}`),
		},
		{ID: challengeUUID(202), Slug: "toko-where-202", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 202,
			TitleID: "Toko Kelontong Makmur: Pencarian Aktif", TitleEN: sp("Toko Kelontong Makmur: Pencarian Aktif"),
			StoryID: "Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nHanya tampilkan record yang statusnya 'active' di tabel `users` untuk dihubungi hari ini.", StoryEN: sp("Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nHanya tampilkan record yang statusnya 'active' di tabel `users` untuk dihubungi hari ini."),
			TaskID: "SELECT name dari `users` WHERE status = 'active'.", TaskEN: sp("SELECT name dari `users` WHERE status = 'active'."),
			ExpectedOutput: j(`[{"name":"Siti"}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "name", "type": "text"}, {"name": "status", "type": "text"}], "rows": [{"id": 1, "name": "Budi", "status": "inactive"}, {"id": 2, "name": "Siti", "status": "active"}]}]}`),
		},
		{ID: challengeUUID(203), Slug: "toko-order-203", Language: "sql", Difficulty: "hard", XPReward: 60, OrderIndex: 203,
			TitleID: "Toko Kelontong Makmur: Urutkan Alphabet", TitleEN: sp("Toko Kelontong Makmur: Urutkan Alphabet"),
			StoryID: "Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nData acak-acakan. Urutkan nama secara ascending (A-Z) agar mudah dibaca.", StoryEN: sp("Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nData acak-acakan. Urutkan nama secara ascending (A-Z) agar mudah dibaca."),
			TaskID: "SELECT name dari `users` ORDER BY name ASC.", TaskEN: sp("SELECT name dari `users` ORDER BY name ASC."),
			ExpectedOutput: j(`[{"name":"Budi"},{"name":"Siti"},{"name":"Zain"}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "name", "type": "text"}], "rows": [{"id": 1, "name": "Siti"}, {"id": 2, "name": "Zain"}, {"id": 3, "name": "Budi"}]}]}`),
		},
		{ID: challengeUUID(204), Slug: "toko-limit-204", Language: "sql", Difficulty: "medium", XPReward: 30, OrderIndex: 204,
			TitleID: "Toko Kelontong Makmur: Ambil Top 2", TitleEN: sp("Toko Kelontong Makmur: Ambil Top 2"),
			StoryID: "Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nLayar kita terbatas, hanya muat 2 data. Jangan lupa urutkan by ID DESC lalu LIMIT 2.", StoryEN: sp("Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nLayar kita terbatas, hanya muat 2 data. Jangan lupa urutkan by ID DESC lalu LIMIT 2."),
			TaskID: "SELECT id dari `users` ORDER BY id DESC LIMIT 2.", TaskEN: sp("SELECT id dari `users` ORDER BY id DESC LIMIT 2."),
			ExpectedOutput: j(`[{"id":5},{"id":4}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}], "rows": [{"id": 1}, {"id": 2}, {"id": 3}, {"id": 4}, {"id": 5}]}]}`),
		},
		{ID: challengeUUID(205), Slug: "toko-count-205", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 205,
			TitleID: "Toko Kelontong Makmur: Hitung Jumlah Keseluruhan", TitleEN: sp("Toko Kelontong Makmur: Hitung Jumlah Keseluruhan"),
			StoryID: "Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nBerapa banyak data yang kita miliki saat ini? Tolong hitung totalnya.", StoryEN: sp("Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nBerapa banyak data yang kita miliki saat ini? Tolong hitung totalnya."),
			TaskID: "SELECT COUNT(*) as total dari `users`.", TaskEN: sp("SELECT COUNT(*) as total dari `users`."),
			ExpectedOutput: j(`[{"total":3}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}], "rows": [{"id": 1}, {"id": 2}, {"id": 3}]}]}`),
		},
		{ID: challengeUUID(206), Slug: "toko-sum-206", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 206,
			TitleID: "Toko Kelontong Makmur: Total Saldo", TitleEN: sp("Toko Kelontong Makmur: Total Saldo"),
			StoryID: "Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nHitung jumlah keseluruhan `saldo` dari semua pengguna yang terdaftar.", StoryEN: sp("Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nHitung jumlah keseluruhan `saldo` dari semua pengguna yang terdaftar."),
			TaskID: "SELECT SUM(saldo) as totalsaldo dari `users`.", TaskEN: sp("SELECT SUM(saldo) as totalsaldo dari `users`."),
			ExpectedOutput: j(`[{"totalsaldo":15000}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "saldo", "type": "int"}], "rows": [{"id": 1, "saldo": 5000}, {"id": 2, "saldo": 10000}]}]}`),
		},
		{ID: challengeUUID(207), Slug: "toko-groupby-207", Language: "sql", Difficulty: "medium", XPReward: 30, OrderIndex: 207,
			TitleID: "Toko Kelontong Makmur: Rekap Grup Kota", TitleEN: sp("Toko Kelontong Makmur: Rekap Grup Kota"),
			StoryID: "Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nManajer butuh laporan berapa jumlah warga di tiap kota.", StoryEN: sp("Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nManajer butuh laporan berapa jumlah warga di tiap kota."),
			TaskID: "SELECT kota, COUNT(*) as jml dari `users` GROUP BY kota ORDER BY kota.", TaskEN: sp("SELECT kota, COUNT(*) as jml dari `users` GROUP BY kota ORDER BY kota."),
			ExpectedOutput: j(`[{"kota":"Bandung","jml":1},{"kota":"Jakarta","jml":2}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "kota", "type": "text"}], "rows": [{"id": 1, "kota": "Jakarta"}, {"id": 2, "kota": "Bandung"}, {"id": 3, "kota": "Jakarta"}]}]}`),
		},
		{ID: challengeUUID(208), Slug: "toko-having-208", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 208,
			TitleID: "Toko Kelontong Makmur: Saring Hasil Grup", TitleEN: sp("Toko Kelontong Makmur: Saring Hasil Grup"),
			StoryID: "Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nSama seperti grup kota sebelumnya, tapi hanya tampilkan kota yang penduduknya > 1.", StoryEN: sp("Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nSama seperti grup kota sebelumnya, tapi hanya tampilkan kota yang penduduknya > 1."),
			TaskID: "SELECT kota, COUNT(*) as jml dari `users` GROUP BY kota HAVING COUNT(*) > 1.", TaskEN: sp("SELECT kota, COUNT(*) as jml dari `users` GROUP BY kota HAVING COUNT(*) > 1."),
			ExpectedOutput: j(`[{"kota":"Jakarta","jml":2}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "kota", "type": "text"}], "rows": [{"id": 1, "kota": "Jakarta"}, {"id": 2, "kota": "Bandung"}, {"id": 3, "kota": "Jakarta"}]}]}`),
		},
		{ID: challengeUUID(209), Slug: "toko-join-209", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 209,
			TitleID: "Toko Kelontong Makmur: Gabungan Data Lintas Divisi", TitleEN: sp("Toko Kelontong Makmur: Gabungan Data Lintas Divisi"),
			StoryID: "Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nTabel `users` dan `roles` terpisah. Gabungkan INNER JOIN agar tahu role si user.", StoryEN: sp("Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nTabel `users` dan `roles` terpisah. Gabungkan INNER JOIN agar tahu role si user."),
			TaskID: "SELECT u.name, r.role_name FROM users u JOIN roles r ON u.role_id = r.id ORDER BY u.name.", TaskEN: sp("SELECT u.name, r.role_name FROM users u JOIN roles r ON u.role_id = r.id ORDER BY u.name."),
			ExpectedOutput: j(`[{"name":"Budi","role_name":"Admin"},{"name":"Siti","role_name":"User"}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "name", "type": "text"}, {"name": "role_id", "type": "int"}], "rows": [{"name": "Budi", "role_id": 1}, {"name": "Siti", "role_id": 2}]}, {"name": "roles", "columns": [{"name": "id", "type": "int"}, {"name": "role_name", "type": "text"}], "rows": [{"id": 1, "role_name": "Admin"}, {"id": 2, "role_name": "User"}]}]}`),
		},
		{ID: challengeUUID(210), Slug: "toko-subquery-210", Language: "sql", Difficulty: "hard", XPReward: 60, OrderIndex: 210,
			TitleID: "Toko Kelontong Makmur: Cari Pejabat Tertinggi", TitleEN: sp("Toko Kelontong Makmur: Cari Pejabat Tertinggi"),
			StoryID: "Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nCari siapa pegawai dengan gaji di atas rata-rata.", StoryEN: sp("Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nCari siapa pegawai dengan gaji di atas rata-rata."),
			TaskID: "SELECT name FROM users WHERE gaji > (SELECT AVG(gaji) FROM users).", TaskEN: sp("SELECT name FROM users WHERE gaji > (SELECT AVG(gaji) FROM users)."),
			ExpectedOutput: j(`[{"name":"Budi"}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "name", "type": "text"}, {"name": "gaji", "type": "int"}], "rows": [{"name": "Budi", "gaji": 20000}, {"name": "Siti", "gaji": 5000}, {"name": "Zain", "gaji": 10000}]}]}`),
		},
		{ID: challengeUUID(211), Slug: "rs-select-211", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 211,
			TitleID: "Rumah Sakit Sehat Sejahtera: Data Master", TitleEN: sp("Rumah Sakit Sehat Sejahtera: Data Master"),
			StoryID: "Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nTampilkan seluruh data pada tabel master `users`. Tolong jangan filter apapun dulu.", StoryEN: sp("Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nTampilkan seluruh data pada tabel master `users`. Tolong jangan filter apapun dulu."),
			TaskID: "SELECT seluruh kolom dari tabel `users`.", TaskEN: sp("SELECT seluruh kolom dari tabel `users`."),
			ExpectedOutput: j(`[{"id":1,"name":"Budi"},{"id":2,"name":"Siti"}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "name", "type": "text"}], "rows": [{"id": 1, "name": "Budi"}, {"id": 2, "name": "Siti"}]}]}`),
		},
		{ID: challengeUUID(212), Slug: "rs-where-212", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 212,
			TitleID: "Rumah Sakit Sehat Sejahtera: Pencarian Aktif", TitleEN: sp("Rumah Sakit Sehat Sejahtera: Pencarian Aktif"),
			StoryID: "Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nHanya tampilkan record yang statusnya 'active' di tabel `users` untuk dihubungi hari ini.", StoryEN: sp("Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nHanya tampilkan record yang statusnya 'active' di tabel `users` untuk dihubungi hari ini."),
			TaskID: "SELECT name dari `users` WHERE status = 'active'.", TaskEN: sp("SELECT name dari `users` WHERE status = 'active'."),
			ExpectedOutput: j(`[{"name":"Siti"}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "name", "type": "text"}, {"name": "status", "type": "text"}], "rows": [{"id": 1, "name": "Budi", "status": "inactive"}, {"id": 2, "name": "Siti", "status": "active"}]}]}`),
		},
		{ID: challengeUUID(213), Slug: "rs-order-213", Language: "sql", Difficulty: "medium", XPReward: 30, OrderIndex: 213,
			TitleID: "Rumah Sakit Sehat Sejahtera: Urutkan Alphabet", TitleEN: sp("Rumah Sakit Sehat Sejahtera: Urutkan Alphabet"),
			StoryID: "Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nData acak-acakan. Urutkan nama secara ascending (A-Z) agar mudah dibaca.", StoryEN: sp("Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nData acak-acakan. Urutkan nama secara ascending (A-Z) agar mudah dibaca."),
			TaskID: "SELECT name dari `users` ORDER BY name ASC.", TaskEN: sp("SELECT name dari `users` ORDER BY name ASC."),
			ExpectedOutput: j(`[{"name":"Budi"},{"name":"Siti"},{"name":"Zain"}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "name", "type": "text"}], "rows": [{"id": 1, "name": "Siti"}, {"id": 2, "name": "Zain"}, {"id": 3, "name": "Budi"}]}]}`),
		},
		{ID: challengeUUID(214), Slug: "rs-limit-214", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 214,
			TitleID: "Rumah Sakit Sehat Sejahtera: Ambil Top 2", TitleEN: sp("Rumah Sakit Sehat Sejahtera: Ambil Top 2"),
			StoryID: "Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nLayar kita terbatas, hanya muat 2 data. Jangan lupa urutkan by ID DESC lalu LIMIT 2.", StoryEN: sp("Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nLayar kita terbatas, hanya muat 2 data. Jangan lupa urutkan by ID DESC lalu LIMIT 2."),
			TaskID: "SELECT id dari `users` ORDER BY id DESC LIMIT 2.", TaskEN: sp("SELECT id dari `users` ORDER BY id DESC LIMIT 2."),
			ExpectedOutput: j(`[{"id":5},{"id":4}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}], "rows": [{"id": 1}, {"id": 2}, {"id": 3}, {"id": 4}, {"id": 5}]}]}`),
		},
		{ID: challengeUUID(215), Slug: "rs-count-215", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 215,
			TitleID: "Rumah Sakit Sehat Sejahtera: Hitung Jumlah Keseluruhan", TitleEN: sp("Rumah Sakit Sehat Sejahtera: Hitung Jumlah Keseluruhan"),
			StoryID: "Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nBerapa banyak data yang kita miliki saat ini? Tolong hitung totalnya.", StoryEN: sp("Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nBerapa banyak data yang kita miliki saat ini? Tolong hitung totalnya."),
			TaskID: "SELECT COUNT(*) as total dari `users`.", TaskEN: sp("SELECT COUNT(*) as total dari `users`."),
			ExpectedOutput: j(`[{"total":3}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}], "rows": [{"id": 1}, {"id": 2}, {"id": 3}]}]}`),
		},
		{ID: challengeUUID(216), Slug: "rs-sum-216", Language: "sql", Difficulty: "medium", XPReward: 30, OrderIndex: 216,
			TitleID: "Rumah Sakit Sehat Sejahtera: Total Saldo", TitleEN: sp("Rumah Sakit Sehat Sejahtera: Total Saldo"),
			StoryID: "Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nHitung jumlah keseluruhan `saldo` dari semua pengguna yang terdaftar.", StoryEN: sp("Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nHitung jumlah keseluruhan `saldo` dari semua pengguna yang terdaftar."),
			TaskID: "SELECT SUM(saldo) as totalsaldo dari `users`.", TaskEN: sp("SELECT SUM(saldo) as totalsaldo dari `users`."),
			ExpectedOutput: j(`[{"totalsaldo":15000}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "saldo", "type": "int"}], "rows": [{"id": 1, "saldo": 5000}, {"id": 2, "saldo": 10000}]}]}`),
		},
		{ID: challengeUUID(217), Slug: "rs-groupby-217", Language: "sql", Difficulty: "hard", XPReward: 60, OrderIndex: 217,
			TitleID: "Rumah Sakit Sehat Sejahtera: Rekap Grup Kota", TitleEN: sp("Rumah Sakit Sehat Sejahtera: Rekap Grup Kota"),
			StoryID: "Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nManajer butuh laporan berapa jumlah warga di tiap kota.", StoryEN: sp("Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nManajer butuh laporan berapa jumlah warga di tiap kota."),
			TaskID: "SELECT kota, COUNT(*) as jml dari `users` GROUP BY kota ORDER BY kota.", TaskEN: sp("SELECT kota, COUNT(*) as jml dari `users` GROUP BY kota ORDER BY kota."),
			ExpectedOutput: j(`[{"kota":"Bandung","jml":1},{"kota":"Jakarta","jml":2}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "kota", "type": "text"}], "rows": [{"id": 1, "kota": "Jakarta"}, {"id": 2, "kota": "Bandung"}, {"id": 3, "kota": "Jakarta"}]}]}`),
		},
		{ID: challengeUUID(218), Slug: "rs-having-218", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 218,
			TitleID: "Rumah Sakit Sehat Sejahtera: Saring Hasil Grup", TitleEN: sp("Rumah Sakit Sehat Sejahtera: Saring Hasil Grup"),
			StoryID: "Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nSama seperti grup kota sebelumnya, tapi hanya tampilkan kota yang penduduknya > 1.", StoryEN: sp("Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nSama seperti grup kota sebelumnya, tapi hanya tampilkan kota yang penduduknya > 1."),
			TaskID: "SELECT kota, COUNT(*) as jml dari `users` GROUP BY kota HAVING COUNT(*) > 1.", TaskEN: sp("SELECT kota, COUNT(*) as jml dari `users` GROUP BY kota HAVING COUNT(*) > 1."),
			ExpectedOutput: j(`[{"kota":"Jakarta","jml":2}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "kota", "type": "text"}], "rows": [{"id": 1, "kota": "Jakarta"}, {"id": 2, "kota": "Bandung"}, {"id": 3, "kota": "Jakarta"}]}]}`),
		},
		{ID: challengeUUID(219), Slug: "rs-join-219", Language: "sql", Difficulty: "medium", XPReward: 30, OrderIndex: 219,
			TitleID: "Rumah Sakit Sehat Sejahtera: Gabungan Data Lintas Divisi", TitleEN: sp("Rumah Sakit Sehat Sejahtera: Gabungan Data Lintas Divisi"),
			StoryID: "Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nTabel `users` dan `roles` terpisah. Gabungkan INNER JOIN agar tahu role si user.", StoryEN: sp("Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nTabel `users` dan `roles` terpisah. Gabungkan INNER JOIN agar tahu role si user."),
			TaskID: "SELECT u.name, r.role_name FROM users u JOIN roles r ON u.role_id = r.id ORDER BY u.name.", TaskEN: sp("SELECT u.name, r.role_name FROM users u JOIN roles r ON u.role_id = r.id ORDER BY u.name."),
			ExpectedOutput: j(`[{"name":"Budi","role_name":"Admin"},{"name":"Siti","role_name":"User"}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "name", "type": "text"}, {"name": "role_id", "type": "int"}], "rows": [{"name": "Budi", "role_id": 1}, {"name": "Siti", "role_id": 2}]}, {"name": "roles", "columns": [{"name": "id", "type": "int"}, {"name": "role_name", "type": "text"}], "rows": [{"id": 1, "role_name": "Admin"}, {"id": 2, "role_name": "User"}]}]}`),
		},
		{ID: challengeUUID(220), Slug: "rs-subquery-220", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 220,
			TitleID: "Rumah Sakit Sehat Sejahtera: Cari Pejabat Tertinggi", TitleEN: sp("Rumah Sakit Sehat Sejahtera: Cari Pejabat Tertinggi"),
			StoryID: "Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nCari siapa pegawai dengan gaji di atas rata-rata.", StoryEN: sp("Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nCari siapa pegawai dengan gaji di atas rata-rata."),
			TaskID: "SELECT name FROM users WHERE gaji > (SELECT AVG(gaji) FROM users).", TaskEN: sp("SELECT name FROM users WHERE gaji > (SELECT AVG(gaji) FROM users)."),
			ExpectedOutput: j(`[{"name":"Budi"}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "name", "type": "text"}, {"name": "gaji", "type": "int"}], "rows": [{"name": "Budi", "gaji": 20000}, {"name": "Siti", "gaji": 5000}, {"name": "Zain", "gaji": 10000}]}]}`),
		},
		{ID: challengeUUID(221), Slug: "sekolah-select-221", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 221,
			TitleID: "SMA Harapan Bangsa: Data Master", TitleEN: sp("SMA Harapan Bangsa: Data Master"),
			StoryID: "Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nTampilkan seluruh data pada tabel master `users`. Tolong jangan filter apapun dulu.", StoryEN: sp("Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nTampilkan seluruh data pada tabel master `users`. Tolong jangan filter apapun dulu."),
			TaskID: "SELECT seluruh kolom dari tabel `users`.", TaskEN: sp("SELECT seluruh kolom dari tabel `users`."),
			ExpectedOutput: j(`[{"id":1,"name":"Budi"},{"id":2,"name":"Siti"}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "name", "type": "text"}], "rows": [{"id": 1, "name": "Budi"}, {"id": 2, "name": "Siti"}]}]}`),
		},
		{ID: challengeUUID(222), Slug: "sekolah-where-222", Language: "sql", Difficulty: "medium", XPReward: 30, OrderIndex: 222,
			TitleID: "SMA Harapan Bangsa: Pencarian Aktif", TitleEN: sp("SMA Harapan Bangsa: Pencarian Aktif"),
			StoryID: "Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nHanya tampilkan record yang statusnya 'active' di tabel `users` untuk dihubungi hari ini.", StoryEN: sp("Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nHanya tampilkan record yang statusnya 'active' di tabel `users` untuk dihubungi hari ini."),
			TaskID: "SELECT name dari `users` WHERE status = 'active'.", TaskEN: sp("SELECT name dari `users` WHERE status = 'active'."),
			ExpectedOutput: j(`[{"name":"Siti"}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "name", "type": "text"}, {"name": "status", "type": "text"}], "rows": [{"id": 1, "name": "Budi", "status": "inactive"}, {"id": 2, "name": "Siti", "status": "active"}]}]}`),
		},
		{ID: challengeUUID(223), Slug: "sekolah-order-223", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 223,
			TitleID: "SMA Harapan Bangsa: Urutkan Alphabet", TitleEN: sp("SMA Harapan Bangsa: Urutkan Alphabet"),
			StoryID: "Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nData acak-acakan. Urutkan nama secara ascending (A-Z) agar mudah dibaca.", StoryEN: sp("Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nData acak-acakan. Urutkan nama secara ascending (A-Z) agar mudah dibaca."),
			TaskID: "SELECT name dari `users` ORDER BY name ASC.", TaskEN: sp("SELECT name dari `users` ORDER BY name ASC."),
			ExpectedOutput: j(`[{"name":"Budi"},{"name":"Siti"},{"name":"Zain"}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "name", "type": "text"}], "rows": [{"id": 1, "name": "Siti"}, {"id": 2, "name": "Zain"}, {"id": 3, "name": "Budi"}]}]}`),
		},
		{ID: challengeUUID(224), Slug: "sekolah-limit-224", Language: "sql", Difficulty: "hard", XPReward: 60, OrderIndex: 224,
			TitleID: "SMA Harapan Bangsa: Ambil Top 2", TitleEN: sp("SMA Harapan Bangsa: Ambil Top 2"),
			StoryID: "Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nLayar kita terbatas, hanya muat 2 data. Jangan lupa urutkan by ID DESC lalu LIMIT 2.", StoryEN: sp("Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nLayar kita terbatas, hanya muat 2 data. Jangan lupa urutkan by ID DESC lalu LIMIT 2."),
			TaskID: "SELECT id dari `users` ORDER BY id DESC LIMIT 2.", TaskEN: sp("SELECT id dari `users` ORDER BY id DESC LIMIT 2."),
			ExpectedOutput: j(`[{"id":5},{"id":4}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}], "rows": [{"id": 1}, {"id": 2}, {"id": 3}, {"id": 4}, {"id": 5}]}]}`),
		},
		{ID: challengeUUID(225), Slug: "sekolah-count-225", Language: "sql", Difficulty: "medium", XPReward: 30, OrderIndex: 225,
			TitleID: "SMA Harapan Bangsa: Hitung Jumlah Keseluruhan", TitleEN: sp("SMA Harapan Bangsa: Hitung Jumlah Keseluruhan"),
			StoryID: "Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nBerapa banyak data yang kita miliki saat ini? Tolong hitung totalnya.", StoryEN: sp("Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nBerapa banyak data yang kita miliki saat ini? Tolong hitung totalnya."),
			TaskID: "SELECT COUNT(*) as total dari `users`.", TaskEN: sp("SELECT COUNT(*) as total dari `users`."),
			ExpectedOutput: j(`[{"total":3}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}], "rows": [{"id": 1}, {"id": 2}, {"id": 3}]}]}`),
		},
		{ID: challengeUUID(226), Slug: "sekolah-sum-226", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 226,
			TitleID: "SMA Harapan Bangsa: Total Saldo", TitleEN: sp("SMA Harapan Bangsa: Total Saldo"),
			StoryID: "Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nHitung jumlah keseluruhan `saldo` dari semua pengguna yang terdaftar.", StoryEN: sp("Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nHitung jumlah keseluruhan `saldo` dari semua pengguna yang terdaftar."),
			TaskID: "SELECT SUM(saldo) as totalsaldo dari `users`.", TaskEN: sp("SELECT SUM(saldo) as totalsaldo dari `users`."),
			ExpectedOutput: j(`[{"totalsaldo":15000}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "saldo", "type": "int"}], "rows": [{"id": 1, "saldo": 5000}, {"id": 2, "saldo": 10000}]}]}`),
		},
		{ID: challengeUUID(227), Slug: "sekolah-groupby-227", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 227,
			TitleID: "SMA Harapan Bangsa: Rekap Grup Kota", TitleEN: sp("SMA Harapan Bangsa: Rekap Grup Kota"),
			StoryID: "Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nManajer butuh laporan berapa jumlah warga di tiap kota.", StoryEN: sp("Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nManajer butuh laporan berapa jumlah warga di tiap kota."),
			TaskID: "SELECT kota, COUNT(*) as jml dari `users` GROUP BY kota ORDER BY kota.", TaskEN: sp("SELECT kota, COUNT(*) as jml dari `users` GROUP BY kota ORDER BY kota."),
			ExpectedOutput: j(`[{"kota":"Bandung","jml":1},{"kota":"Jakarta","jml":2}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "kota", "type": "text"}], "rows": [{"id": 1, "kota": "Jakarta"}, {"id": 2, "kota": "Bandung"}, {"id": 3, "kota": "Jakarta"}]}]}`),
		},
		{ID: challengeUUID(228), Slug: "sekolah-having-228", Language: "sql", Difficulty: "medium", XPReward: 30, OrderIndex: 228,
			TitleID: "SMA Harapan Bangsa: Saring Hasil Grup", TitleEN: sp("SMA Harapan Bangsa: Saring Hasil Grup"),
			StoryID: "Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nSama seperti grup kota sebelumnya, tapi hanya tampilkan kota yang penduduknya > 1.", StoryEN: sp("Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nSama seperti grup kota sebelumnya, tapi hanya tampilkan kota yang penduduknya > 1."),
			TaskID: "SELECT kota, COUNT(*) as jml dari `users` GROUP BY kota HAVING COUNT(*) > 1.", TaskEN: sp("SELECT kota, COUNT(*) as jml dari `users` GROUP BY kota HAVING COUNT(*) > 1."),
			ExpectedOutput: j(`[{"kota":"Jakarta","jml":2}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "kota", "type": "text"}], "rows": [{"id": 1, "kota": "Jakarta"}, {"id": 2, "kota": "Bandung"}, {"id": 3, "kota": "Jakarta"}]}]}`),
		},
		{ID: challengeUUID(229), Slug: "sekolah-join-229", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 229,
			TitleID: "SMA Harapan Bangsa: Gabungan Data Lintas Divisi", TitleEN: sp("SMA Harapan Bangsa: Gabungan Data Lintas Divisi"),
			StoryID: "Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nTabel `users` dan `roles` terpisah. Gabungkan INNER JOIN agar tahu role si user.", StoryEN: sp("Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nTabel `users` dan `roles` terpisah. Gabungkan INNER JOIN agar tahu role si user."),
			TaskID: "SELECT u.name, r.role_name FROM users u JOIN roles r ON u.role_id = r.id ORDER BY u.name.", TaskEN: sp("SELECT u.name, r.role_name FROM users u JOIN roles r ON u.role_id = r.id ORDER BY u.name."),
			ExpectedOutput: j(`[{"name":"Budi","role_name":"Admin"},{"name":"Siti","role_name":"User"}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "name", "type": "text"}, {"name": "role_id", "type": "int"}], "rows": [{"name": "Budi", "role_id": 1}, {"name": "Siti", "role_id": 2}]}, {"name": "roles", "columns": [{"name": "id", "type": "int"}, {"name": "role_name", "type": "text"}], "rows": [{"id": 1, "role_name": "Admin"}, {"id": 2, "role_name": "User"}]}]}`),
		},
		{ID: challengeUUID(230), Slug: "sekolah-subquery-230", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 230,
			TitleID: "SMA Harapan Bangsa: Cari Pejabat Tertinggi", TitleEN: sp("SMA Harapan Bangsa: Cari Pejabat Tertinggi"),
			StoryID: "Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nCari siapa pegawai dengan gaji di atas rata-rata.", StoryEN: sp("Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nCari siapa pegawai dengan gaji di atas rata-rata."),
			TaskID: "SELECT name FROM users WHERE gaji > (SELECT AVG(gaji) FROM users).", TaskEN: sp("SELECT name FROM users WHERE gaji > (SELECT AVG(gaji) FROM users)."),
			ExpectedOutput: j(`[{"name":"Budi"}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "name", "type": "text"}, {"name": "gaji", "type": "int"}], "rows": [{"name": "Budi", "gaji": 20000}, {"name": "Siti", "gaji": 5000}, {"name": "Zain", "gaji": 10000}]}]}`),
		},
		{ID: challengeUUID(231), Slug: "pabrik-select-231", Language: "sql", Difficulty: "hard", XPReward: 60, OrderIndex: 231,
			TitleID: "Pabrik Sepatu Super: Data Master", TitleEN: sp("Pabrik Sepatu Super: Data Master"),
			StoryID: "Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nTampilkan seluruh data pada tabel master `users`. Tolong jangan filter apapun dulu.", StoryEN: sp("Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nTampilkan seluruh data pada tabel master `users`. Tolong jangan filter apapun dulu."),
			TaskID: "SELECT seluruh kolom dari tabel `users`.", TaskEN: sp("SELECT seluruh kolom dari tabel `users`."),
			ExpectedOutput: j(`[{"id":1,"name":"Budi"},{"id":2,"name":"Siti"}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "name", "type": "text"}], "rows": [{"id": 1, "name": "Budi"}, {"id": 2, "name": "Siti"}]}]}`),
		},
		{ID: challengeUUID(232), Slug: "pabrik-where-232", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 232,
			TitleID: "Pabrik Sepatu Super: Pencarian Aktif", TitleEN: sp("Pabrik Sepatu Super: Pencarian Aktif"),
			StoryID: "Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nHanya tampilkan record yang statusnya 'active' di tabel `users` untuk dihubungi hari ini.", StoryEN: sp("Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nHanya tampilkan record yang statusnya 'active' di tabel `users` untuk dihubungi hari ini."),
			TaskID: "SELECT name dari `users` WHERE status = 'active'.", TaskEN: sp("SELECT name dari `users` WHERE status = 'active'."),
			ExpectedOutput: j(`[{"name":"Siti"}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "name", "type": "text"}, {"name": "status", "type": "text"}], "rows": [{"id": 1, "name": "Budi", "status": "inactive"}, {"id": 2, "name": "Siti", "status": "active"}]}]}`),
		},
		{ID: challengeUUID(233), Slug: "pabrik-order-233", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 233,
			TitleID: "Pabrik Sepatu Super: Urutkan Alphabet", TitleEN: sp("Pabrik Sepatu Super: Urutkan Alphabet"),
			StoryID: "Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nData acak-acakan. Urutkan nama secara ascending (A-Z) agar mudah dibaca.", StoryEN: sp("Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nData acak-acakan. Urutkan nama secara ascending (A-Z) agar mudah dibaca."),
			TaskID: "SELECT name dari `users` ORDER BY name ASC.", TaskEN: sp("SELECT name dari `users` ORDER BY name ASC."),
			ExpectedOutput: j(`[{"name":"Budi"},{"name":"Siti"},{"name":"Zain"}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "name", "type": "text"}], "rows": [{"id": 1, "name": "Siti"}, {"id": 2, "name": "Zain"}, {"id": 3, "name": "Budi"}]}]}`),
		},
		{ID: challengeUUID(234), Slug: "pabrik-limit-234", Language: "sql", Difficulty: "medium", XPReward: 30, OrderIndex: 234,
			TitleID: "Pabrik Sepatu Super: Ambil Top 2", TitleEN: sp("Pabrik Sepatu Super: Ambil Top 2"),
			StoryID: "Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nLayar kita terbatas, hanya muat 2 data. Jangan lupa urutkan by ID DESC lalu LIMIT 2.", StoryEN: sp("Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nLayar kita terbatas, hanya muat 2 data. Jangan lupa urutkan by ID DESC lalu LIMIT 2."),
			TaskID: "SELECT id dari `users` ORDER BY id DESC LIMIT 2.", TaskEN: sp("SELECT id dari `users` ORDER BY id DESC LIMIT 2."),
			ExpectedOutput: j(`[{"id":5},{"id":4}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}], "rows": [{"id": 1}, {"id": 2}, {"id": 3}, {"id": 4}, {"id": 5}]}]}`),
		},
		{ID: challengeUUID(235), Slug: "pabrik-count-235", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 235,
			TitleID: "Pabrik Sepatu Super: Hitung Jumlah Keseluruhan", TitleEN: sp("Pabrik Sepatu Super: Hitung Jumlah Keseluruhan"),
			StoryID: "Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nBerapa banyak data yang kita miliki saat ini? Tolong hitung totalnya.", StoryEN: sp("Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nBerapa banyak data yang kita miliki saat ini? Tolong hitung totalnya."),
			TaskID: "SELECT COUNT(*) as total dari `users`.", TaskEN: sp("SELECT COUNT(*) as total dari `users`."),
			ExpectedOutput: j(`[{"total":3}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}], "rows": [{"id": 1}, {"id": 2}, {"id": 3}]}]}`),
		},
		{ID: challengeUUID(236), Slug: "pabrik-sum-236", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 236,
			TitleID: "Pabrik Sepatu Super: Total Saldo", TitleEN: sp("Pabrik Sepatu Super: Total Saldo"),
			StoryID: "Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nHitung jumlah keseluruhan `saldo` dari semua pengguna yang terdaftar.", StoryEN: sp("Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nHitung jumlah keseluruhan `saldo` dari semua pengguna yang terdaftar."),
			TaskID: "SELECT SUM(saldo) as totalsaldo dari `users`.", TaskEN: sp("SELECT SUM(saldo) as totalsaldo dari `users`."),
			ExpectedOutput: j(`[{"totalsaldo":15000}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "saldo", "type": "int"}], "rows": [{"id": 1, "saldo": 5000}, {"id": 2, "saldo": 10000}]}]}`),
		},
		{ID: challengeUUID(237), Slug: "pabrik-groupby-237", Language: "sql", Difficulty: "medium", XPReward: 30, OrderIndex: 237,
			TitleID: "Pabrik Sepatu Super: Rekap Grup Kota", TitleEN: sp("Pabrik Sepatu Super: Rekap Grup Kota"),
			StoryID: "Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nManajer butuh laporan berapa jumlah warga di tiap kota.", StoryEN: sp("Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nManajer butuh laporan berapa jumlah warga di tiap kota."),
			TaskID: "SELECT kota, COUNT(*) as jml dari `users` GROUP BY kota ORDER BY kota.", TaskEN: sp("SELECT kota, COUNT(*) as jml dari `users` GROUP BY kota ORDER BY kota."),
			ExpectedOutput: j(`[{"kota":"Bandung","jml":1},{"kota":"Jakarta","jml":2}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "kota", "type": "text"}], "rows": [{"id": 1, "kota": "Jakarta"}, {"id": 2, "kota": "Bandung"}, {"id": 3, "kota": "Jakarta"}]}]}`),
		},
		{ID: challengeUUID(238), Slug: "pabrik-having-238", Language: "sql", Difficulty: "hard", XPReward: 60, OrderIndex: 238,
			TitleID: "Pabrik Sepatu Super: Saring Hasil Grup", TitleEN: sp("Pabrik Sepatu Super: Saring Hasil Grup"),
			StoryID: "Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nSama seperti grup kota sebelumnya, tapi hanya tampilkan kota yang penduduknya > 1.", StoryEN: sp("Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nSama seperti grup kota sebelumnya, tapi hanya tampilkan kota yang penduduknya > 1."),
			TaskID: "SELECT kota, COUNT(*) as jml dari `users` GROUP BY kota HAVING COUNT(*) > 1.", TaskEN: sp("SELECT kota, COUNT(*) as jml dari `users` GROUP BY kota HAVING COUNT(*) > 1."),
			ExpectedOutput: j(`[{"kota":"Jakarta","jml":2}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "kota", "type": "text"}], "rows": [{"id": 1, "kota": "Jakarta"}, {"id": 2, "kota": "Bandung"}, {"id": 3, "kota": "Jakarta"}]}]}`),
		},
		{ID: challengeUUID(239), Slug: "pabrik-join-239", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 239,
			TitleID: "Pabrik Sepatu Super: Gabungan Data Lintas Divisi", TitleEN: sp("Pabrik Sepatu Super: Gabungan Data Lintas Divisi"),
			StoryID: "Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nTabel `users` dan `roles` terpisah. Gabungkan INNER JOIN agar tahu role si user.", StoryEN: sp("Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nTabel `users` dan `roles` terpisah. Gabungkan INNER JOIN agar tahu role si user."),
			TaskID: "SELECT u.name, r.role_name FROM users u JOIN roles r ON u.role_id = r.id ORDER BY u.name.", TaskEN: sp("SELECT u.name, r.role_name FROM users u JOIN roles r ON u.role_id = r.id ORDER BY u.name."),
			ExpectedOutput: j(`[{"name":"Budi","role_name":"Admin"},{"name":"Siti","role_name":"User"}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "name", "type": "text"}, {"name": "role_id", "type": "int"}], "rows": [{"name": "Budi", "role_id": 1}, {"name": "Siti", "role_id": 2}]}, {"name": "roles", "columns": [{"name": "id", "type": "int"}, {"name": "role_name", "type": "text"}], "rows": [{"id": 1, "role_name": "Admin"}, {"id": 2, "role_name": "User"}]}]}`),
		},
		{ID: challengeUUID(240), Slug: "pabrik-subquery-240", Language: "sql", Difficulty: "medium", XPReward: 30, OrderIndex: 240,
			TitleID: "Pabrik Sepatu Super: Cari Pejabat Tertinggi", TitleEN: sp("Pabrik Sepatu Super: Cari Pejabat Tertinggi"),
			StoryID: "Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nCari siapa pegawai dengan gaji di atas rata-rata.", StoryEN: sp("Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nCari siapa pegawai dengan gaji di atas rata-rata."),
			TaskID: "SELECT name FROM users WHERE gaji > (SELECT AVG(gaji) FROM users).", TaskEN: sp("SELECT name FROM users WHERE gaji > (SELECT AVG(gaji) FROM users)."),
			ExpectedOutput: j(`[{"name":"Budi"}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "name", "type": "text"}, {"name": "gaji", "type": "int"}], "rows": [{"name": "Budi", "gaji": 20000}, {"name": "Siti", "gaji": 5000}, {"name": "Zain", "gaji": 10000}]}]}`),
		},
		{ID: challengeUUID(241), Slug: "kargo-select-241", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 241,
			TitleID: "Ekspedisi Kilat: Data Master", TitleEN: sp("Ekspedisi Kilat: Data Master"),
			StoryID: "Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nTampilkan seluruh data pada tabel master `users`. Tolong jangan filter apapun dulu.", StoryEN: sp("Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nTampilkan seluruh data pada tabel master `users`. Tolong jangan filter apapun dulu."),
			TaskID: "SELECT seluruh kolom dari tabel `users`.", TaskEN: sp("SELECT seluruh kolom dari tabel `users`."),
			ExpectedOutput: j(`[{"id":1,"name":"Budi"},{"id":2,"name":"Siti"}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "name", "type": "text"}], "rows": [{"id": 1, "name": "Budi"}, {"id": 2, "name": "Siti"}]}]}`),
		},
		{ID: challengeUUID(242), Slug: "kargo-where-242", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 242,
			TitleID: "Ekspedisi Kilat: Pencarian Aktif", TitleEN: sp("Ekspedisi Kilat: Pencarian Aktif"),
			StoryID: "Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nHanya tampilkan record yang statusnya 'active' di tabel `users` untuk dihubungi hari ini.", StoryEN: sp("Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nHanya tampilkan record yang statusnya 'active' di tabel `users` untuk dihubungi hari ini."),
			TaskID: "SELECT name dari `users` WHERE status = 'active'.", TaskEN: sp("SELECT name dari `users` WHERE status = 'active'."),
			ExpectedOutput: j(`[{"name":"Siti"}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "name", "type": "text"}, {"name": "status", "type": "text"}], "rows": [{"id": 1, "name": "Budi", "status": "inactive"}, {"id": 2, "name": "Siti", "status": "active"}]}]}`),
		},
		{ID: challengeUUID(243), Slug: "kargo-order-243", Language: "sql", Difficulty: "medium", XPReward: 30, OrderIndex: 243,
			TitleID: "Ekspedisi Kilat: Urutkan Alphabet", TitleEN: sp("Ekspedisi Kilat: Urutkan Alphabet"),
			StoryID: "Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nData acak-acakan. Urutkan nama secara ascending (A-Z) agar mudah dibaca.", StoryEN: sp("Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nData acak-acakan. Urutkan nama secara ascending (A-Z) agar mudah dibaca."),
			TaskID: "SELECT name dari `users` ORDER BY name ASC.", TaskEN: sp("SELECT name dari `users` ORDER BY name ASC."),
			ExpectedOutput: j(`[{"name":"Budi"},{"name":"Siti"},{"name":"Zain"}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "name", "type": "text"}], "rows": [{"id": 1, "name": "Siti"}, {"id": 2, "name": "Zain"}, {"id": 3, "name": "Budi"}]}]}`),
		},
		{ID: challengeUUID(244), Slug: "kargo-limit-244", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 244,
			TitleID: "Ekspedisi Kilat: Ambil Top 2", TitleEN: sp("Ekspedisi Kilat: Ambil Top 2"),
			StoryID: "Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nLayar kita terbatas, hanya muat 2 data. Jangan lupa urutkan by ID DESC lalu LIMIT 2.", StoryEN: sp("Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nLayar kita terbatas, hanya muat 2 data. Jangan lupa urutkan by ID DESC lalu LIMIT 2."),
			TaskID: "SELECT id dari `users` ORDER BY id DESC LIMIT 2.", TaskEN: sp("SELECT id dari `users` ORDER BY id DESC LIMIT 2."),
			ExpectedOutput: j(`[{"id":5},{"id":4}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}], "rows": [{"id": 1}, {"id": 2}, {"id": 3}, {"id": 4}, {"id": 5}]}]}`),
		},
		{ID: challengeUUID(245), Slug: "kargo-count-245", Language: "sql", Difficulty: "hard", XPReward: 60, OrderIndex: 245,
			TitleID: "Ekspedisi Kilat: Hitung Jumlah Keseluruhan", TitleEN: sp("Ekspedisi Kilat: Hitung Jumlah Keseluruhan"),
			StoryID: "Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nBerapa banyak data yang kita miliki saat ini? Tolong hitung totalnya.", StoryEN: sp("Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nBerapa banyak data yang kita miliki saat ini? Tolong hitung totalnya."),
			TaskID: "SELECT COUNT(*) as total dari `users`.", TaskEN: sp("SELECT COUNT(*) as total dari `users`."),
			ExpectedOutput: j(`[{"total":3}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}], "rows": [{"id": 1}, {"id": 2}, {"id": 3}]}]}`),
		},
		{ID: challengeUUID(246), Slug: "kargo-sum-246", Language: "sql", Difficulty: "medium", XPReward: 30, OrderIndex: 246,
			TitleID: "Ekspedisi Kilat: Total Saldo", TitleEN: sp("Ekspedisi Kilat: Total Saldo"),
			StoryID: "Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nHitung jumlah keseluruhan `saldo` dari semua pengguna yang terdaftar.", StoryEN: sp("Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nHitung jumlah keseluruhan `saldo` dari semua pengguna yang terdaftar."),
			TaskID: "SELECT SUM(saldo) as totalsaldo dari `users`.", TaskEN: sp("SELECT SUM(saldo) as totalsaldo dari `users`."),
			ExpectedOutput: j(`[{"totalsaldo":15000}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "saldo", "type": "int"}], "rows": [{"id": 1, "saldo": 5000}, {"id": 2, "saldo": 10000}]}]}`),
		},
		{ID: challengeUUID(247), Slug: "kargo-groupby-247", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 247,
			TitleID: "Ekspedisi Kilat: Rekap Grup Kota", TitleEN: sp("Ekspedisi Kilat: Rekap Grup Kota"),
			StoryID: "Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nManajer butuh laporan berapa jumlah warga di tiap kota.", StoryEN: sp("Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nManajer butuh laporan berapa jumlah warga di tiap kota."),
			TaskID: "SELECT kota, COUNT(*) as jml dari `users` GROUP BY kota ORDER BY kota.", TaskEN: sp("SELECT kota, COUNT(*) as jml dari `users` GROUP BY kota ORDER BY kota."),
			ExpectedOutput: j(`[{"kota":"Bandung","jml":1},{"kota":"Jakarta","jml":2}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "kota", "type": "text"}], "rows": [{"id": 1, "kota": "Jakarta"}, {"id": 2, "kota": "Bandung"}, {"id": 3, "kota": "Jakarta"}]}]}`),
		},
		{ID: challengeUUID(248), Slug: "kargo-having-248", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 248,
			TitleID: "Ekspedisi Kilat: Saring Hasil Grup", TitleEN: sp("Ekspedisi Kilat: Saring Hasil Grup"),
			StoryID: "Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nSama seperti grup kota sebelumnya, tapi hanya tampilkan kota yang penduduknya > 1.", StoryEN: sp("Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nSama seperti grup kota sebelumnya, tapi hanya tampilkan kota yang penduduknya > 1."),
			TaskID: "SELECT kota, COUNT(*) as jml dari `users` GROUP BY kota HAVING COUNT(*) > 1.", TaskEN: sp("SELECT kota, COUNT(*) as jml dari `users` GROUP BY kota HAVING COUNT(*) > 1."),
			ExpectedOutput: j(`[{"kota":"Jakarta","jml":2}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "id", "type": "int"}, {"name": "kota", "type": "text"}], "rows": [{"id": 1, "kota": "Jakarta"}, {"id": 2, "kota": "Bandung"}, {"id": 3, "kota": "Jakarta"}]}]}`),
		},
		{ID: challengeUUID(249), Slug: "kargo-join-249", Language: "sql", Difficulty: "medium", XPReward: 30, OrderIndex: 249,
			TitleID: "Ekspedisi Kilat: Gabungan Data Lintas Divisi", TitleEN: sp("Ekspedisi Kilat: Gabungan Data Lintas Divisi"),
			StoryID: "Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nTabel `users` dan `roles` terpisah. Gabungkan INNER JOIN agar tahu role si user.", StoryEN: sp("Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nTabel `users` dan `roles` terpisah. Gabungkan INNER JOIN agar tahu role si user."),
			TaskID: "SELECT u.name, r.role_name FROM users u JOIN roles r ON u.role_id = r.id ORDER BY u.name.", TaskEN: sp("SELECT u.name, r.role_name FROM users u JOIN roles r ON u.role_id = r.id ORDER BY u.name."),
			ExpectedOutput: j(`[{"name":"Budi","role_name":"Admin"},{"name":"Siti","role_name":"User"}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "name", "type": "text"}, {"name": "role_id", "type": "int"}], "rows": [{"name": "Budi", "role_id": 1}, {"name": "Siti", "role_id": 2}]}, {"name": "roles", "columns": [{"name": "id", "type": "int"}, {"name": "role_name", "type": "text"}], "rows": [{"id": 1, "role_name": "Admin"}, {"id": 2, "role_name": "User"}]}]}`),
		},
		{ID: challengeUUID(250), Slug: "kargo-subquery-250", Language: "sql", Difficulty: "easy", XPReward: 15, OrderIndex: 250,
			TitleID: "Ekspedisi Kilat: Cari Pejabat Tertinggi", TitleEN: sp("Ekspedisi Kilat: Cari Pejabat Tertinggi"),
			StoryID: "Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nCari siapa pegawai dengan gaji di atas rata-rata.", StoryEN: sp("Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nCari siapa pegawai dengan gaji di atas rata-rata."),
			TaskID: "SELECT name FROM users WHERE gaji > (SELECT AVG(gaji) FROM users).", TaskEN: sp("SELECT name FROM users WHERE gaji > (SELECT AVG(gaji) FROM users)."),
			ExpectedOutput: j(`[{"name":"Budi"}]`), SchemaInfo: j(`{"tables": [{"name": "users", "columns": [{"name": "name", "type": "text"}, {"name": "gaji", "type": "int"}], "rows": [{"name": "Budi", "gaji": 20000}, {"name": "Siti", "gaji": 5000}, {"name": "Zain", "gaji": 10000}]}]}`),
		},
	}
	for i := range challenges {
		upsert(db, &challenges[i], challenges[i].Slug)
	}
}
