package main

import (
	"github.com/arulkarim/ngodingyuk-server/internal/domain"
	"gorm.io/gorm"
)

func seedGoChallengesExp(db *gorm.DB) {
	challenges := []domain.Challenge{
		{ID: challengeUUID(101), Slug: "toko-sum-101", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 101,
			TitleID: "Toko Kelontong Makmur: Total Nominal", TitleEN: sp("Toko Kelontong Makmur: Total Nominal"),
			StoryID: "Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nTolong buatkan program untuk menghitung total semua angka di dalam list.", StoryEN: sp("Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nTolong buatkan program untuk menghitung total semua angka di dalam list."),
			TaskID: "Buat fungsi `HitungTotal(data []int) int` yang menjumlahkan semua elemen array.", TaskEN: sp("Buat fungsi `HitungTotal(data []int) int` yang menjumlahkan semua elemen array."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: buat fungsi HitungTotal\n\nfunc main() {\n    fmt.Println(HitungTotal([]int{10, 20, 30}))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc HitungTotal(data []int) int {\n    total := 0\n    for _, v := range data { total += v }\n    return total\n}\nfunc main() {\n    fmt.Println(HitungTotal([]int{10, 20, 30}))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "30\n"}]`),
			ExpectedOutput: j(`"30\n"`),
		},
		{ID: challengeUUID(102), Slug: "toko-max-102", Language: "golang", Difficulty: "medium", XPReward: 30, OrderIndex: 102,
			TitleID: "Toko Kelontong Makmur: Nilai Tertinggi", TitleEN: sp("Toko Kelontong Makmur: Nilai Tertinggi"),
			StoryID: "Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nKita butuh mengetahui angka paling besar di dalam kumpulan data untuk laporan akhir.", StoryEN: sp("Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nKita butuh mengetahui angka paling besar di dalam kumpulan data untuk laporan akhir."),
			TaskID: "Buat fungsi `CariMax(data []int) int` yang mengembalikan elemen terbesar awal. Jika kosong return 0.", TaskEN: sp("Buat fungsi `CariMax(data []int) int` yang mengembalikan elemen terbesar awal. Jika kosong return 0."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: buat fungsi CariMax\n\nfunc main() {\n    fmt.Println(CariMax([]int{15, 45, 20}))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc CariMax(data []int) int {\n    if len(data) == 0 { return 0 }\n    max := data[0]\n    for _, v := range data {\n        if v > max { max = v }\n    }\n    return max\n}\nfunc main() {\n    fmt.Println(CariMax([]int{15, 45, 20}))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "45\n"}]`),
			ExpectedOutput: j(`"45\n"`),
		},
		{ID: challengeUUID(103), Slug: "toko-filter-103", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 103,
			TitleID: "Toko Kelontong Makmur: Saring Data Lebih Dari 50", TitleEN: sp("Toko Kelontong Makmur: Saring Data Lebih Dari 50"),
			StoryID: "Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nBanyak data sampah atau nilai kecil. Saring angka yang di atas atau sama dengan 50.", StoryEN: sp("Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nBanyak data sampah atau nilai kecil. Saring angka yang di atas atau sama dengan 50."),
			TaskID: "Buat fungsi `SaringData(data []int) []int`. Cetak hasilnya (tanpa bracket format standard agar mudah). Return array baru.", TaskEN: sp("Buat fungsi `SaringData(data []int) []int`. Cetak hasilnya (tanpa bracket format standard agar mudah). Return array baru."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: buat fungsi SaringData\n\nfunc main() {\n    res := SaringData([]int{10, 50, 80, 20})\n    for _, v := range res { fmt.Println(v) }\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc SaringData(data []int) []int {\n    var res []int\n    for _, v := range data {\n        if v >= 50 { res = append(res, v) }\n    }\n    return res\n}\nfunc main() {\n    res := SaringData([]int{10, 50, 80, 20})\n    for _, v := range res { fmt.Println(v) }\n}"),
			TestCases: j(`[{"input": "", "expected_output": "50\n80\n"}]`),
			ExpectedOutput: j(`"50\n80\n"`),
		},
		{ID: challengeUUID(104), Slug: "toko-avg-104", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 104,
			TitleID: "Toko Kelontong Makmur: Rata-Rata", TitleEN: sp("Toko Kelontong Makmur: Rata-Rata"),
			StoryID: "Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nUntuk laporan statistik, tolong program perhitungan nilai rata-rata dari slice integer terlampir.", StoryEN: sp("Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nUntuk laporan statistik, tolong program perhitungan nilai rata-rata dari slice integer terlampir."),
			TaskID: "Buat fungsi `RataRata(data []int) float64`. Jika kosong, return 0.0.", TaskEN: sp("Buat fungsi `RataRata(data []int) float64`. Jika kosong, return 0.0."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: buat RataRata\n\nfunc main() {\n    fmt.Printf(\"%.1f\n\", RataRata([]int{10, 20, 30}))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc RataRata(data []int) float64 {\n    if len(data) == 0 { return 0.0 }\n    sum := 0\n    for _, v := range data { sum += v }\n    return float64(sum)/float64(len(data))\n}\nfunc main() {\n    fmt.Printf(\"%.1f\n\", RataRata([]int{10, 20, 30}))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "20.0\n"}]`),
			ExpectedOutput: j(`"20.0\n"`),
		},
		{ID: challengeUUID(105), Slug: "toko-count-105", Language: "golang", Difficulty: "hard", XPReward: 60, OrderIndex: 105,
			TitleID: "Toko Kelontong Makmur: Frekuensi Kategori", TitleEN: sp("Toko Kelontong Makmur: Frekuensi Kategori"),
			StoryID: "Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nKami ingin tahu seberapa banyak setiap kategori atau kode muncul di sistem. Buatkan program penghitung frekuensi string.", StoryEN: sp("Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nKami ingin tahu seberapa banyak setiap kategori atau kode muncul di sistem. Buatkan program penghitung frekuensi string."),
			TaskID: "Buat `HitungFrekuensi(data []string) map[string]int`. Cetak A lalu B (hardcode print map[A] dan map[B]).", TaskEN: sp("Buat `HitungFrekuensi(data []string) map[string]int`. Cetak A lalu B (hardcode print map[A] dan map[B])."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: HitungFrekuensi\n\nfunc main() {\n    m := HitungFrekuensi([]string{\"A\", \"B\", \"A\"})\n    fmt.Println(m[\"A\"])\n    fmt.Println(m[\"B\"])\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc HitungFrekuensi(data []string) map[string]int {\n    m := make(map[string]int)\n    for _, v := range data { m[v]++ }\n    return m\n}\nfunc main() {\n    m := HitungFrekuensi([]string{\"A\", \"B\", \"A\"})\n    fmt.Println(m[\"A\"])\n    fmt.Println(m[\"B\"])\n}"),
			TestCases: j(`[{"input": "", "expected_output": "2\n1\n"}]`),
			ExpectedOutput: j(`"2\n1\n"`),
		},
		{ID: challengeUUID(106), Slug: "toko-dedup-106", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 106,
			TitleID: "Toko Kelontong Makmur: Hapus Duplikat", TitleEN: sp("Toko Kelontong Makmur: Hapus Duplikat"),
			StoryID: "Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nData kotor ini banyak entri ganda. Buatkan fungsi untuk menghapus duplikat dari list string dengan tetap menjaga urutan awal kemunculan.", StoryEN: sp("Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nData kotor ini banyak entri ganda. Buatkan fungsi untuk menghapus duplikat dari list string dengan tetap menjaga urutan awal kemunculan."),
			TaskID: "Buat `HapusDuplikat(data []string) []string`. Cetak baris per baris.", TaskEN: sp("Buat `HapusDuplikat(data []string) []string`. Cetak baris per baris."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: HapusDuplikat\n\nfunc main() {\n    res := HapusDuplikat([]string{\"X\", \"Y\", \"X\", \"Z\"})\n    for _, v := range res { fmt.Println(v) }\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc HapusDuplikat(data []string) []string {\n    seen := make(map[string]bool)\n    var res []string\n    for _, v := range data {\n        if !seen[v] { res = append(res, v); seen[v] = true }\n    }\n    return res\n}\nfunc main() {\n    res := HapusDuplikat([]string{\"X\", \"Y\", \"X\", \"Z\"})\n    for _, v := range res { fmt.Println(v) }\n}"),
			TestCases: j(`[{"input": "", "expected_output": "X\nY\nZ\n"}]`),
			ExpectedOutput: j(`"X\nY\nZ\n"`),
		},
		{ID: challengeUUID(107), Slug: "toko-palindrome-107", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 107,
			TitleID: "Toko Kelontong Makmur: Cek ID Palindrom", TitleEN: sp("Toko Kelontong Makmur: Cek ID Palindrom"),
			StoryID: "Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nSebagai pengaman, ID entri tertentu harus bersifat palindrom (dibaca dari depan dan belakang sama). Toleransi huruf besar-kecil tidak diperlukan.", StoryEN: sp("Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nSebagai pengaman, ID entri tertentu harus bersifat palindrom (dibaca dari depan dan belakang sama). Toleransi huruf besar-kecil tidak diperlukan."),
			TaskID: "Buat fungsi `IsPalindrome(s string) bool`. Cetak true/false.", TaskEN: sp("Buat fungsi `IsPalindrome(s string) bool`. Cetak true/false."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: IsPalindrome\n\nfunc main() {\n    fmt.Println(IsPalindrome(\"malam\"))\n    fmt.Println(IsPalindrome(\"siang\"))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc IsPalindrome(s string) bool {\n    r := []rune(s)\n    for i, j := 0, len(r)-1; i < j; i, j = i+1, j-1 {\n        if r[i] != r[j] { return false }\n    }\n    return true\n}\nfunc main() {\n    fmt.Println(IsPalindrome(\"malam\"))\n    fmt.Println(IsPalindrome(\"siang\"))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "true\nfalse\n"}]`),
			ExpectedOutput: j(`"true\nfalse\n"`),
		},
		{ID: challengeUUID(108), Slug: "toko-reverse-108", Language: "golang", Difficulty: "medium", XPReward: 30, OrderIndex: 108,
			TitleID: "Toko Kelontong Makmur: Balik Urutan", TitleEN: sp("Toko Kelontong Makmur: Balik Urutan"),
			StoryID: "Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nKarena kesalahan migrasi database, urutan log terbalik. Buatkan fungsi yang membalikkan slice integer layaknya stack.", StoryEN: sp("Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nKarena kesalahan migrasi database, urutan log terbalik. Buatkan fungsi yang membalikkan slice integer layaknya stack."),
			TaskID: "Buat fungsi `BalikArray(arr []int) []int` yang mereturn array terbalik (reverse).", TaskEN: sp("Buat fungsi `BalikArray(arr []int) []int` yang mereturn array terbalik (reverse)."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: BalikArray\n\nfunc main() {\n    res := BalikArray([]int{1, 2, 3})\n    for _, v := range res { fmt.Println(v) }\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc BalikArray(arr []int) []int {\n    res := make([]int, len(arr))\n    copy(res, arr)\n    for i, j := 0, len(res)-1; i < j; i, j = i+1, j-1 {\n        res[i], res[j] = res[j], res[i]\n    }\n    return res\n}\nfunc main() {\n    res := BalikArray([]int{1, 2, 3})\n    for _, v := range res { fmt.Println(v) }\n}"),
			TestCases: j(`[{"input": "", "expected_output": "3\n2\n1\n"}]`),
			ExpectedOutput: j(`"3\n2\n1\n"`),
		},
		{ID: challengeUUID(109), Slug: "toko-search-109", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 109,
			TitleID: "Toko Kelontong Makmur: Pencarian Biner Cepat", TitleEN: sp("Toko Kelontong Makmur: Pencarian Biner Cepat"),
			StoryID: "Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nData sudah berurut tapi ukurannya besar. Coba gunakan algoritma pencarian biner untuk mencari target secara efisien.", StoryEN: sp("Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nData sudah berurut tapi ukurannya besar. Coba gunakan algoritma pencarian biner untuk mencari target secara efisien."),
			TaskID: "Buat `BinarySearch(arr []int, target int) int` mereturn index atau -1 jika tak ada. Cari 20 di [10,20,30,40].", TaskEN: sp("Buat `BinarySearch(arr []int, target int) int` mereturn index atau -1 jika tak ada. Cari 20 di [10,20,30,40]."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: BinarySearch\n\nfunc main() {\n    fmt.Println(BinarySearch([]int{10, 20, 30, 40}, 20))\n    fmt.Println(BinarySearch([]int{10, 20, 30, 40}, 50))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc BinarySearch(arr []int, target int) int {\n    l, r := 0, len(arr)-1\n    for l <= r {\n        m := l + (r-l)/2\n        if arr[m] == target { return m }\n        if arr[m] < target { l = m+1 } else { r = m-1 }\n    }\n    return -1\n}\nfunc main() {\n    fmt.Println(BinarySearch([]int{10, 20, 30, 40}, 20))\n    fmt.Println(BinarySearch([]int{10, 20, 30, 40}, 50))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "1\n-1\n"}]`),
			ExpectedOutput: j(`"1\n-1\n"`),
		},
		{ID: challengeUUID(110), Slug: "toko-fibonacci-110", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 110,
			TitleID: "Toko Kelontong Makmur: Hitung Proyeksi Fibonacci", TitleEN: sp("Toko Kelontong Makmur: Hitung Proyeksi Fibonacci"),
			StoryID: "Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nPara peramal menggunakan proyeksi bilangan fibonacci untuk menaksir angka bulan depan. Buatkan fungsinya.", StoryEN: sp("Pak Budi manajer toko kelontong Makmur ingin otomatisasi.\n\nPara peramal menggunakan proyeksi bilangan fibonacci untuk menaksir angka bulan depan. Buatkan fungsinya."),
			TaskID: "Buat fungsi `Fibonacci(n int) int` mereturn angka ke-n (0-indexed). Cetak n=6.", TaskEN: sp("Buat fungsi `Fibonacci(n int) int` mereturn angka ke-n (0-indexed). Cetak n=6."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: Fibonacci\n\nfunc main() {\n    fmt.Println(Fibonacci(6))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc Fibonacci(n int) int {\n    if n <= 1 { return n }\n    a, b := 0, 1\n    for i := 2; i <= n; i++ {\n        a, b = b, a+b\n    }\n    return b\n}\nfunc main() {\n    fmt.Println(Fibonacci(6))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "8\n"}]`),
			ExpectedOutput: j(`"8\n"`),
		},
		{ID: challengeUUID(111), Slug: "rs-sum-111", Language: "golang", Difficulty: "medium", XPReward: 30, OrderIndex: 111,
			TitleID: "Rumah Sakit Sehat Sejahtera: Total Nominal", TitleEN: sp("Rumah Sakit Sehat Sejahtera: Total Nominal"),
			StoryID: "Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nTolong buatkan program untuk menghitung total semua angka di dalam list.", StoryEN: sp("Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nTolong buatkan program untuk menghitung total semua angka di dalam list."),
			TaskID: "Buat fungsi `HitungTotal(data []int) int` yang menjumlahkan semua elemen array.", TaskEN: sp("Buat fungsi `HitungTotal(data []int) int` yang menjumlahkan semua elemen array."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: buat fungsi HitungTotal\n\nfunc main() {\n    fmt.Println(HitungTotal([]int{10, 20, 30}))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc HitungTotal(data []int) int {\n    total := 0\n    for _, v := range data { total += v }\n    return total\n}\nfunc main() {\n    fmt.Println(HitungTotal([]int{10, 20, 30}))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "30\n"}]`),
			ExpectedOutput: j(`"30\n"`),
		},
		{ID: challengeUUID(112), Slug: "rs-max-112", Language: "golang", Difficulty: "hard", XPReward: 60, OrderIndex: 112,
			TitleID: "Rumah Sakit Sehat Sejahtera: Nilai Tertinggi", TitleEN: sp("Rumah Sakit Sehat Sejahtera: Nilai Tertinggi"),
			StoryID: "Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nKita butuh mengetahui angka paling besar di dalam kumpulan data untuk laporan akhir.", StoryEN: sp("Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nKita butuh mengetahui angka paling besar di dalam kumpulan data untuk laporan akhir."),
			TaskID: "Buat fungsi `CariMax(data []int) int` yang mengembalikan elemen terbesar awal. Jika kosong return 0.", TaskEN: sp("Buat fungsi `CariMax(data []int) int` yang mengembalikan elemen terbesar awal. Jika kosong return 0."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: buat fungsi CariMax\n\nfunc main() {\n    fmt.Println(CariMax([]int{15, 45, 20}))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc CariMax(data []int) int {\n    if len(data) == 0 { return 0 }\n    max := data[0]\n    for _, v := range data {\n        if v > max { max = v }\n    }\n    return max\n}\nfunc main() {\n    fmt.Println(CariMax([]int{15, 45, 20}))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "45\n"}]`),
			ExpectedOutput: j(`"45\n"`),
		},
		{ID: challengeUUID(113), Slug: "rs-filter-113", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 113,
			TitleID: "Rumah Sakit Sehat Sejahtera: Saring Data Lebih Dari 50", TitleEN: sp("Rumah Sakit Sehat Sejahtera: Saring Data Lebih Dari 50"),
			StoryID: "Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nBanyak data sampah atau nilai kecil. Saring angka yang di atas atau sama dengan 50.", StoryEN: sp("Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nBanyak data sampah atau nilai kecil. Saring angka yang di atas atau sama dengan 50."),
			TaskID: "Buat fungsi `SaringData(data []int) []int`. Cetak hasilnya (tanpa bracket format standard agar mudah). Return array baru.", TaskEN: sp("Buat fungsi `SaringData(data []int) []int`. Cetak hasilnya (tanpa bracket format standard agar mudah). Return array baru."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: buat fungsi SaringData\n\nfunc main() {\n    res := SaringData([]int{10, 50, 80, 20})\n    for _, v := range res { fmt.Println(v) }\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc SaringData(data []int) []int {\n    var res []int\n    for _, v := range data {\n        if v >= 50 { res = append(res, v) }\n    }\n    return res\n}\nfunc main() {\n    res := SaringData([]int{10, 50, 80, 20})\n    for _, v := range res { fmt.Println(v) }\n}"),
			TestCases: j(`[{"input": "", "expected_output": "50\n80\n"}]`),
			ExpectedOutput: j(`"50\n80\n"`),
		},
		{ID: challengeUUID(114), Slug: "rs-avg-114", Language: "golang", Difficulty: "medium", XPReward: 30, OrderIndex: 114,
			TitleID: "Rumah Sakit Sehat Sejahtera: Rata-Rata", TitleEN: sp("Rumah Sakit Sehat Sejahtera: Rata-Rata"),
			StoryID: "Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nUntuk laporan statistik, tolong program perhitungan nilai rata-rata dari slice integer terlampir.", StoryEN: sp("Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nUntuk laporan statistik, tolong program perhitungan nilai rata-rata dari slice integer terlampir."),
			TaskID: "Buat fungsi `RataRata(data []int) float64`. Jika kosong, return 0.0.", TaskEN: sp("Buat fungsi `RataRata(data []int) float64`. Jika kosong, return 0.0."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: buat RataRata\n\nfunc main() {\n    fmt.Printf(\"%.1f\n\", RataRata([]int{10, 20, 30}))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc RataRata(data []int) float64 {\n    if len(data) == 0 { return 0.0 }\n    sum := 0\n    for _, v := range data { sum += v }\n    return float64(sum)/float64(len(data))\n}\nfunc main() {\n    fmt.Printf(\"%.1f\n\", RataRata([]int{10, 20, 30}))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "20.0\n"}]`),
			ExpectedOutput: j(`"20.0\n"`),
		},
		{ID: challengeUUID(115), Slug: "rs-count-115", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 115,
			TitleID: "Rumah Sakit Sehat Sejahtera: Frekuensi Kategori", TitleEN: sp("Rumah Sakit Sehat Sejahtera: Frekuensi Kategori"),
			StoryID: "Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nKami ingin tahu seberapa banyak setiap kategori atau kode muncul di sistem. Buatkan program penghitung frekuensi string.", StoryEN: sp("Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nKami ingin tahu seberapa banyak setiap kategori atau kode muncul di sistem. Buatkan program penghitung frekuensi string."),
			TaskID: "Buat `HitungFrekuensi(data []string) map[string]int`. Cetak A lalu B (hardcode print map[A] dan map[B]).", TaskEN: sp("Buat `HitungFrekuensi(data []string) map[string]int`. Cetak A lalu B (hardcode print map[A] dan map[B])."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: HitungFrekuensi\n\nfunc main() {\n    m := HitungFrekuensi([]string{\"A\", \"B\", \"A\"})\n    fmt.Println(m[\"A\"])\n    fmt.Println(m[\"B\"])\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc HitungFrekuensi(data []string) map[string]int {\n    m := make(map[string]int)\n    for _, v := range data { m[v]++ }\n    return m\n}\nfunc main() {\n    m := HitungFrekuensi([]string{\"A\", \"B\", \"A\"})\n    fmt.Println(m[\"A\"])\n    fmt.Println(m[\"B\"])\n}"),
			TestCases: j(`[{"input": "", "expected_output": "2\n1\n"}]`),
			ExpectedOutput: j(`"2\n1\n"`),
		},
		{ID: challengeUUID(116), Slug: "rs-dedup-116", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 116,
			TitleID: "Rumah Sakit Sehat Sejahtera: Hapus Duplikat", TitleEN: sp("Rumah Sakit Sehat Sejahtera: Hapus Duplikat"),
			StoryID: "Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nData kotor ini banyak entri ganda. Buatkan fungsi untuk menghapus duplikat dari list string dengan tetap menjaga urutan awal kemunculan.", StoryEN: sp("Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nData kotor ini banyak entri ganda. Buatkan fungsi untuk menghapus duplikat dari list string dengan tetap menjaga urutan awal kemunculan."),
			TaskID: "Buat `HapusDuplikat(data []string) []string`. Cetak baris per baris.", TaskEN: sp("Buat `HapusDuplikat(data []string) []string`. Cetak baris per baris."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: HapusDuplikat\n\nfunc main() {\n    res := HapusDuplikat([]string{\"X\", \"Y\", \"X\", \"Z\"})\n    for _, v := range res { fmt.Println(v) }\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc HapusDuplikat(data []string) []string {\n    seen := make(map[string]bool)\n    var res []string\n    for _, v := range data {\n        if !seen[v] { res = append(res, v); seen[v] = true }\n    }\n    return res\n}\nfunc main() {\n    res := HapusDuplikat([]string{\"X\", \"Y\", \"X\", \"Z\"})\n    for _, v := range res { fmt.Println(v) }\n}"),
			TestCases: j(`[{"input": "", "expected_output": "X\nY\nZ\n"}]`),
			ExpectedOutput: j(`"X\nY\nZ\n"`),
		},
		{ID: challengeUUID(117), Slug: "rs-palindrome-117", Language: "golang", Difficulty: "medium", XPReward: 30, OrderIndex: 117,
			TitleID: "Rumah Sakit Sehat Sejahtera: Cek ID Palindrom", TitleEN: sp("Rumah Sakit Sehat Sejahtera: Cek ID Palindrom"),
			StoryID: "Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nSebagai pengaman, ID entri tertentu harus bersifat palindrom (dibaca dari depan dan belakang sama). Toleransi huruf besar-kecil tidak diperlukan.", StoryEN: sp("Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nSebagai pengaman, ID entri tertentu harus bersifat palindrom (dibaca dari depan dan belakang sama). Toleransi huruf besar-kecil tidak diperlukan."),
			TaskID: "Buat fungsi `IsPalindrome(s string) bool`. Cetak true/false.", TaskEN: sp("Buat fungsi `IsPalindrome(s string) bool`. Cetak true/false."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: IsPalindrome\n\nfunc main() {\n    fmt.Println(IsPalindrome(\"malam\"))\n    fmt.Println(IsPalindrome(\"siang\"))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc IsPalindrome(s string) bool {\n    r := []rune(s)\n    for i, j := 0, len(r)-1; i < j; i, j = i+1, j-1 {\n        if r[i] != r[j] { return false }\n    }\n    return true\n}\nfunc main() {\n    fmt.Println(IsPalindrome(\"malam\"))\n    fmt.Println(IsPalindrome(\"siang\"))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "true\nfalse\n"}]`),
			ExpectedOutput: j(`"true\nfalse\n"`),
		},
		{ID: challengeUUID(118), Slug: "rs-reverse-118", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 118,
			TitleID: "Rumah Sakit Sehat Sejahtera: Balik Urutan", TitleEN: sp("Rumah Sakit Sehat Sejahtera: Balik Urutan"),
			StoryID: "Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nKarena kesalahan migrasi database, urutan log terbalik. Buatkan fungsi yang membalikkan slice integer layaknya stack.", StoryEN: sp("Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nKarena kesalahan migrasi database, urutan log terbalik. Buatkan fungsi yang membalikkan slice integer layaknya stack."),
			TaskID: "Buat fungsi `BalikArray(arr []int) []int` yang mereturn array terbalik (reverse).", TaskEN: sp("Buat fungsi `BalikArray(arr []int) []int` yang mereturn array terbalik (reverse)."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: BalikArray\n\nfunc main() {\n    res := BalikArray([]int{1, 2, 3})\n    for _, v := range res { fmt.Println(v) }\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc BalikArray(arr []int) []int {\n    res := make([]int, len(arr))\n    copy(res, arr)\n    for i, j := 0, len(res)-1; i < j; i, j = i+1, j-1 {\n        res[i], res[j] = res[j], res[i]\n    }\n    return res\n}\nfunc main() {\n    res := BalikArray([]int{1, 2, 3})\n    for _, v := range res { fmt.Println(v) }\n}"),
			TestCases: j(`[{"input": "", "expected_output": "3\n2\n1\n"}]`),
			ExpectedOutput: j(`"3\n2\n1\n"`),
		},
		{ID: challengeUUID(119), Slug: "rs-search-119", Language: "golang", Difficulty: "hard", XPReward: 60, OrderIndex: 119,
			TitleID: "Rumah Sakit Sehat Sejahtera: Pencarian Biner Cepat", TitleEN: sp("Rumah Sakit Sehat Sejahtera: Pencarian Biner Cepat"),
			StoryID: "Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nData sudah berurut tapi ukurannya besar. Coba gunakan algoritma pencarian biner untuk mencari target secara efisien.", StoryEN: sp("Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nData sudah berurut tapi ukurannya besar. Coba gunakan algoritma pencarian biner untuk mencari target secara efisien."),
			TaskID: "Buat `BinarySearch(arr []int, target int) int` mereturn index atau -1 jika tak ada. Cari 20 di [10,20,30,40].", TaskEN: sp("Buat `BinarySearch(arr []int, target int) int` mereturn index atau -1 jika tak ada. Cari 20 di [10,20,30,40]."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: BinarySearch\n\nfunc main() {\n    fmt.Println(BinarySearch([]int{10, 20, 30, 40}, 20))\n    fmt.Println(BinarySearch([]int{10, 20, 30, 40}, 50))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc BinarySearch(arr []int, target int) int {\n    l, r := 0, len(arr)-1\n    for l <= r {\n        m := l + (r-l)/2\n        if arr[m] == target { return m }\n        if arr[m] < target { l = m+1 } else { r = m-1 }\n    }\n    return -1\n}\nfunc main() {\n    fmt.Println(BinarySearch([]int{10, 20, 30, 40}, 20))\n    fmt.Println(BinarySearch([]int{10, 20, 30, 40}, 50))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "1\n-1\n"}]`),
			ExpectedOutput: j(`"1\n-1\n"`),
		},
		{ID: challengeUUID(120), Slug: "rs-fibonacci-120", Language: "golang", Difficulty: "medium", XPReward: 30, OrderIndex: 120,
			TitleID: "Rumah Sakit Sehat Sejahtera: Hitung Proyeksi Fibonacci", TitleEN: sp("Rumah Sakit Sehat Sejahtera: Hitung Proyeksi Fibonacci"),
			StoryID: "Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nPara peramal menggunakan proyeksi bilangan fibonacci untuk menaksir angka bulan depan. Buatkan fungsinya.", StoryEN: sp("Sistem admin rumah sakit butuh fungsi rekap medis pasien.\n\nPara peramal menggunakan proyeksi bilangan fibonacci untuk menaksir angka bulan depan. Buatkan fungsinya."),
			TaskID: "Buat fungsi `Fibonacci(n int) int` mereturn angka ke-n (0-indexed). Cetak n=6.", TaskEN: sp("Buat fungsi `Fibonacci(n int) int` mereturn angka ke-n (0-indexed). Cetak n=6."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: Fibonacci\n\nfunc main() {\n    fmt.Println(Fibonacci(6))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc Fibonacci(n int) int {\n    if n <= 1 { return n }\n    a, b := 0, 1\n    for i := 2; i <= n; i++ {\n        a, b = b, a+b\n    }\n    return b\n}\nfunc main() {\n    fmt.Println(Fibonacci(6))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "8\n"}]`),
			ExpectedOutput: j(`"8\n"`),
		},
		{ID: challengeUUID(121), Slug: "sekolah-sum-121", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 121,
			TitleID: "SMA Harapan Bangsa: Total Nominal", TitleEN: sp("SMA Harapan Bangsa: Total Nominal"),
			StoryID: "Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nTolong buatkan program untuk menghitung total semua angka di dalam list.", StoryEN: sp("Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nTolong buatkan program untuk menghitung total semua angka di dalam list."),
			TaskID: "Buat fungsi `HitungTotal(data []int) int` yang menjumlahkan semua elemen array.", TaskEN: sp("Buat fungsi `HitungTotal(data []int) int` yang menjumlahkan semua elemen array."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: buat fungsi HitungTotal\n\nfunc main() {\n    fmt.Println(HitungTotal([]int{10, 20, 30}))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc HitungTotal(data []int) int {\n    total := 0\n    for _, v := range data { total += v }\n    return total\n}\nfunc main() {\n    fmt.Println(HitungTotal([]int{10, 20, 30}))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "30\n"}]`),
			ExpectedOutput: j(`"30\n"`),
		},
		{ID: challengeUUID(122), Slug: "sekolah-max-122", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 122,
			TitleID: "SMA Harapan Bangsa: Nilai Tertinggi", TitleEN: sp("SMA Harapan Bangsa: Nilai Tertinggi"),
			StoryID: "Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nKita butuh mengetahui angka paling besar di dalam kumpulan data untuk laporan akhir.", StoryEN: sp("Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nKita butuh mengetahui angka paling besar di dalam kumpulan data untuk laporan akhir."),
			TaskID: "Buat fungsi `CariMax(data []int) int` yang mengembalikan elemen terbesar awal. Jika kosong return 0.", TaskEN: sp("Buat fungsi `CariMax(data []int) int` yang mengembalikan elemen terbesar awal. Jika kosong return 0."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: buat fungsi CariMax\n\nfunc main() {\n    fmt.Println(CariMax([]int{15, 45, 20}))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc CariMax(data []int) int {\n    if len(data) == 0 { return 0 }\n    max := data[0]\n    for _, v := range data {\n        if v > max { max = v }\n    }\n    return max\n}\nfunc main() {\n    fmt.Println(CariMax([]int{15, 45, 20}))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "45\n"}]`),
			ExpectedOutput: j(`"45\n"`),
		},
		{ID: challengeUUID(123), Slug: "sekolah-filter-123", Language: "golang", Difficulty: "medium", XPReward: 30, OrderIndex: 123,
			TitleID: "SMA Harapan Bangsa: Saring Data Lebih Dari 50", TitleEN: sp("SMA Harapan Bangsa: Saring Data Lebih Dari 50"),
			StoryID: "Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nBanyak data sampah atau nilai kecil. Saring angka yang di atas atau sama dengan 50.", StoryEN: sp("Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nBanyak data sampah atau nilai kecil. Saring angka yang di atas atau sama dengan 50."),
			TaskID: "Buat fungsi `SaringData(data []int) []int`. Cetak hasilnya (tanpa bracket format standard agar mudah). Return array baru.", TaskEN: sp("Buat fungsi `SaringData(data []int) []int`. Cetak hasilnya (tanpa bracket format standard agar mudah). Return array baru."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: buat fungsi SaringData\n\nfunc main() {\n    res := SaringData([]int{10, 50, 80, 20})\n    for _, v := range res { fmt.Println(v) }\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc SaringData(data []int) []int {\n    var res []int\n    for _, v := range data {\n        if v >= 50 { res = append(res, v) }\n    }\n    return res\n}\nfunc main() {\n    res := SaringData([]int{10, 50, 80, 20})\n    for _, v := range res { fmt.Println(v) }\n}"),
			TestCases: j(`[{"input": "", "expected_output": "50\n80\n"}]`),
			ExpectedOutput: j(`"50\n80\n"`),
		},
		{ID: challengeUUID(124), Slug: "sekolah-avg-124", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 124,
			TitleID: "SMA Harapan Bangsa: Rata-Rata", TitleEN: sp("SMA Harapan Bangsa: Rata-Rata"),
			StoryID: "Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nUntuk laporan statistik, tolong program perhitungan nilai rata-rata dari slice integer terlampir.", StoryEN: sp("Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nUntuk laporan statistik, tolong program perhitungan nilai rata-rata dari slice integer terlampir."),
			TaskID: "Buat fungsi `RataRata(data []int) float64`. Jika kosong, return 0.0.", TaskEN: sp("Buat fungsi `RataRata(data []int) float64`. Jika kosong, return 0.0."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: buat RataRata\n\nfunc main() {\n    fmt.Printf(\"%.1f\n\", RataRata([]int{10, 20, 30}))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc RataRata(data []int) float64 {\n    if len(data) == 0 { return 0.0 }\n    sum := 0\n    for _, v := range data { sum += v }\n    return float64(sum)/float64(len(data))\n}\nfunc main() {\n    fmt.Printf(\"%.1f\n\", RataRata([]int{10, 20, 30}))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "20.0\n"}]`),
			ExpectedOutput: j(`"20.0\n"`),
		},
		{ID: challengeUUID(125), Slug: "sekolah-count-125", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 125,
			TitleID: "SMA Harapan Bangsa: Frekuensi Kategori", TitleEN: sp("SMA Harapan Bangsa: Frekuensi Kategori"),
			StoryID: "Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nKami ingin tahu seberapa banyak setiap kategori atau kode muncul di sistem. Buatkan program penghitung frekuensi string.", StoryEN: sp("Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nKami ingin tahu seberapa banyak setiap kategori atau kode muncul di sistem. Buatkan program penghitung frekuensi string."),
			TaskID: "Buat `HitungFrekuensi(data []string) map[string]int`. Cetak A lalu B (hardcode print map[A] dan map[B]).", TaskEN: sp("Buat `HitungFrekuensi(data []string) map[string]int`. Cetak A lalu B (hardcode print map[A] dan map[B])."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: HitungFrekuensi\n\nfunc main() {\n    m := HitungFrekuensi([]string{\"A\", \"B\", \"A\"})\n    fmt.Println(m[\"A\"])\n    fmt.Println(m[\"B\"])\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc HitungFrekuensi(data []string) map[string]int {\n    m := make(map[string]int)\n    for _, v := range data { m[v]++ }\n    return m\n}\nfunc main() {\n    m := HitungFrekuensi([]string{\"A\", \"B\", \"A\"})\n    fmt.Println(m[\"A\"])\n    fmt.Println(m[\"B\"])\n}"),
			TestCases: j(`[{"input": "", "expected_output": "2\n1\n"}]`),
			ExpectedOutput: j(`"2\n1\n"`),
		},
		{ID: challengeUUID(126), Slug: "sekolah-dedup-126", Language: "golang", Difficulty: "hard", XPReward: 60, OrderIndex: 126,
			TitleID: "SMA Harapan Bangsa: Hapus Duplikat", TitleEN: sp("SMA Harapan Bangsa: Hapus Duplikat"),
			StoryID: "Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nData kotor ini banyak entri ganda. Buatkan fungsi untuk menghapus duplikat dari list string dengan tetap menjaga urutan awal kemunculan.", StoryEN: sp("Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nData kotor ini banyak entri ganda. Buatkan fungsi untuk menghapus duplikat dari list string dengan tetap menjaga urutan awal kemunculan."),
			TaskID: "Buat `HapusDuplikat(data []string) []string`. Cetak baris per baris.", TaskEN: sp("Buat `HapusDuplikat(data []string) []string`. Cetak baris per baris."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: HapusDuplikat\n\nfunc main() {\n    res := HapusDuplikat([]string{\"X\", \"Y\", \"X\", \"Z\"})\n    for _, v := range res { fmt.Println(v) }\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc HapusDuplikat(data []string) []string {\n    seen := make(map[string]bool)\n    var res []string\n    for _, v := range data {\n        if !seen[v] { res = append(res, v); seen[v] = true }\n    }\n    return res\n}\nfunc main() {\n    res := HapusDuplikat([]string{\"X\", \"Y\", \"X\", \"Z\"})\n    for _, v := range res { fmt.Println(v) }\n}"),
			TestCases: j(`[{"input": "", "expected_output": "X\nY\nZ\n"}]`),
			ExpectedOutput: j(`"X\nY\nZ\n"`),
		},
		{ID: challengeUUID(127), Slug: "sekolah-palindrome-127", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 127,
			TitleID: "SMA Harapan Bangsa: Cek ID Palindrom", TitleEN: sp("SMA Harapan Bangsa: Cek ID Palindrom"),
			StoryID: "Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nSebagai pengaman, ID entri tertentu harus bersifat palindrom (dibaca dari depan dan belakang sama). Toleransi huruf besar-kecil tidak diperlukan.", StoryEN: sp("Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nSebagai pengaman, ID entri tertentu harus bersifat palindrom (dibaca dari depan dan belakang sama). Toleransi huruf besar-kecil tidak diperlukan."),
			TaskID: "Buat fungsi `IsPalindrome(s string) bool`. Cetak true/false.", TaskEN: sp("Buat fungsi `IsPalindrome(s string) bool`. Cetak true/false."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: IsPalindrome\n\nfunc main() {\n    fmt.Println(IsPalindrome(\"malam\"))\n    fmt.Println(IsPalindrome(\"siang\"))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc IsPalindrome(s string) bool {\n    r := []rune(s)\n    for i, j := 0, len(r)-1; i < j; i, j = i+1, j-1 {\n        if r[i] != r[j] { return false }\n    }\n    return true\n}\nfunc main() {\n    fmt.Println(IsPalindrome(\"malam\"))\n    fmt.Println(IsPalindrome(\"siang\"))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "true\nfalse\n"}]`),
			ExpectedOutput: j(`"true\nfalse\n"`),
		},
		{ID: challengeUUID(128), Slug: "sekolah-reverse-128", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 128,
			TitleID: "SMA Harapan Bangsa: Balik Urutan", TitleEN: sp("SMA Harapan Bangsa: Balik Urutan"),
			StoryID: "Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nKarena kesalahan migrasi database, urutan log terbalik. Buatkan fungsi yang membalikkan slice integer layaknya stack.", StoryEN: sp("Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nKarena kesalahan migrasi database, urutan log terbalik. Buatkan fungsi yang membalikkan slice integer layaknya stack."),
			TaskID: "Buat fungsi `BalikArray(arr []int) []int` yang mereturn array terbalik (reverse).", TaskEN: sp("Buat fungsi `BalikArray(arr []int) []int` yang mereturn array terbalik (reverse)."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: BalikArray\n\nfunc main() {\n    res := BalikArray([]int{1, 2, 3})\n    for _, v := range res { fmt.Println(v) }\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc BalikArray(arr []int) []int {\n    res := make([]int, len(arr))\n    copy(res, arr)\n    for i, j := 0, len(res)-1; i < j; i, j = i+1, j-1 {\n        res[i], res[j] = res[j], res[i]\n    }\n    return res\n}\nfunc main() {\n    res := BalikArray([]int{1, 2, 3})\n    for _, v := range res { fmt.Println(v) }\n}"),
			TestCases: j(`[{"input": "", "expected_output": "3\n2\n1\n"}]`),
			ExpectedOutput: j(`"3\n2\n1\n"`),
		},
		{ID: challengeUUID(129), Slug: "sekolah-search-129", Language: "golang", Difficulty: "medium", XPReward: 30, OrderIndex: 129,
			TitleID: "SMA Harapan Bangsa: Pencarian Biner Cepat", TitleEN: sp("SMA Harapan Bangsa: Pencarian Biner Cepat"),
			StoryID: "Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nData sudah berurut tapi ukurannya besar. Coba gunakan algoritma pencarian biner untuk mencari target secara efisien.", StoryEN: sp("Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nData sudah berurut tapi ukurannya besar. Coba gunakan algoritma pencarian biner untuk mencari target secara efisien."),
			TaskID: "Buat `BinarySearch(arr []int, target int) int` mereturn index atau -1 jika tak ada. Cari 20 di [10,20,30,40].", TaskEN: sp("Buat `BinarySearch(arr []int, target int) int` mereturn index atau -1 jika tak ada. Cari 20 di [10,20,30,40]."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: BinarySearch\n\nfunc main() {\n    fmt.Println(BinarySearch([]int{10, 20, 30, 40}, 20))\n    fmt.Println(BinarySearch([]int{10, 20, 30, 40}, 50))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc BinarySearch(arr []int, target int) int {\n    l, r := 0, len(arr)-1\n    for l <= r {\n        m := l + (r-l)/2\n        if arr[m] == target { return m }\n        if arr[m] < target { l = m+1 } else { r = m-1 }\n    }\n    return -1\n}\nfunc main() {\n    fmt.Println(BinarySearch([]int{10, 20, 30, 40}, 20))\n    fmt.Println(BinarySearch([]int{10, 20, 30, 40}, 50))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "1\n-1\n"}]`),
			ExpectedOutput: j(`"1\n-1\n"`),
		},
		{ID: challengeUUID(130), Slug: "sekolah-fibonacci-130", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 130,
			TitleID: "SMA Harapan Bangsa: Hitung Proyeksi Fibonacci", TitleEN: sp("SMA Harapan Bangsa: Hitung Proyeksi Fibonacci"),
			StoryID: "Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nPara peramal menggunakan proyeksi bilangan fibonacci untuk menaksir angka bulan depan. Buatkan fungsinya.", StoryEN: sp("Kepala sekolah ingin mendata nilai murid dengan aplikasi Go.\n\nPara peramal menggunakan proyeksi bilangan fibonacci untuk menaksir angka bulan depan. Buatkan fungsinya."),
			TaskID: "Buat fungsi `Fibonacci(n int) int` mereturn angka ke-n (0-indexed). Cetak n=6.", TaskEN: sp("Buat fungsi `Fibonacci(n int) int` mereturn angka ke-n (0-indexed). Cetak n=6."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: Fibonacci\n\nfunc main() {\n    fmt.Println(Fibonacci(6))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc Fibonacci(n int) int {\n    if n <= 1 { return n }\n    a, b := 0, 1\n    for i := 2; i <= n; i++ {\n        a, b = b, a+b\n    }\n    return b\n}\nfunc main() {\n    fmt.Println(Fibonacci(6))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "8\n"}]`),
			ExpectedOutput: j(`"8\n"`),
		},
		{ID: challengeUUID(131), Slug: "pabrik-sum-131", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 131,
			TitleID: "Pabrik Sepatu Super: Total Nominal", TitleEN: sp("Pabrik Sepatu Super: Total Nominal"),
			StoryID: "Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nTolong buatkan program untuk menghitung total semua angka di dalam list.", StoryEN: sp("Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nTolong buatkan program untuk menghitung total semua angka di dalam list."),
			TaskID: "Buat fungsi `HitungTotal(data []int) int` yang menjumlahkan semua elemen array.", TaskEN: sp("Buat fungsi `HitungTotal(data []int) int` yang menjumlahkan semua elemen array."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: buat fungsi HitungTotal\n\nfunc main() {\n    fmt.Println(HitungTotal([]int{10, 20, 30}))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc HitungTotal(data []int) int {\n    total := 0\n    for _, v := range data { total += v }\n    return total\n}\nfunc main() {\n    fmt.Println(HitungTotal([]int{10, 20, 30}))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "30\n"}]`),
			ExpectedOutput: j(`"30\n"`),
		},
		{ID: challengeUUID(132), Slug: "pabrik-max-132", Language: "golang", Difficulty: "medium", XPReward: 30, OrderIndex: 132,
			TitleID: "Pabrik Sepatu Super: Nilai Tertinggi", TitleEN: sp("Pabrik Sepatu Super: Nilai Tertinggi"),
			StoryID: "Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nKita butuh mengetahui angka paling besar di dalam kumpulan data untuk laporan akhir.", StoryEN: sp("Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nKita butuh mengetahui angka paling besar di dalam kumpulan data untuk laporan akhir."),
			TaskID: "Buat fungsi `CariMax(data []int) int` yang mengembalikan elemen terbesar awal. Jika kosong return 0.", TaskEN: sp("Buat fungsi `CariMax(data []int) int` yang mengembalikan elemen terbesar awal. Jika kosong return 0."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: buat fungsi CariMax\n\nfunc main() {\n    fmt.Println(CariMax([]int{15, 45, 20}))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc CariMax(data []int) int {\n    if len(data) == 0 { return 0 }\n    max := data[0]\n    for _, v := range data {\n        if v > max { max = v }\n    }\n    return max\n}\nfunc main() {\n    fmt.Println(CariMax([]int{15, 45, 20}))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "45\n"}]`),
			ExpectedOutput: j(`"45\n"`),
		},
		{ID: challengeUUID(133), Slug: "pabrik-filter-133", Language: "golang", Difficulty: "hard", XPReward: 60, OrderIndex: 133,
			TitleID: "Pabrik Sepatu Super: Saring Data Lebih Dari 50", TitleEN: sp("Pabrik Sepatu Super: Saring Data Lebih Dari 50"),
			StoryID: "Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nBanyak data sampah atau nilai kecil. Saring angka yang di atas atau sama dengan 50.", StoryEN: sp("Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nBanyak data sampah atau nilai kecil. Saring angka yang di atas atau sama dengan 50."),
			TaskID: "Buat fungsi `SaringData(data []int) []int`. Cetak hasilnya (tanpa bracket format standard agar mudah). Return array baru.", TaskEN: sp("Buat fungsi `SaringData(data []int) []int`. Cetak hasilnya (tanpa bracket format standard agar mudah). Return array baru."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: buat fungsi SaringData\n\nfunc main() {\n    res := SaringData([]int{10, 50, 80, 20})\n    for _, v := range res { fmt.Println(v) }\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc SaringData(data []int) []int {\n    var res []int\n    for _, v := range data {\n        if v >= 50 { res = append(res, v) }\n    }\n    return res\n}\nfunc main() {\n    res := SaringData([]int{10, 50, 80, 20})\n    for _, v := range res { fmt.Println(v) }\n}"),
			TestCases: j(`[{"input": "", "expected_output": "50\n80\n"}]`),
			ExpectedOutput: j(`"50\n80\n"`),
		},
		{ID: challengeUUID(134), Slug: "pabrik-avg-134", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 134,
			TitleID: "Pabrik Sepatu Super: Rata-Rata", TitleEN: sp("Pabrik Sepatu Super: Rata-Rata"),
			StoryID: "Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nUntuk laporan statistik, tolong program perhitungan nilai rata-rata dari slice integer terlampir.", StoryEN: sp("Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nUntuk laporan statistik, tolong program perhitungan nilai rata-rata dari slice integer terlampir."),
			TaskID: "Buat fungsi `RataRata(data []int) float64`. Jika kosong, return 0.0.", TaskEN: sp("Buat fungsi `RataRata(data []int) float64`. Jika kosong, return 0.0."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: buat RataRata\n\nfunc main() {\n    fmt.Printf(\"%.1f\n\", RataRata([]int{10, 20, 30}))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc RataRata(data []int) float64 {\n    if len(data) == 0 { return 0.0 }\n    sum := 0\n    for _, v := range data { sum += v }\n    return float64(sum)/float64(len(data))\n}\nfunc main() {\n    fmt.Printf(\"%.1f\n\", RataRata([]int{10, 20, 30}))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "20.0\n"}]`),
			ExpectedOutput: j(`"20.0\n"`),
		},
		{ID: challengeUUID(135), Slug: "pabrik-count-135", Language: "golang", Difficulty: "medium", XPReward: 30, OrderIndex: 135,
			TitleID: "Pabrik Sepatu Super: Frekuensi Kategori", TitleEN: sp("Pabrik Sepatu Super: Frekuensi Kategori"),
			StoryID: "Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nKami ingin tahu seberapa banyak setiap kategori atau kode muncul di sistem. Buatkan program penghitung frekuensi string.", StoryEN: sp("Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nKami ingin tahu seberapa banyak setiap kategori atau kode muncul di sistem. Buatkan program penghitung frekuensi string."),
			TaskID: "Buat `HitungFrekuensi(data []string) map[string]int`. Cetak A lalu B (hardcode print map[A] dan map[B]).", TaskEN: sp("Buat `HitungFrekuensi(data []string) map[string]int`. Cetak A lalu B (hardcode print map[A] dan map[B])."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: HitungFrekuensi\n\nfunc main() {\n    m := HitungFrekuensi([]string{\"A\", \"B\", \"A\"})\n    fmt.Println(m[\"A\"])\n    fmt.Println(m[\"B\"])\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc HitungFrekuensi(data []string) map[string]int {\n    m := make(map[string]int)\n    for _, v := range data { m[v]++ }\n    return m\n}\nfunc main() {\n    m := HitungFrekuensi([]string{\"A\", \"B\", \"A\"})\n    fmt.Println(m[\"A\"])\n    fmt.Println(m[\"B\"])\n}"),
			TestCases: j(`[{"input": "", "expected_output": "2\n1\n"}]`),
			ExpectedOutput: j(`"2\n1\n"`),
		},
		{ID: challengeUUID(136), Slug: "pabrik-dedup-136", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 136,
			TitleID: "Pabrik Sepatu Super: Hapus Duplikat", TitleEN: sp("Pabrik Sepatu Super: Hapus Duplikat"),
			StoryID: "Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nData kotor ini banyak entri ganda. Buatkan fungsi untuk menghapus duplikat dari list string dengan tetap menjaga urutan awal kemunculan.", StoryEN: sp("Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nData kotor ini banyak entri ganda. Buatkan fungsi untuk menghapus duplikat dari list string dengan tetap menjaga urutan awal kemunculan."),
			TaskID: "Buat `HapusDuplikat(data []string) []string`. Cetak baris per baris.", TaskEN: sp("Buat `HapusDuplikat(data []string) []string`. Cetak baris per baris."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: HapusDuplikat\n\nfunc main() {\n    res := HapusDuplikat([]string{\"X\", \"Y\", \"X\", \"Z\"})\n    for _, v := range res { fmt.Println(v) }\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc HapusDuplikat(data []string) []string {\n    seen := make(map[string]bool)\n    var res []string\n    for _, v := range data {\n        if !seen[v] { res = append(res, v); seen[v] = true }\n    }\n    return res\n}\nfunc main() {\n    res := HapusDuplikat([]string{\"X\", \"Y\", \"X\", \"Z\"})\n    for _, v := range res { fmt.Println(v) }\n}"),
			TestCases: j(`[{"input": "", "expected_output": "X\nY\nZ\n"}]`),
			ExpectedOutput: j(`"X\nY\nZ\n"`),
		},
		{ID: challengeUUID(137), Slug: "pabrik-palindrome-137", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 137,
			TitleID: "Pabrik Sepatu Super: Cek ID Palindrom", TitleEN: sp("Pabrik Sepatu Super: Cek ID Palindrom"),
			StoryID: "Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nSebagai pengaman, ID entri tertentu harus bersifat palindrom (dibaca dari depan dan belakang sama). Toleransi huruf besar-kecil tidak diperlukan.", StoryEN: sp("Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nSebagai pengaman, ID entri tertentu harus bersifat palindrom (dibaca dari depan dan belakang sama). Toleransi huruf besar-kecil tidak diperlukan."),
			TaskID: "Buat fungsi `IsPalindrome(s string) bool`. Cetak true/false.", TaskEN: sp("Buat fungsi `IsPalindrome(s string) bool`. Cetak true/false."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: IsPalindrome\n\nfunc main() {\n    fmt.Println(IsPalindrome(\"malam\"))\n    fmt.Println(IsPalindrome(\"siang\"))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc IsPalindrome(s string) bool {\n    r := []rune(s)\n    for i, j := 0, len(r)-1; i < j; i, j = i+1, j-1 {\n        if r[i] != r[j] { return false }\n    }\n    return true\n}\nfunc main() {\n    fmt.Println(IsPalindrome(\"malam\"))\n    fmt.Println(IsPalindrome(\"siang\"))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "true\nfalse\n"}]`),
			ExpectedOutput: j(`"true\nfalse\n"`),
		},
		{ID: challengeUUID(138), Slug: "pabrik-reverse-138", Language: "golang", Difficulty: "medium", XPReward: 30, OrderIndex: 138,
			TitleID: "Pabrik Sepatu Super: Balik Urutan", TitleEN: sp("Pabrik Sepatu Super: Balik Urutan"),
			StoryID: "Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nKarena kesalahan migrasi database, urutan log terbalik. Buatkan fungsi yang membalikkan slice integer layaknya stack.", StoryEN: sp("Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nKarena kesalahan migrasi database, urutan log terbalik. Buatkan fungsi yang membalikkan slice integer layaknya stack."),
			TaskID: "Buat fungsi `BalikArray(arr []int) []int` yang mereturn array terbalik (reverse).", TaskEN: sp("Buat fungsi `BalikArray(arr []int) []int` yang mereturn array terbalik (reverse)."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: BalikArray\n\nfunc main() {\n    res := BalikArray([]int{1, 2, 3})\n    for _, v := range res { fmt.Println(v) }\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc BalikArray(arr []int) []int {\n    res := make([]int, len(arr))\n    copy(res, arr)\n    for i, j := 0, len(res)-1; i < j; i, j = i+1, j-1 {\n        res[i], res[j] = res[j], res[i]\n    }\n    return res\n}\nfunc main() {\n    res := BalikArray([]int{1, 2, 3})\n    for _, v := range res { fmt.Println(v) }\n}"),
			TestCases: j(`[{"input": "", "expected_output": "3\n2\n1\n"}]`),
			ExpectedOutput: j(`"3\n2\n1\n"`),
		},
		{ID: challengeUUID(139), Slug: "pabrik-search-139", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 139,
			TitleID: "Pabrik Sepatu Super: Pencarian Biner Cepat", TitleEN: sp("Pabrik Sepatu Super: Pencarian Biner Cepat"),
			StoryID: "Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nData sudah berurut tapi ukurannya besar. Coba gunakan algoritma pencarian biner untuk mencari target secara efisien.", StoryEN: sp("Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nData sudah berurut tapi ukurannya besar. Coba gunakan algoritma pencarian biner untuk mencari target secara efisien."),
			TaskID: "Buat `BinarySearch(arr []int, target int) int` mereturn index atau -1 jika tak ada. Cari 20 di [10,20,30,40].", TaskEN: sp("Buat `BinarySearch(arr []int, target int) int` mereturn index atau -1 jika tak ada. Cari 20 di [10,20,30,40]."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: BinarySearch\n\nfunc main() {\n    fmt.Println(BinarySearch([]int{10, 20, 30, 40}, 20))\n    fmt.Println(BinarySearch([]int{10, 20, 30, 40}, 50))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc BinarySearch(arr []int, target int) int {\n    l, r := 0, len(arr)-1\n    for l <= r {\n        m := l + (r-l)/2\n        if arr[m] == target { return m }\n        if arr[m] < target { l = m+1 } else { r = m-1 }\n    }\n    return -1\n}\nfunc main() {\n    fmt.Println(BinarySearch([]int{10, 20, 30, 40}, 20))\n    fmt.Println(BinarySearch([]int{10, 20, 30, 40}, 50))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "1\n-1\n"}]`),
			ExpectedOutput: j(`"1\n-1\n"`),
		},
		{ID: challengeUUID(140), Slug: "pabrik-fibonacci-140", Language: "golang", Difficulty: "hard", XPReward: 60, OrderIndex: 140,
			TitleID: "Pabrik Sepatu Super: Hitung Proyeksi Fibonacci", TitleEN: sp("Pabrik Sepatu Super: Hitung Proyeksi Fibonacci"),
			StoryID: "Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nPara peramal menggunakan proyeksi bilangan fibonacci untuk menaksir angka bulan depan. Buatkan fungsinya.", StoryEN: sp("Mandor pabrik butuh sistem untuk memantau produksi harian.\n\nPara peramal menggunakan proyeksi bilangan fibonacci untuk menaksir angka bulan depan. Buatkan fungsinya."),
			TaskID: "Buat fungsi `Fibonacci(n int) int` mereturn angka ke-n (0-indexed). Cetak n=6.", TaskEN: sp("Buat fungsi `Fibonacci(n int) int` mereturn angka ke-n (0-indexed). Cetak n=6."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: Fibonacci\n\nfunc main() {\n    fmt.Println(Fibonacci(6))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc Fibonacci(n int) int {\n    if n <= 1 { return n }\n    a, b := 0, 1\n    for i := 2; i <= n; i++ {\n        a, b = b, a+b\n    }\n    return b\n}\nfunc main() {\n    fmt.Println(Fibonacci(6))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "8\n"}]`),
			ExpectedOutput: j(`"8\n"`),
		},
		{ID: challengeUUID(141), Slug: "kargo-sum-141", Language: "golang", Difficulty: "medium", XPReward: 30, OrderIndex: 141,
			TitleID: "Ekspedisi Kilat: Total Nominal", TitleEN: sp("Ekspedisi Kilat: Total Nominal"),
			StoryID: "Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nTolong buatkan program untuk menghitung total semua angka di dalam list.", StoryEN: sp("Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nTolong buatkan program untuk menghitung total semua angka di dalam list."),
			TaskID: "Buat fungsi `HitungTotal(data []int) int` yang menjumlahkan semua elemen array.", TaskEN: sp("Buat fungsi `HitungTotal(data []int) int` yang menjumlahkan semua elemen array."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: buat fungsi HitungTotal\n\nfunc main() {\n    fmt.Println(HitungTotal([]int{10, 20, 30}))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc HitungTotal(data []int) int {\n    total := 0\n    for _, v := range data { total += v }\n    return total\n}\nfunc main() {\n    fmt.Println(HitungTotal([]int{10, 20, 30}))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "30\n"}]`),
			ExpectedOutput: j(`"30\n"`),
		},
		{ID: challengeUUID(142), Slug: "kargo-max-142", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 142,
			TitleID: "Ekspedisi Kilat: Nilai Tertinggi", TitleEN: sp("Ekspedisi Kilat: Nilai Tertinggi"),
			StoryID: "Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nKita butuh mengetahui angka paling besar di dalam kumpulan data untuk laporan akhir.", StoryEN: sp("Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nKita butuh mengetahui angka paling besar di dalam kumpulan data untuk laporan akhir."),
			TaskID: "Buat fungsi `CariMax(data []int) int` yang mengembalikan elemen terbesar awal. Jika kosong return 0.", TaskEN: sp("Buat fungsi `CariMax(data []int) int` yang mengembalikan elemen terbesar awal. Jika kosong return 0."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: buat fungsi CariMax\n\nfunc main() {\n    fmt.Println(CariMax([]int{15, 45, 20}))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc CariMax(data []int) int {\n    if len(data) == 0 { return 0 }\n    max := data[0]\n    for _, v := range data {\n        if v > max { max = v }\n    }\n    return max\n}\nfunc main() {\n    fmt.Println(CariMax([]int{15, 45, 20}))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "45\n"}]`),
			ExpectedOutput: j(`"45\n"`),
		},
		{ID: challengeUUID(143), Slug: "kargo-filter-143", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 143,
			TitleID: "Ekspedisi Kilat: Saring Data Lebih Dari 50", TitleEN: sp("Ekspedisi Kilat: Saring Data Lebih Dari 50"),
			StoryID: "Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nBanyak data sampah atau nilai kecil. Saring angka yang di atas atau sama dengan 50.", StoryEN: sp("Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nBanyak data sampah atau nilai kecil. Saring angka yang di atas atau sama dengan 50."),
			TaskID: "Buat fungsi `SaringData(data []int) []int`. Cetak hasilnya (tanpa bracket format standard agar mudah). Return array baru.", TaskEN: sp("Buat fungsi `SaringData(data []int) []int`. Cetak hasilnya (tanpa bracket format standard agar mudah). Return array baru."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: buat fungsi SaringData\n\nfunc main() {\n    res := SaringData([]int{10, 50, 80, 20})\n    for _, v := range res { fmt.Println(v) }\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc SaringData(data []int) []int {\n    var res []int\n    for _, v := range data {\n        if v >= 50 { res = append(res, v) }\n    }\n    return res\n}\nfunc main() {\n    res := SaringData([]int{10, 50, 80, 20})\n    for _, v := range res { fmt.Println(v) }\n}"),
			TestCases: j(`[{"input": "", "expected_output": "50\n80\n"}]`),
			ExpectedOutput: j(`"50\n80\n"`),
		},
		{ID: challengeUUID(144), Slug: "kargo-avg-144", Language: "golang", Difficulty: "medium", XPReward: 30, OrderIndex: 144,
			TitleID: "Ekspedisi Kilat: Rata-Rata", TitleEN: sp("Ekspedisi Kilat: Rata-Rata"),
			StoryID: "Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nUntuk laporan statistik, tolong program perhitungan nilai rata-rata dari slice integer terlampir.", StoryEN: sp("Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nUntuk laporan statistik, tolong program perhitungan nilai rata-rata dari slice integer terlampir."),
			TaskID: "Buat fungsi `RataRata(data []int) float64`. Jika kosong, return 0.0.", TaskEN: sp("Buat fungsi `RataRata(data []int) float64`. Jika kosong, return 0.0."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: buat RataRata\n\nfunc main() {\n    fmt.Printf(\"%.1f\n\", RataRata([]int{10, 20, 30}))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc RataRata(data []int) float64 {\n    if len(data) == 0 { return 0.0 }\n    sum := 0\n    for _, v := range data { sum += v }\n    return float64(sum)/float64(len(data))\n}\nfunc main() {\n    fmt.Printf(\"%.1f\n\", RataRata([]int{10, 20, 30}))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "20.0\n"}]`),
			ExpectedOutput: j(`"20.0\n"`),
		},
		{ID: challengeUUID(145), Slug: "kargo-count-145", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 145,
			TitleID: "Ekspedisi Kilat: Frekuensi Kategori", TitleEN: sp("Ekspedisi Kilat: Frekuensi Kategori"),
			StoryID: "Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nKami ingin tahu seberapa banyak setiap kategori atau kode muncul di sistem. Buatkan program penghitung frekuensi string.", StoryEN: sp("Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nKami ingin tahu seberapa banyak setiap kategori atau kode muncul di sistem. Buatkan program penghitung frekuensi string."),
			TaskID: "Buat `HitungFrekuensi(data []string) map[string]int`. Cetak A lalu B (hardcode print map[A] dan map[B]).", TaskEN: sp("Buat `HitungFrekuensi(data []string) map[string]int`. Cetak A lalu B (hardcode print map[A] dan map[B])."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: HitungFrekuensi\n\nfunc main() {\n    m := HitungFrekuensi([]string{\"A\", \"B\", \"A\"})\n    fmt.Println(m[\"A\"])\n    fmt.Println(m[\"B\"])\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc HitungFrekuensi(data []string) map[string]int {\n    m := make(map[string]int)\n    for _, v := range data { m[v]++ }\n    return m\n}\nfunc main() {\n    m := HitungFrekuensi([]string{\"A\", \"B\", \"A\"})\n    fmt.Println(m[\"A\"])\n    fmt.Println(m[\"B\"])\n}"),
			TestCases: j(`[{"input": "", "expected_output": "2\n1\n"}]`),
			ExpectedOutput: j(`"2\n1\n"`),
		},
		{ID: challengeUUID(146), Slug: "kargo-dedup-146", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 146,
			TitleID: "Ekspedisi Kilat: Hapus Duplikat", TitleEN: sp("Ekspedisi Kilat: Hapus Duplikat"),
			StoryID: "Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nData kotor ini banyak entri ganda. Buatkan fungsi untuk menghapus duplikat dari list string dengan tetap menjaga urutan awal kemunculan.", StoryEN: sp("Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nData kotor ini banyak entri ganda. Buatkan fungsi untuk menghapus duplikat dari list string dengan tetap menjaga urutan awal kemunculan."),
			TaskID: "Buat `HapusDuplikat(data []string) []string`. Cetak baris per baris.", TaskEN: sp("Buat `HapusDuplikat(data []string) []string`. Cetak baris per baris."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: HapusDuplikat\n\nfunc main() {\n    res := HapusDuplikat([]string{\"X\", \"Y\", \"X\", \"Z\"})\n    for _, v := range res { fmt.Println(v) }\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc HapusDuplikat(data []string) []string {\n    seen := make(map[string]bool)\n    var res []string\n    for _, v := range data {\n        if !seen[v] { res = append(res, v); seen[v] = true }\n    }\n    return res\n}\nfunc main() {\n    res := HapusDuplikat([]string{\"X\", \"Y\", \"X\", \"Z\"})\n    for _, v := range res { fmt.Println(v) }\n}"),
			TestCases: j(`[{"input": "", "expected_output": "X\nY\nZ\n"}]`),
			ExpectedOutput: j(`"X\nY\nZ\n"`),
		},
		{ID: challengeUUID(147), Slug: "kargo-palindrome-147", Language: "golang", Difficulty: "hard", XPReward: 60, OrderIndex: 147,
			TitleID: "Ekspedisi Kilat: Cek ID Palindrom", TitleEN: sp("Ekspedisi Kilat: Cek ID Palindrom"),
			StoryID: "Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nSebagai pengaman, ID entri tertentu harus bersifat palindrom (dibaca dari depan dan belakang sama). Toleransi huruf besar-kecil tidak diperlukan.", StoryEN: sp("Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nSebagai pengaman, ID entri tertentu harus bersifat palindrom (dibaca dari depan dan belakang sama). Toleransi huruf besar-kecil tidak diperlukan."),
			TaskID: "Buat fungsi `IsPalindrome(s string) bool`. Cetak true/false.", TaskEN: sp("Buat fungsi `IsPalindrome(s string) bool`. Cetak true/false."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: IsPalindrome\n\nfunc main() {\n    fmt.Println(IsPalindrome(\"malam\"))\n    fmt.Println(IsPalindrome(\"siang\"))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc IsPalindrome(s string) bool {\n    r := []rune(s)\n    for i, j := 0, len(r)-1; i < j; i, j = i+1, j-1 {\n        if r[i] != r[j] { return false }\n    }\n    return true\n}\nfunc main() {\n    fmt.Println(IsPalindrome(\"malam\"))\n    fmt.Println(IsPalindrome(\"siang\"))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "true\nfalse\n"}]`),
			ExpectedOutput: j(`"true\nfalse\n"`),
		},
		{ID: challengeUUID(148), Slug: "kargo-reverse-148", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 148,
			TitleID: "Ekspedisi Kilat: Balik Urutan", TitleEN: sp("Ekspedisi Kilat: Balik Urutan"),
			StoryID: "Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nKarena kesalahan migrasi database, urutan log terbalik. Buatkan fungsi yang membalikkan slice integer layaknya stack.", StoryEN: sp("Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nKarena kesalahan migrasi database, urutan log terbalik. Buatkan fungsi yang membalikkan slice integer layaknya stack."),
			TaskID: "Buat fungsi `BalikArray(arr []int) []int` yang mereturn array terbalik (reverse).", TaskEN: sp("Buat fungsi `BalikArray(arr []int) []int` yang mereturn array terbalik (reverse)."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: BalikArray\n\nfunc main() {\n    res := BalikArray([]int{1, 2, 3})\n    for _, v := range res { fmt.Println(v) }\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc BalikArray(arr []int) []int {\n    res := make([]int, len(arr))\n    copy(res, arr)\n    for i, j := 0, len(res)-1; i < j; i, j = i+1, j-1 {\n        res[i], res[j] = res[j], res[i]\n    }\n    return res\n}\nfunc main() {\n    res := BalikArray([]int{1, 2, 3})\n    for _, v := range res { fmt.Println(v) }\n}"),
			TestCases: j(`[{"input": "", "expected_output": "3\n2\n1\n"}]`),
			ExpectedOutput: j(`"3\n2\n1\n"`),
		},
		{ID: challengeUUID(149), Slug: "kargo-search-149", Language: "golang", Difficulty: "easy", XPReward: 15, OrderIndex: 149,
			TitleID: "Ekspedisi Kilat: Pencarian Biner Cepat", TitleEN: sp("Ekspedisi Kilat: Pencarian Biner Cepat"),
			StoryID: "Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nData sudah berurut tapi ukurannya besar. Coba gunakan algoritma pencarian biner untuk mencari target secara efisien.", StoryEN: sp("Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nData sudah berurut tapi ukurannya besar. Coba gunakan algoritma pencarian biner untuk mencari target secara efisien."),
			TaskID: "Buat `BinarySearch(arr []int, target int) int` mereturn index atau -1 jika tak ada. Cari 20 di [10,20,30,40].", TaskEN: sp("Buat `BinarySearch(arr []int, target int) int` mereturn index atau -1 jika tak ada. Cari 20 di [10,20,30,40]."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: BinarySearch\n\nfunc main() {\n    fmt.Println(BinarySearch([]int{10, 20, 30, 40}, 20))\n    fmt.Println(BinarySearch([]int{10, 20, 30, 40}, 50))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc BinarySearch(arr []int, target int) int {\n    l, r := 0, len(arr)-1\n    for l <= r {\n        m := l + (r-l)/2\n        if arr[m] == target { return m }\n        if arr[m] < target { l = m+1 } else { r = m-1 }\n    }\n    return -1\n}\nfunc main() {\n    fmt.Println(BinarySearch([]int{10, 20, 30, 40}, 20))\n    fmt.Println(BinarySearch([]int{10, 20, 30, 40}, 50))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "1\n-1\n"}]`),
			ExpectedOutput: j(`"1\n-1\n"`),
		},
		{ID: challengeUUID(150), Slug: "kargo-fibonacci-150", Language: "golang", Difficulty: "medium", XPReward: 30, OrderIndex: 150,
			TitleID: "Ekspedisi Kilat: Hitung Proyeksi Fibonacci", TitleEN: sp("Ekspedisi Kilat: Hitung Proyeksi Fibonacci"),
			StoryID: "Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nPara peramal menggunakan proyeksi bilangan fibonacci untuk menaksir angka bulan depan. Buatkan fungsinya.", StoryEN: sp("Perusahaan ekspedisi membutuhkan perhitungan logistik rute pengiriman.\n\nPara peramal menggunakan proyeksi bilangan fibonacci untuk menaksir angka bulan depan. Buatkan fungsinya."),
			TaskID: "Buat fungsi `Fibonacci(n int) int` mereturn angka ke-n (0-indexed). Cetak n=6.", TaskEN: sp("Buat fungsi `Fibonacci(n int) int` mereturn angka ke-n (0-indexed). Cetak n=6."),
			StarterCode: sp("package main\n\nimport \"fmt\"\n\n// TODO: Fibonacci\n\nfunc main() {\n    fmt.Println(Fibonacci(6))\n}"),
			SolutionCode: sp("package main\nimport \"fmt\"\nfunc Fibonacci(n int) int {\n    if n <= 1 { return n }\n    a, b := 0, 1\n    for i := 2; i <= n; i++ {\n        a, b = b, a+b\n    }\n    return b\n}\nfunc main() {\n    fmt.Println(Fibonacci(6))\n}"),
			TestCases: j(`[{"input": "", "expected_output": "8\n"}]`),
			ExpectedOutput: j(`"8\n"`),
		},
	}
	for i := range challenges {
		upsert(db, &challenges[i], challenges[i].Slug)
	}
}
