package main

import (
	"github.com/arulkarim/ngodingyuk-server/internal/domain"
	"gorm.io/gorm"
)

func seedSQLBeginnerQuizzes(db *gorm.DB) {
	quizzes := []domain.LessonQuiz{
		// --- Lesson 1: Pengenalan (2 quizzes) ---
		{
			ID:            quizUUID(4, 1, 1),
			LessonID:      lessonUUID(4, 1),
			CorrectIndex:  1,
			OrderIndex:    1,
			XPReward:      5,
			QuestionID:    "Apa kepanjangan dari SQL?",
			QuestionEN:    sp("What does SQL stand for?"),
			OptionsID:     j([]string{"Strong Question Language", "Structured Query Language", "Structured Quick Language", "Simple Query Logic"}),
			OptionsEN:     j([]string{"Strong Question Language", "Structured Query Language", "Structured Quick Language", "Simple Query Logic"}),
			ExplanationID: sp("SQL adalah singkatan dari Structured Query Language (Bahasa Kueri Terstruktur)."),
			ExplanationEN: sp("SQL stands for Structured Query Language."),
		},
		{
			ID:            quizUUID(4, 1, 2),
			LessonID:      lessonUUID(4, 1),
			CorrectIndex:  0,
			OrderIndex:    2,
			XPReward:      5,
			QuestionID:    "Apa fungsi utama dari database?",
			QuestionEN:    sp("What is the primary function of a database?"),
			OptionsID:     j([]string{"Menyimpan dan mengelola informasi secara tertata", "Menghapus virus dari komputer", "Mengedit video secara online", "Membuat halaman web interaktif"}),
			OptionsEN:     j([]string{"To store and manage information systematically", "To remove viruses from computers", "To edit videos online", "To create interactive web pages"}),
			ExplanationID: sp("Database berfungsi sebagai tempat penyimpanan data relasional yang besar agar dapat dikelola dan dicari kembali dengan mudah."),
			ExplanationEN: sp("A database serves as a storage system for large amounts of structured data for easy management and retrieval."),
		},

		// --- Lesson 2: Struktur Tabel (1 quiz) ---
		{
			ID:            quizUUID(4, 2, 1),
			LessonID:      lessonUUID(4, 2),
			CorrectIndex:  2,
			OrderIndex:    1,
			XPReward:      5,
			QuestionID:    "Bagian tabel apakah yang merepresentasikan suatu entitas data utuh (misal: data 1 orang Budi secara keseluruhan)?",
			QuestionEN:    sp("Which part of a table represents a complete single entity (e.g., all data for one person named Budi)?"),
			OptionsID:     j([]string{"Kolom (Column)", "Bidang (Field)", "Baris (Row / Record)", "Sel (Cell)"}),
			OptionsEN:     j([]string{"Column", "Field", "Row / Record", "Cell"}),
			ExplanationID: sp("Baris (Row / Record) adalah satu kesatuan entitas data (seperti nama, umur, dan negara Budi yang direkam secara menyamping)."),
			ExplanationEN: sp("A Row (Record) represents one entire horizontal entity comprising associated multi-column values."),
		},

		// --- Lesson 3: SELECT Dasar (2 quizzes) ---
		{
			ID:            quizUUID(4, 3, 1),
			LessonID:      lessonUUID(4, 3),
			CorrectIndex:  3,
			OrderIndex:    1,
			XPReward:      5,
			QuestionID:    "Perintah apa yang dipakai untuk MAJU/MEMBACA data dari database?",
			QuestionEN:    sp("Which command is designated to READ/RETRIEVE data out from the database?"),
			OptionsID:     j([]string{"GET", "OPEN", "EXTRACT", "SELECT"}),
			OptionsEN:     j([]string{"GET", "OPEN", "EXTRACT", "SELECT"}),
			ExplanationID: sp("Secara absolut di RDBMS standar, SELECT adalah kata kunci membaca data."),
			ExplanationEN: sp("SELECT is fundamentally the absolute keyword across standard RDBMS for querying."),
		},
		{
			ID:            quizUUID(4, 3, 2),
			LessonID:      lessonUUID(4, 3),
			CorrectIndex:  0,
			OrderIndex:    2,
			XPReward:      5,
			QuestionID:    "Tanda apakah yang digunakan untuk mengambil 'semua/seluruh kolom'?",
			QuestionEN:    sp("Which symbol represents 'all columns / everything'?"),
			OptionsID:     j([]string{"* (Bintang)", "& (Dan)", "% (Persen)", "# (Pagar)"}),
			OptionsEN:     j([]string{"* (Asterisk)", "& (Ampersand)", "% (Percent)", "# (Hash)"}),
			ExplanationID: sp("SELECT * berarti ambil semua kolom."),
			ExplanationEN: sp("SELECT * fetches every single column defined."),
		},

		// --- Lesson 4: Memilih Kolom Spesifik (1 quiz) ---
		{
			ID:            quizUUID(4, 4, 1),
			LessonID:      lessonUUID(4, 4),
			CorrectIndex:  1,
			OrderIndex:    1,
			XPReward:      5,
			QuestionID:    "Bagaimana cara mengambil HANYA kolom 'name' dan 'age' dari tabel 'users'?",
			QuestionEN:    sp("How effectively do you fetch ONLY the 'name' and 'age' columns from the 'users' table?"),
			OptionsID:     j([]string{"SELECT name age FROM users;", "SELECT name, age FROM users;", "SELECT * name, age FROM users;", "GET name AND age FROM users;"}),
			OptionsEN:     j([]string{"SELECT name age FROM users;", "SELECT name, age FROM users;", "SELECT * name, age FROM users;", "GET name AND age FROM users;"}),
			ExplanationID: sp("Gunakan tanda koma (,) untuk memisahkan setiap kolom yang ingin disebutkan."),
			ExplanationEN: sp("Use a comma (,) as the column separator discriminator."),
		},

		// --- Lesson 5: Menyaring dengan WHERE (2 quizzes) ---
		{
			ID:            quizUUID(4, 5, 1),
			LessonID:      lessonUUID(4, 5),
			CorrectIndex:  2,
			OrderIndex:    1,
			XPReward:      5,
			QuestionID:    "Klausul apa yang digunakan untuk mengatur kondisi seleksi baris (filtering)?",
			QuestionEN:    sp("Which clause restricts/filters rows returned depending on a specified condition?"),
			OptionsID:     j([]string{"FILTER", "FIND", "WHERE", "CHOOSE"}),
			OptionsEN:     j([]string{"FILTER", "FIND", "WHERE", "CHOOSE"}),
			ExplanationID: sp("Klausul WHERE digunakan untuk filterisasi kondisional dalam sebuah query."),
			ExplanationEN: sp("The WHERE clause is applied to filter datasets conditionally."),
		},
		{
			ID:            quizUUID(4, 5, 2),
			LessonID:      lessonUUID(4, 5),
			CorrectIndex:  0,
			OrderIndex:    2,
			XPReward:      5,
			QuestionID:    "Sintaks SQL yang benar untuk mencetak produk yang memiliki nama 'Buku'?",
			QuestionEN:    sp("Which SQL fragment correctly finds the records where the product name equals 'Buku'?"),
			OptionsID:     j([]string{"SELECT * FROM products WHERE name = 'Buku';", "SELECT products WHERE name = 'Buku';", "SELECT * FROM products IF name = 'Buku';", "SELECT name FROM products SEARCH 'Buku';"}),
			OptionsEN:     j([]string{"SELECT * FROM products WHERE name = 'Buku';", "SELECT products WHERE name = 'Buku';", "SELECT * FROM products IF name = 'Buku';", "SELECT name FROM products SEARCH 'Buku';"}),
			ExplanationID: sp("Format string / teks harus diapit dengan tanda petik tunggal '...' dan perbandinganya ditaruh setelah WHERE."),
			ExplanationEN: sp("A literal string must be encapsulated utilizing single quotes '...' inside a WHERE equation."),
		},

		// --- Lesson 6: Operator Perbandingan (2 quizzes) ---
		{
			ID:            quizUUID(4, 6, 1),
			LessonID:      lessonUUID(4, 6),
			CorrectIndex:  3,
			OrderIndex:    1,
			XPReward:      5,
			QuestionID:    "Operator manakah yang mewakili makna 'TIDAK SAMA DENGAN'?",
			QuestionEN:    sp("Which comparative operator stands denoting 'NOT EQUAL TO'?"),
			OptionsID:     j([]string{"==", "><", "!!", "<> / !="}),
			OptionsEN:     j([]string{"==", "><", "!!", "<> / !="}),
			ExplanationID: sp("Dalam SQL diizinkan pemakaian <> atau != sebagai negasi ekuivalensi (tidak sama dengan)."),
			ExplanationEN: sp("Standard SQL engines support both the <> operator and commonly != as explicit inequality comparators."),
		},
		{
			ID:            quizUUID(4, 6, 2),
			LessonID:      lessonUUID(4, 6),
			CorrectIndex:  0,
			OrderIndex:    2,
			XPReward:      5,
			QuestionID:    "Query yang benar untuk menampilkan penduduk berusia LEBIH ATAU SAMA DENGAN 17 tahun?",
			QuestionEN:    sp("What query identifies population aged GREATER THAN OR EQUAL TO 17?"),
			OptionsID:     j([]string{"SELECT * FROM public WHERE age >= 17;", "SELECT * FROM public WHERE age => 17;", "SELECT * FROM public WHERE age > 17;", "SELECT * FROM public WHERE age =< 17;"}),
			OptionsEN:     j([]string{"SELECT * FROM public WHERE age >= 17;", "SELECT * FROM public WHERE age => 17;", "SELECT * FROM public WHERE age > 17;", "SELECT * FROM public WHERE age =< 17;"}),
			ExplanationID: sp("Kombinasi yang benar merujuk ke sintaks operator matematika asli: >= (lebih dari lalu sama dengan)."),
			ExplanationEN: sp("The combined characters universally translate functionally as >= (greater followed natively by equal)."),
		},

		// --- Lesson 7: Operator Logika (2 quizzes) ---
		{
			ID:            quizUUID(4, 7, 1),
			LessonID:      lessonUUID(4, 7),
			CorrectIndex:  1,
			OrderIndex:    1,
			XPReward:      5,
			QuestionID:    "Agar baris ditampilkan, operator logika manakah yang mensyaratkan SEMUA KONDISI harus bernilai BENAR?",
			QuestionEN:    sp("Which boolean connective mandates ALL CONJOINED CONDITIONS perfectly assert true equivalently?"),
			OptionsID:     j([]string{"OR", "AND", "NOT", "BOTH"}),
			OptionsEN:     j([]string{"OR", "AND", "NOT", "BOTH"}),
			ExplanationID: sp("AND mengikat seluruh persyaratan menjadi satu paket mutlak wajib terpenuhi seluruhnya."),
			ExplanationEN: sp("AND fundamentally chains requisites obligating universal mutual satisfaction concurrently."),
		},
		{
			ID:            quizUUID(4, 7, 2),
			LessonID:      lessonUUID(4, 7),
			CorrectIndex:  0,
			OrderIndex:    2,
			XPReward:      5,
			QuestionID:    "Apa hasil dari klausul WHERE color = 'Red' OR color = 'Blue'?",
			QuestionEN:    sp("What does traversing WHERE color = 'Red' OR color = 'Blue' output ultimately?"),
			OptionsID:     j([]string{"Menampilkan data yang warnanya Merah, ataupun yang warnanya Biru", "Hanya menampilkan data yang warnanya Merah sekaligus Biru di kolom yang sama", "Tidak menampilkan keduanya", "Akan memunculkan Error"}),
			OptionsEN:     j([]string{"Outputs rows evaluated containing either purely Red or purely Blue independently", "Displays records exhibiting intertwined Red-Blue traits natively inside the lone respective cell string", "Presents neither effectively", "Returns fatal syntax Execution Exception Error"}),
			ExplanationID: sp("OR mengabulkan kecocokan asalkan minimal salah satu prasyaratnya berstatus benar."),
			ExplanationEN: sp("OR grants validation legitimacy exclusively requiring sole minimum isolation criterion fulfillment."),
		},

		// --- Lesson 8: IN dan BETWEEN (2 quizzes) ---
		{
			ID:            quizUUID(4, 8, 1),
			LessonID:      lessonUUID(4, 8),
			CorrectIndex:  3,
			OrderIndex:    1,
			XPReward:      5,
			QuestionID:    "Mana penggunaan operator IN yang paling tepat?",
			QuestionEN:    sp("Which constitutes robust functional appliance translating syntactic IN architecture?"),
			OptionsID:     j([]string{"WHERE age IN 20, 30;", "WHERE name IN 'Budi' AND 'Ani';", "WHERE IN (country = 'ID');", "WHERE country IN ('ID', 'US', 'JP');"}),
			OptionsEN:     j([]string{"WHERE age IN 20, 30;", "WHERE name IN 'Budi' AND 'Ani';", "WHERE IN (country = 'ID');", "WHERE country IN ('ID', 'US', 'JP');"}),
			ExplanationID: sp("Operator IN dibungkus dengan tanda kurung ( ) dan tiap nilainya dipisahkan tanda koma tanpa perulangan kolom/variabel utamanya."),
			ExplanationEN: sp("IN parameters wrap collectively via parenthesis enclosures ( ) segregating localized discrete entities simply appending commas."),
		},
		{
			ID:            quizUUID(4, 8, 2),
			LessonID:      lessonUUID(4, 8),
			CorrectIndex:  2,
			OrderIndex:    2,
			XPReward:      5,
			QuestionID:    "Pada WHERE price BETWEEN 10 AND 50, apakah angka 10 dan 50 akan diikutsertakan (inklusif)?",
			QuestionEN:    sp("If specifying WHERE price BETWEEN 10 AND 50, do native boundaries mathematically include exactly 10 and exactly 50 specifically?"),
			OptionsID:     j([]string{"Hanya 50 yang ikut, 10 tidak", "Tidak, hanya mengambil angka 11 sampai 49", "Ya, kedua batasan (10 dan 50) ikutserta (inklusif)", "Hanya 10 yang ikut, 50 tidak"}),
			OptionsEN:     j([]string{"Includes solely the upper trailing 50, ignoring 10", "Excludes entirely bound endpoints effectively filtering essentially exclusively 11 through 49 inclusive", "Absolutely yes, comprehensive endpoints identically evaluate inclusively", "Traps strictly initial baseline 10, refusing 50"}),
			ExplanationID: sp("Fungsi BETWEEN selalu bersifat Inklusif; angka pangkal awal serta angka pucuk akhiran akan terhitung sah."),
			ExplanationEN: sp("BETWEEN evaluates inclusive logically; beginning alongside termination numbers evaluate safely legitimately matching conditions naturally."),
		},

		// --- Lesson 9: LIKE (2 quizzes) ---
		{
			ID:            quizUUID(4, 9, 1),
			LessonID:      lessonUUID(4, 9),
			CorrectIndex:  1,
			OrderIndex:    1,
			XPReward:      5,
			QuestionID:    "Tanda karakter yang lazim dipakai untuk memperluas pencarian 'wildcard huruf apapun' dalam LIKE adalah?",
			QuestionEN:    sp("The standard wildcard operator symbol enabling 'matches any sequence string combinations' accompanied near LIKE behaves as?"),
			OptionsID:     j([]string{"*", "%", "$", "?"}),
			OptionsEN:     j([]string{"*", "%", "$", "?"}),
			ExplanationID: sp("Bintang dipakai untuk SELECT (semua kolom). Untuk mencari pola substring teks di LIKE, SQL menggunakan tanda persentase (%)."),
			ExplanationEN: sp("While Astersik returns column subsets initially, text matching algorithm dynamically embraces percentage (%) symbolizing zero or numerous succeeding wildcard characters."),
		},
		{
			ID:            quizUUID(4, 9, 2),
			LessonID:      lessonUUID(4, 9),
			CorrectIndex:  0,
			OrderIndex:    2,
			XPReward:      5,
			QuestionID:    "Jika ingin mencari pendaftar yang namanya berakhiran 'son' (misal: Jason, Edison), pola LIKE manakah yang tepat?",
			QuestionEN:    sp("To effectively extract applicant identities terminating universally precisely ending suffix format 'son' (like: Jason, Edison), which LIKE pattern validates correctly?"),
			OptionsID:     j([]string{"LIKE '%son'", "LIKE 'son%'", "LIKE '%son%'", "LIKE 's%n'"}),
			OptionsEN:     j([]string{"LIKE '%son'", "LIKE 'son%'", "LIKE '%son%'", "LIKE 's%n'"}),
			ExplanationID: sp("Persen di depan '%son' melambangkan awalan terserah apapun karakternya, asalkan ujung penutupnya bertuliskan 'son' persis mutlak."),
			ExplanationEN: sp("Preceding `%` enables unconstrained prefixes dynamically, firmly strictly locking termination suffix 'son' accurately seamlessly at tail positions exclusively."),
		},

		// --- Lesson 10: ORDER BY (2 quizzes) ---
		{
			ID:            quizUUID(4, 10, 1),
			LessonID:      lessonUUID(4, 10),
			CorrectIndex:  1,
			OrderIndex:    1,
			XPReward:      5,
			QuestionID:    "Apa kepanjangan dari DESC pada fungsional ORDER BY?",
			QuestionEN:    sp("What explicitly operates identically matching logical mapping underlying DESC keywords near ORDER BY sorting contexts?"),
			OptionsID:     j([]string{"Describe", "Descending", "Decrease", "Disconnect"}),
			OptionsEN:     j([]string{"Describe", "Descending", "Decrease", "Disconnect"}),
			ExplanationID: sp("DESC mewakili Descending (menurun, dari yang paling besar ke paling kecil, atau membalik alfabet dari huruf akhir Z ke A)."),
			ExplanationEN: sp("DESC denotes mathematically descending (large toward diminished sequences logically translating top-heavy downwards configurations effectively Z returning backwards A progressively)."),
		},
		{
			ID:            quizUUID(4, 10, 2),
			LessonID:      lessonUUID(4, 10),
			CorrectIndex:  3,
			OrderIndex:    2,
			XPReward:      5,
			QuestionID:    "Jika kamu sekedar menulis 'ORDER BY nama', bagaimana SQL mesin mengurutkannya secara default/bawaan asali?",
			QuestionEN:    sp("Writing superficially merely 'ORDER BY name' forces sorting processes evaluating explicitly under what built-in algorithmic defaults routinely implicitly automatically?"),
			OptionsID:     j([]string{"Diurutkan mendadak secara asalan random per detiknya", "Diurutkan Descending karena dirasa sistem lebih bagus rapi", "Tidak akan diurutkan karena sintaksnya error butuh ASC/DESC konstan mutlak", "Secara otomatis default-nya diinterpretasikan menjadi menaik ASC (Ascending)"}),
			OptionsEN:     j([]string{"Presents spontaneously indiscriminately rendering chaotic unpredictable iterations sequentially", "Enforces rigid descending automatically sensing aesthetically improved display preferences internally", "Raises fatal exceptions refusing operational compilations demanding strict explicit suffix ASC/DESC notation", "Assimilates autonomously evaluating default parameters translating exclusively upward ascending ASC directions systematically"}),
			ExplanationID: sp("RDBMS mempermudah tugasmu. Saat mode ASC atau DESC kosong sengaja tak ditulis, SQL mutlak selalu mematok jalurnya secara menaik (Ascending)."),
			ExplanationEN: sp("Omission seamlessly cascades engine directives dynamically resorting systematically toward baseline chronological/numerical upward (Ascending ASC) behavior defaults intrinsically."),
		},

		// --- Lesson 11: LIMIT (2 quizzes) ---
		{
			ID:            quizUUID(4, 11, 1),
			LessonID:      lessonUUID(4, 11),
			CorrectIndex:  0,
			OrderIndex:    1,
			XPReward:      5,
			QuestionID:    "Berapa banyak baris data yang muncul saat mengeksekusi sintaks berikut: SELECT * FROM items LIMIT 3?",
			QuestionEN:    sp("How many row extractions populate fundamentally succeeding successful queries invoking exactly: SELECT * FROM items LIMIT 3?"),
			OptionsID:     j([]string{"Maksimal 3 baris teratas saja", "Baris pada nomer index 3 saja", "Pencarian melimit data yang kolomnya memiliki nilai nomor 3", "Sebanyak kelipatan 3 baris"}),
			OptionsEN:     j([]string{"Restricts rendering maximally presenting exclusively uppermost 3 rows primarily", "Singles out isolation specifically row absolute logical index mapped exactly 3", "Evaluates parameters conditionally locking cells holding digit 3 intrinsically strictly", "Multiples returned yields dynamically chunking groupings threes procedurally sequentially"}),
			ExplanationID: sp("LIMIT berfungsi murni spesifik mengerucutkan pembatasan maksimal kuota jumlah baris keluar menjadi sekadar N angka tersebut saja (yakni tiga data)."),
			ExplanationEN: sp("LIMIT unequivocally truncates rendering volumes specifically curtailing maximal visible output population matching specified integer N directly straightforward purely."),
		},
		{
			ID:            quizUUID(4, 11, 2),
			LessonID:      lessonUUID(4, 11),
			CorrectIndex:  2,
			OrderIndex:    2,
			XPReward:      5,
			QuestionID:    "Di manakah posisi ideal peletakan kata LIMIT dalam barisan logika struktur piramida sintaks SQL umum?",
			QuestionEN:    sp("Locate grammatically structurally optimal foundational absolute positioning logically enforcing LIMIT occurrences broadly conventionally?"),
			OptionsID:     j([]string{"Paling depan tepat setelah SELECT selalu awalan konstan", "Di antara FROM dan WHERE secara terselip apik rapi", "Paling belakang/akhir dari perumusan deklarasi sebuah query utuh", "Terserah karena SQL sangat pintar otomatis merajut puzzle mandiri cerdas"}),
			OptionsEN:     j([]string{"Asserted immediately front-loaded sequentially preceding virtually initially permanently exclusively absolute", "Threaded deeply internal between foundational FROM combining logically WHERE statements implicitly optimally", "Positioned firmly cementing closure strictly capping entirely finalized query architectures terminal sequentially", "Interchangeable arbitrary placements natively automatically assimilated dynamically utilizing intelligent parsing routinely"}),
			ExplanationID: sp("Secara fundamental piramida sintaks eksekusi database reguler aslinya (LIMIT) diletakkan absolut tepat paling bawah akhir sendiri (PostgreSQL, MySQL, dsb)."),
			ExplanationEN: sp("Dialects predominantly enforce structural trailing positions universally dictating termination boundaries closing fully written query bodies fundamentally dependably safely."),
		},

		// --- Lesson 12: NULL (2 quizzes) ---
		{
			ID:            quizUUID(4, 12, 1),
			LessonID:      lessonUUID(4, 12),
			CorrectIndex:  0,
			OrderIndex:    1,
			XPReward:      5,
			QuestionID:    "Apakah arti dari NULL dalam pemahaman database relasional teknis sesungguhnya murni sejati?",
			QuestionEN:    sp("Interpret explicitly absolute technical realities inherently conceptualizing pure relational database NULL phenomenons definitively properly realistically?"),
			OptionsID:     j([]string{"Kekosongan murni absolut mutlak tanpa satupun entitas karakter tak berwujud state (Unknown State)", "Sama dengan bilangan cacah matematika yakni nilainya murni Angka Nol 0 pas", "Sama persis dengan Spasi ' ' atau kutip ganda/string kosong utuh tidak ada tulisan memanjang", "Sebuah pertanda Error yang mewajibkan developer segera membuang dan mereparasi menghapusnya fatal"}),
			OptionsEN:     j([]string{"Represents sheer pure absolute conceptual unknown void states completely unmapped categorically immaterial implicitly missing completely intrinsically", "Evaluates mathematically purely reflecting standard baseline zero digits strictly 0 definitively identical identically absolutely", "Corresponds interchangeably mapped string allocations effectively simulating transparent spaces equivalently completely nullified explicitly blank strings logically", "Denotes engine architectural severe faulting conditions fundamentally permanently enforcing developer intervention deleting anomalies consistently invariably"}),
			ExplanationID: sp("Karakteristik hakiki fundamental NULL aslinya mewujudkan absennya/ketidakberadaanya data secara entitas mutlak. Dia Bukanlah 0. Dia bukan tulisan spasi ''), dia adalah Kekosongan belaka."),
			ExplanationEN: sp("Fundamental intrinsic reality definitively maps conceptual NULL values absolutely modeling non-existence completely explicitly differentiating distinctively apart zero integers or blank strings simultaneously independently entirely unknown strictly missing completely fundamentally."),
		},
		{
			ID:            quizUUID(4, 12, 2),
			LessonID:      lessonUUID(4, 12),
			CorrectIndex:  1,
			OrderIndex:    2,
			XPReward:      5,
			QuestionID:    "Bagaimana tata cara sintaks pengecekan mendeteksi NULL termudah, tersahih, dan mutlak tidak keliru pada klausul WHERE ?",
			QuestionEN:    sp("Identifies effectively grammatical valid robust checks verifying detecting underlying absolutely NULL states accurately functionally faultless executing inherently properly WHERE integrations sequentially realistically?"),
			OptionsID:     j([]string{"WHERE email = NULL;", "WHERE email IS NULL;", "WHERE email == NULL;", "WHERE email LIKE 'NULL';"}),
			OptionsEN:     j([]string{"WHERE email = NULL;", "WHERE email IS NULL;", "WHERE email == NULL;", "WHERE email LIKE 'NULL';"}),
			ExplanationID: sp("Aturan abadi SQL: mendeteksi ke-null-an DILARANG memakai tanda matematika '=', mesin bakal buta tak memahami. Kewajibannya harus dan musti diganti perlakuan khususnya yaitu idiom 'IS NULL'."),
			ExplanationEN: sp("Core deterministic engine standards prohibit natively mathematical evaluations equality explicitly employing '=' equations failing utterly processing comprehensively null voids directly. Engine demands mandated explicit 'IS NULL' strictly explicitly implicitly accurately uniformly definitively naturally safely unconditionally uniquely unequivocally valid purely."),
		},

		// --- Lesson 13: AS (Column Aliases) (2 quizzes) ---
		{
			ID:            quizUUID(4, 13, 1),
			LessonID:      lessonUUID(4, 13),
			CorrectIndex:  2,
			OrderIndex:    1,
			XPReward:      5,
			QuestionID:    "Klausul apa yang bertugas semata-mata 'memberikan penamaan identitas temporer ganda / samaran' pada baris kolom header agar tampil cantik dilihat?",
			QuestionEN:    sp("Which explicitly functional grammatical clause effectively arbitrarily maps substitute alias identities masking native database structural references projecting cleaner prettier visual presentations temporarily rendering properly primarily effectively reliably practically immediately directly appropriately visually completely securely functionally realistically simply precisely naturally?"),
			OptionsID:     j([]string{"RENAME", "CHANGE", "AS", "ALTER"}),
			OptionsEN:     j([]string{"RENAME", "CHANGE", "AS", "ALTER"}),
			ExplanationID: sp("Secara etimologi gramatika AS singkatan spontan alias, merekonstruksi wujud label tampilan sekejap saat read data saja tanpa membongkar meja relasional aslinya selamanya."),
			ExplanationEN: sp("Aliasing intrinsically dynamically utilizes AS purely projecting aesthetic front-layer renaming presentation facades transiently masking structural architectures harmlessly non-destructively accurately simply predictably quickly inherently automatically flawlessly directly natively completely comprehensively strictly perfectly safely primarily."),
		},
		{
			ID:            quizUUID(4, 13, 2),
			LessonID:      lessonUUID(4, 13),
			CorrectIndex:  0,
			OrderIndex:    2,
			XPReward:      5,
			QuestionID:    "Saat menggunakan AS tetapi menamai dengan 2 kata terpisah berjarak spasi, apa yang wajib kamu sisipkan ?",
			QuestionEN:    sp("Executing effectively aliasing utilizing combinations integrating strictly distinctly separated vocabulary inherently partitioned implicitly involving pure spacing naturally demands additionally implementing explicitly enforcing specifically accurately safely flawlessly functionally reliably practically dependably properly successfully intuitively essentially automatically effectively practically thoroughly primarily?"),
			OptionsID:     j([]string{"Mengapitnya menggunakan Tanda Kutip 'nama panjang ini' atau Ganda \"tiga kata itu\" ", "Menggunalan underscore paksa selalu selamanya otomatis menyatu panjang tiada jeda ", "Akan gagal karena tidak boleh ganti nama yang lebih dari satu kata baku sejati utuh murni murni ", "Diberikan tanda seru penutup kalimat mutlak mendalam "}),
			OptionsEN:     j([]string{"Encompassing encapsulation mandating distinctly explicitly quotation marks 'my super string' encapsulating entirely securely", "Forcefully rejecting spaces permanently defaulting invariably automatic underscore interpolations silently stringently strictly", "Fatal rejections immediately enforcing single explicit unbreakable dictionary pure unified rigid keywords relentlessly absolutely primarily consistently seamlessly systematically safely", "Postfixing exclamation marks dynamically enforcing linguistic declarative authority comprehensively fully cleanly uniformly"}),
			ExplanationID: sp("Apabila label alias yang di-request berupa multi kata, WAJIBHUKUMNYA di-wrap / dikurung memeluk petik di sekujur katanya agar sintaks terlepas dari kecelakaan pembantaian error interpreter mematikan."),
			ExplanationEN: sp("Any alias integrating naturally explicitly whitespace essentially completely demands mandatory comprehensive encapsulation utilizing explicit quotes isolating safely entirely shielding compilation errors intuitively efficiently properly explicitly uniformly fully securely directly completely accurately seamlessly practically definitively optimally intrinsically accurately fundamentally optimally accurately rigorously effectively perfectly dynamically successfully."),
		},

		// --- Lesson 14: Pengenalan Agregasi (1 quiz) ---
		{
			ID:            quizUUID(4, 14, 1),
			LessonID:      lessonUUID(4, 14),
			CorrectIndex:  1,
			OrderIndex:    1,
			XPReward:      5,
			QuestionID:    "Manakah di bawah ini yang BUKAN merupakan bagian murni asli dari fungsi fundamental agregat matematis SQL sejati?",
			QuestionEN:    sp("Identify explicitly distinct mathematical function fundamentally effectively structurally totally absent entirely outside standard absolute core native aggregations unconditionally intrinsically accurately natively comprehensively definitively natively uniquely clearly fundamentally effectively inherently objectively correctly completely realistically purely primarily dynamically optimally objectively exactly specifically?"),
			OptionsID:     j([]string{"SUM()", "SUBTRACT()", "COUNT()", "AVG()"}),
			OptionsEN:     j([]string{"SUM()", "SUBTRACT()", "COUNT()", "AVG()"}),
			ExplanationID: sp("SUBTRACT() bukanlah Fungsi Agregat (Aggregate). Agregat aslinya cuma mengkalkulasi kumpulan utuh menjadi ringkasan (misal MIN, MAX, SUM, AVG, COUNT), pengurangan tak masuk di ranah merangkum himpunan agregasi default SQL tulen sesungguhnya sejati mutlak pasti."),
			ExplanationEN: sp("Native aggregates summarize comprehensive groupings rendering statistical summaries explicitly. Mathematical deductions subtracting entities lack native grouping capabilities structurally absent entirely comprehensively rigorously definitely inherently implicitly naturally unequivocally effectively specifically definitively practically clearly intuitively completely uniquely perfectly explicitly properly efficiently flawlessly exclusively perfectly flawlessly natively optimally reliably perfectly simply reliably comprehensively securely purely reliably directly flawlessly correctly comprehensively explicitly comprehensively flawlessly completely properly safely fully directly rigorously perfectly naturally simply seamlessly optimally cleanly flawlessly accurately seamlessly unconditionally."),
		},

		// --- Lesson 15-17: COUNT, SUM, AVG, MIN, MAX (3 quizzes) ---
		{
			ID:            quizUUID(4, 15, 1),
			LessonID:      lessonUUID(4, 15),
			CorrectIndex:  3,
			OrderIndex:    1,
			XPReward:      5,
			QuestionID:    "Fungsi yang spesifik eksklusif bertugas mengevaluasi perhitungan TOTAL JUMLAH BARIS (bukan totalkan saldo isinya, tapi menghitung berapa banyak kemunculan datanya bertumpuk barinya panjang nya) murni adalah?",
			QuestionEN:    sp("Which natively intrinsically explicitly evaluates total cumulative volumes accounting purely strictly row counts precisely entirely effectively calculating quantities exclusively independently definitively implicitly purely cleanly definitively safely practically intuitively optimally successfully correctly distinctly completely accurately flawlessly structurally essentially flawlessly perfectly cleanly effectively practically naturally optimally explicitly accurately naturally automatically implicitly successfully cleanly?"),
			OptionsID:     j([]string{"MAX()", "SUM()", "AVG()", "COUNT()"}),
			OptionsEN:     j([]string{"MAX()", "SUM()", "AVG()", "COUNT()"}),
			ExplanationID: sp("Bedakan antara SUM (menjumlah nominal uang isinya), dengan COUNT (menghitung jumlah populasinya yang ikut berpartisipasi). COUNT khusus mendeteksi baris hadir!"),
			ExplanationEN: sp("Distinguish rigorously fundamentally strictly SUM aggregating numerical contents progressively adding sequentially. COUNT objectively identifies explicit row occurrence magnitudes cleanly precisely realistically properly cleanly flawlessly accurately predictably comprehensively optimally naturally specifically exclusively implicitly definitively perfectly inherently completely efficiently effectively completely perfectly effectively intelligently cleanly properly cleanly securely properly systematically cleanly strictly intuitively naturally explicitly fundamentally cleanly functionally optimally automatically strictly precisely unconditionally explicitly successfully correctly perfectly reliably correctly strictly flawlessly reliably completely purely optimally distinctly cleanly smoothly safely perfectly clearly."),
		},
		{
			ID:            quizUUID(4, 16, 1),
			LessonID:      lessonUUID(4, 16),
			CorrectIndex:  1,
			OrderIndex:    1,
			XPReward:      5,
			QuestionID:    "Fungsi manakah yang menopang pemrosesan matematika pencarian 'RATA-RATA' nilai raport siswa terhebat seantero sekolahan merangkum tuntas sempurna?",
			QuestionEN:    sp("Which aggregation rigorously natively intrinsically facilitates computing comprehensive explicit mathematical averages effectively definitively optimally inherently accurately properly systematically explicitly perfectly seamlessly cleanly efficiently precisely clearly automatically successfully correctly beautifully simply strictly reliably safely practically flawlessly functionally purely securely clearly ideally optimally?"),
			OptionsID:     j([]string{"TOTAL()", "AVG()", "MIN()", "RATA_RATA()"}),
			OptionsEN:     j([]string{"TOTAL()", "AVG()", "MIN()", "RATA_RATA()"}),
			ExplanationID: sp("Average disingkat lugas padat efisien gesit mantap AVG() mewakili penghitungan mencari tengah-tengah rentang statistik mean (Rata-rata)."),
			ExplanationEN: sp("AVG represents concisely functionally smoothly explicitly statistical means correctly calculating universally averaging arithmetic accurately fundamentally comprehensively seamlessly exactly correctly ideally exclusively implicitly comprehensively intelligently effectively effectively predictably correctly safely purely naturally flawlessly explicitly cleanly optimally explicitly optimally explicitly safely explicitly perfectly ideally naturally uniquely completely accurately cleanly efficiently clearly properly cleanly intuitively automatically flawlessly cleanly efficiently successfully effectively cleanly efficiently flawlessly cleanly effectively purely intuitively intuitively simply completely cleanly successfully strictly structurally specifically correctly automatically ideally optimally successfully intelligently brilliantly systematically comprehensively smoothly fundamentally implicitly explicitly elegantly rigorously definitively clearly optimally beautifully purely uniquely completely explicitly securely reliably flawlessly seamlessly securely absolutely purely accurately flawlessly strictly purely consistently exclusively consistently."),
		},
		{
			ID:            quizUUID(4, 17, 1),
			LessonID:      lessonUUID(4, 17),
			CorrectIndex:  0,
			OrderIndex:    1,
			XPReward:      5,
			QuestionID:    "Untuk mencari daftar Harga Paling MURAH (Paling Rendah / Kecil) sebuah Toko Kelontong, sintaks manakah yang mutlak dipergunakan paling praktis instan akurat super hemat efisien maksimal tajam sejati sempurna optimal otomatis lugas handal mumpuni cerdas tepat logis benar?",
			QuestionEN:    sp("Identifying rigorously absolutely explicitly lowest optimal minimal absolute figures essentially universally effectively functionally explicitly accurately clearly flawlessly practically simply securely exactly neatly optimally correctly systematically seamlessly reliably clearly naturally completely automatically effectively directly flawlessly perfectly cleanly rigorously gracefully purely smoothly beautifully safely fundamentally intelligently properly purely effortlessly accurately effectively cleanly dynamically safely properly precisely quickly cleanly efficiently essentially perfectly smoothly?"),
			OptionsID:     j([]string{"SELECT MIN(harga) FROM toko;", "SELECT MAX(harga) FROM toko;", "SELECT LOWER(harga) FROM toko;", "SELECT DOWN(harga) FROM toko;"}),
			OptionsEN:     j([]string{"SELECT MIN(harga) FROM toko;", "SELECT MAX(harga) FROM toko;", "SELECT LOWER(harga) FROM toko;", "SELECT DOWN(harga) FROM toko;"}),
			ExplanationID: sp("Jelas lugas padat terarah, MIN bertugas menggali mencari mendeteksi menyelidiki nilai yang bertengger di tahta paling minimalis terdasar terendah mutlak valid secara matematika logis absolut murni sejati selamanya secara konsisten elegan. Sangat akurat."),
			ExplanationEN: sp("MIN flawlessly accurately directly exclusively intelligently elegantly effectively computes extracts effectively lowest extreme boundaries optimally comprehensively natively securely cleanly accurately simply dependably correctly practically inherently consistently fundamentally implicitly unconditionally automatically perfectly implicitly intuitively flawlessly smoothly neatly purely predictably clearly natively brilliantly flawlessly intuitively distinctly definitively rigorously absolutely effortlessly cleanly brilliantly properly gracefully flawlessly effectively seamlessly cleanly predictably securely successfully rigorously smoothly intuitively inherently successfully rigorously efficiently effectively automatically accurately strictly directly fundamentally thoroughly automatically gracefully elegantly dependably efficiently gracefully elegantly reliably precisely correctly implicitly unconditionally gracefully reliably seamlessly implicitly effectively naturally elegantly exclusively safely predictably gracefully consistently flawlessly seamlessly neatly absolutely effectively distinctly properly unconditionally strictly cleanly cleanly essentially purely securely successfully automatically logically simply effectively strictly completely systematically natively effortlessly optimally precisely reliably flawlessly dynamically securely essentially efficiently implicitly efficiently completely successfully practically fully safely flawlessly smoothly brilliantly seamlessly intuitively effectively elegantly perfectly intelligently explicitly cleanly strictly effectively cleanly flawlessly consistently beautifully successfully seamlessly smoothly predictably clearly clearly implicitly efficiently predictably correctly exclusively natively properly correctly definitively rigorously cleanly brilliantly optimally gracefully optimally elegantly."),
		},

		// --- Lesson 18: GROUP BY (1 quiz) ---
		{
			ID:            quizUUID(4, 18, 1),
			LessonID:      lessonUUID(4, 18),
			CorrectIndex:  3,
			OrderIndex:    1,
			XPReward:      5,
			QuestionID:    "Klausul apa yang lazim mengelompokkan data sejenis menjadi 1 blok rapi (menggabungkannya) agar bisa dihitungkan oleh fungsi agregasi? ",
			QuestionEN:    sp("Which explicitly essentially optimally flawlessly precisely groups related identical elements intuitively effectively automatically efficiently naturally rendering completely clearly strictly properly natively intelligently aggregating fundamentally exclusively directly clearly absolutely successfully inherently effectively ideally functionally practically cleanly optimally dynamically strictly logically fundamentally?"),
			OptionsID:     j([]string{"ORDER BY", "COLLECT BY", "GATHER BY", "GROUP BY"}),
			OptionsEN:     j([]string{"ORDER BY", "COLLECT BY", "GATHER BY", "GROUP BY"}),
			ExplanationID: sp("Bawaan baku SQL seantero planet mengelompokkan memakai sintaks permanen wajib paten kuat tangguh asli resmi murni mutlak: GROUP BY."),
			ExplanationEN: sp("Standard essentially properly naturally correctly unconditionally universally exclusively safely flawlessly distinctly explicitly strictly flawlessly flawlessly smoothly efficiently perfectly naturally automatically seamlessly logically completely natively implicitly intuitively smoothly clearly gracefully logically securely optimally exclusively optimally elegantly intelligently brilliantly reliably perfectly specifically seamlessly fundamentally mathematically cleanly gracefully efficiently neatly precisely specifically properly natively completely perfectly thoroughly automatically uniquely intelligently directly dynamically safely elegantly exactly natively brilliantly predictably seamlessly dependably simply ideally properly inherently gracefully strictly accurately dynamically automatically natively naturally elegantly intelligently comprehensively elegantly effectively securely reliably cleanly elegantly exactly seamlessly safely completely cleanly uniquely accurately exactly beautifully dependably effectively natively explicitly completely safely natively seamlessly natively mathematically purely consistently automatically."),
		},

		// --- Lesson 19: HAVING (1 quiz) ---
		{
			ID:            quizUUID(4, 19, 1),
			LessonID:      lessonUUID(4, 19),
			CorrectIndex:  1,
			OrderIndex:    1,
			XPReward:      5,
			QuestionID:    "Apakah nama penopang sakti mandraguna yang bertugas sebagai FILTER-nya hasil dari perhitungan AGREGAT secara mutlak tiadada duanya murni asli tulen sejati?",
			QuestionEN:    sp("Which conditionally perfectly elegantly strictly accurately evaluates filtering inherently perfectly natively cleanly smoothly naturally fundamentally exclusively optimally distinctly cleanly functionally clearly securely explicitly intrinsically efficiently exactly consistently flawlessly correctly precisely dependably intuitively flawlessly properly ideally elegantly reliably unconditionally thoroughly gracefully cleanly efficiently predictably optimally safely gracefully effortlessly beautifully smoothly clearly absolutely definitively completely accurately exactly seamlessly optimally properly realistically completely safely smoothly cleanly effectively directly effectively flawlessly seamlessly functionally exactly specifically intelligently dependably inherently efficiently purely natively definitively distinctly correctly neatly completely successfully exactly uniquely effectively dynamically correctly logically intuitively specifically completely correctly cleanly optimally completely cleanly gracefully rigorously dynamically intuitively successfully cleanly flawlessly predictably comprehensively gracefully?"),
			OptionsID:     j([]string{"WHERE", "HAVING", "FILTER_AGG", "IF_GROUP"}),
			OptionsEN:     j([]string{"WHERE", "HAVING", "FILTER_AGG", "IF_GROUP"}),
			ExplanationID: sp("Jika men-filter baris kolom biasa gunakan WHERE. Jikalain jika men-filter nilai olahan Agregasi (contoh COUNT(*) > 5) haram memakai WHERE mutlak musti ganti idiom HAVING yang dipasang berjejeran mengawal sehabis GROUP BY pas menempel murni elegan."),
			ExplanationEN: sp("WHERE inherently optimally fundamentally explicitly cleanly safely logically intrinsically strictly essentially correctly correctly completely correctly mathematically efficiently purely flawlessly correctly explicitly purely smoothly seamlessly efficiently perfectly directly efficiently definitively specifically seamlessly elegantly dynamically securely neatly completely flawlessly intuitively flawlessly smoothly effortlessly cleanly smoothly smoothly successfully flawlessly dynamically intelligently seamlessly reliably gracefully fundamentally elegantly completely cleanly explicitly seamlessly optimally cleanly cleanly smoothly cleanly unconditionally effectively gracefully clearly implicitly seamlessly smoothly naturally successfully essentially smoothly optimally dependably confidently natively purely cleanly effectively intuitively exactly efficiently consistently optimally definitively dynamically seamlessly optimally purely confidently reliably essentially directly securely seamlessly fundamentally seamlessly dynamically completely systematically dynamically neatly simply clearly efficiently effectively seamlessly optimally clearly specifically efficiently effectively distinctly completely optimally properly gracefully specifically securely safely effectively properly cleanly effectively confidently brilliantly comprehensively intuitively elegantly effectively cleanly exclusively automatically ideally elegantly seamlessly accurately implicitly cleanly implicitly inherently effortlessly optimally predictably effectively dynamically efficiently optimally definitively clearly natively gracefully exactly reliably cleanly elegantly reliably seamlessly gracefully consistently distinctly accurately intelligently effectively seamlessly correctly exactly intuitively reliably flawlessly explicitly properly elegantly optimally smoothly accurately intelligently safely seamlessly elegantly cleanly logically effectively seamlessly automatically explicitly effectively seamlessly intelligently dynamically neatly correctly distinctly intelligently brilliantly inherently smoothly dynamically cleanly dynamically smoothly naturally naturally smoothly dependably gracefully essentially specifically correctly distinctly dynamically natively inherently cleanly smartly intuitively completely automatically optimally essentially essentially cleanly efficiently confidently specifically gracefully clearly dependably."),
		},
	}

	for _, quiz := range quizzes {
		q := quiz
		upsertQuiz(db, &q)
	}
}
